import type { Preset } from "@cmdgen/engine";
import type { PatchSpec, ShellDialect } from "./spec";
import { SPEC_VERSION } from "./pure";

export function newId(): string {
  if (typeof globalThis.crypto?.randomUUID === "function") return globalThis.crypto.randomUUID();
  return `id-${Date.now().toString(36)}-${(counter++).toString(36)}`;
}
let counter = 0;

export interface CreateSpecOptions {
  id?: string;
  name?: string;
  shell?: ShellDialect;
}

export function createSpec(options: CreateSpecOptions = {}): PatchSpec {
  return {
    specVersion: SPEC_VERSION,
    id: options.id ?? newId(),
    name: options.name ?? "",
    patchFile: "",
    targetFile: "",
    shell: options.shell ?? "posix",
    flags: {},
  };
}

// Every preset's `apply` replaces `flags` wholesale — same rule as every other command this session.
export const PRESETS: readonly Preset<PatchSpec>[] = [
  {
    id: "apply-patch",
    label: "Apply a patch file",
    summary: "The plain, every-day case — patch guesses the target file from the diff headers.",
    commandExample: "patch changes.patch",
    apply: (spec) => ({ ...spec, patchFile: "changes.patch", targetFile: "", flags: {} }),
  },
  {
    id: "apply-from-stdin-with-backup",
    label: "Apply from stdin, with a backup",
    summary: "--backup, no patch file given — patch reads from stdin (e.g. piped in), keeping an .orig copy.",
    commandExample: "patch -b < changes.patch",
    apply: (spec) => ({ ...spec, patchFile: "", targetFile: "", flags: { backup: true } }),
  },
  {
    id: "dry-run-check",
    label: "Check a patch with --dry-run",
    summary: "--dry-run — see whether it applies cleanly before committing to it for real.",
    commandExample: "patch --dry-run changes.patch",
    apply: (spec) => ({ ...spec, patchFile: "changes.patch", flags: { dryRun: true } }),
  },
  {
    id: "reverse-a-patch",
    label: "Reverse (un-apply) a patch",
    summary: "-R --backup — un-applies a previously applied patch, keeping a safety copy.",
    commandExample: "patch -R -b changes.patch",
    apply: (spec) => ({ ...spec, patchFile: "changes.patch", flags: { reverse: true, backup: true } }),
  },
  {
    id: "strip-one-level",
    label: "Strip one leading path component",
    summary: "-p1 — the common case for patches generated by git, which carry a/ and b/ prefixes.",
    commandExample: "patch -p 1 changes.patch",
    apply: (spec) => ({ ...spec, patchFile: "changes.patch", flags: { strip: 1 } }),
  },
];

export function getPreset(id: string): Preset<PatchSpec> | undefined {
  return PRESETS.find((p) => p.id === id);
}
