import { createFlagCatalogue, type FlagDef as FlagDefGeneric } from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type BranchingFlagDef = FlagDefGeneric<FlagGroup>;

/**
 * All 10 of `branch`'s flags live in one catalogue even though only a subset
 * applies to any given `action` (see `argv/branching.ts`'s per-action
 * dispatch) — same shape as `undo.ts`'s `RESET_FLAGS`, where the builder
 * picks which flags are even eligible to render rather than the catalogue
 * pretending they're all always relevant.
 */
export const BRANCH_FLAGS: readonly BranchingFlagDef[] = [
  {
    id: "delete",
    short: "-d",
    preferShort: true,
    long: "--delete",
    group: "options",
    kind: "boolean",
    danger: "caution",
    conflictsWith: ["forceDelete"],
    summary: "Delete the named branch(es).",
    detail: "Git itself refuses if a branch has commits not yet merged elsewhere — this alone can't force that through.",
    order: 10,
  },
  {
    id: "forceDelete",
    short: "-D",
    long: "-D",
    preferShort: true,
    group: "options",
    kind: "boolean",
    danger: "destructive",
    conflictsWith: ["delete"],
    summary: "Delete even if the branch has unmerged commits.",
    detail: "Bypasses git's own safety check — commits reachable only from this branch are lost for good. -d is the safer alternative.",
    order: 20,
  },
  {
    id: "force",
    short: "-f",
    preferShort: true,
    long: "--force",
    group: "options",
    kind: "boolean",
    danger: "destructive",
    summary: "Reset an existing branch to the given start point, even if it isn't a descendant.",
    detail: "Create-form only. Silently moves an existing branch's tip, which can strand commits that were only reachable from it.",
    order: 30,
  },
  {
    id: "forceMove",
    short: "-M",
    long: "-M",
    preferShort: true,
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Force the rename/copy, overwriting an existing branch already named the target.",
    detail: "Silently overwrites whatever the target name already pointed to.",
    order: 40,
  },
  {
    id: "all",
    short: "-a",
    preferShort: true,
    long: "--all",
    group: "options",
    kind: "boolean",
    summary: "List both local and remote-tracking branches.",
    detail: "List-only — has no effect on create/delete/rename/copy.",
    order: 50,
  },
  {
    id: "remotes",
    short: "-r",
    preferShort: true,
    long: "--remotes",
    group: "options",
    kind: "boolean",
    summary: "Act on remote-tracking branches instead of local ones.",
    detail: "With list, shows remote-tracking branches. With delete, removes a LOCAL remote-tracking ref only — it never touches anything on the actual remote.",
    order: 60,
  },
  {
    id: "setUpstreamTo",
    long: "--set-upstream-to",
    group: "options",
    kind: "text",
    arg: { placeholder: "origin/main" },
    summary: "Set the upstream tracking branch for the named branch.",
    detail: "Equivalent to what -u/--set-upstream did on push, but standalone — doesn't push anything itself.",
    order: 70,
  },
  {
    id: "unsetUpstream",
    long: "--unset-upstream",
    group: "options",
    kind: "boolean",
    conflictsWith: ["setUpstreamTo"],
    summary: "Remove the upstream tracking configuration for the named branch.",
    detail: "The branch keeps existing — only the link to its remote-tracking counterpart is cleared.",
    order: 80,
  },
  {
    id: "contains",
    long: "--contains",
    group: "options",
    kind: "text",
    arg: { placeholder: "HEAD" },
    summary: "List only branches that contain this commit.",
    detail: "List-only filter — combines with a names pattern rather than replacing it.",
    order: 90,
  },
  {
    id: "sort",
    long: "--sort",
    group: "options",
    kind: "text",
    arg: { placeholder: "-committerdate" },
    summary: "Sort listed branches by this key instead of alphabetically.",
    detail: "Prefix with - to reverse, e.g. -committerdate for most-recently-committed first.",
    order: 100,
  },
] as const;
export const BRANCH_CATALOGUE = createFlagCatalogue<FlagGroup>(BRANCH_FLAGS);

export const SWITCH_FLAGS: readonly BranchingFlagDef[] = [
  {
    id: "create",
    short: "-c",
    preferShort: true,
    long: "--create",
    group: "options",
    kind: "boolean",
    summary: "Create a new branch named below, then switch to it.",
    detail: "Real invocation shape is `-c <new-branch> [<start-point>]` — rendering is driven by the New branch name field, not this toggle alone.",
    order: 10,
  },
  {
    id: "forceCreate",
    short: "-C",
    long: "-C",
    preferShort: true,
    group: "options",
    kind: "boolean",
    danger: "destructive",
    summary: "Like Create, but resets an existing branch of that name to the start point.",
    detail: "Unlike plain -c, this doesn't refuse when the new branch name already exists — it silently overwrites where that branch pointed.",
    order: 20,
  },
  {
    id: "detach",
    short: "-d",
    preferShort: true,
    long: "--detach",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Switch to a commit directly, not a branch (detached HEAD).",
    detail: "Commits made in this state are only reachable while HEAD stays there — create a branch before switching away if they should be kept.",
    order: 30,
  },
  {
    id: "discardChanges",
    long: "--discard-changes",
    group: "options",
    kind: "boolean",
    danger: "destructive",
    conflictsWith: ["merge"],
    summary: "Throw away uncommitted worktree changes instead of blocking the switch.",
    detail: "No confirmation, no stash — the edits are simply gone once this runs.",
    order: 40,
  },
  {
    id: "merge",
    short: "-m",
    preferShort: true,
    long: "--merge",
    group: "options",
    kind: "boolean",
    conflictsWith: ["discardChanges"],
    summary: "Try to carry uncommitted changes across the switch via a three-way merge.",
    detail: "The safer alternative to Discard changes — git stops and asks rather than silently dropping anything if the merge would conflict.",
    order: 50,
  },
  {
    id: "track",
    long: "--track",
    group: "options",
    kind: "boolean",
    conflictsWith: ["noTrack"],
    summary: "Set up the new branch to track its start point.",
    detail: "Only meaningful together with a new branch name.",
    order: 60,
  },
  {
    id: "noTrack",
    long: "--no-track",
    group: "options",
    kind: "boolean",
    conflictsWith: ["track"],
    summary: "Don't set up tracking, even if it would otherwise happen automatically.",
    detail: "Overrides the branch.autoSetupMerge default for this one switch.",
    order: 70,
  },
  {
    id: "guessTracking",
    long: "--guess",
    group: "options",
    kind: "boolean",
    summary: "Guess a new branch's tracking remote from a single matching remote-tracking name.",
    detail: "This is git's default behavior — the flag exists mainly to make it explicit, or paired with --no-guess elsewhere to turn it off.",
    order: 80,
  },
  {
    id: "orphan",
    long: "--orphan",
    group: "options",
    kind: "boolean",
    summary: "Create a new branch with no history at all, reusing the New branch name field.",
    detail: "The next commit on it will be a root commit — nothing before it, not even from the current branch.",
    order: 90,
  },
  {
    id: "ignoreOtherWorktrees",
    long: "--ignore-other-worktrees",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Allow switching to a branch that's already checked out in another worktree.",
    detail: "Git normally refuses this to prevent two worktrees from pointing at the same branch at once.",
    order: 100,
  },
] as const;
export const SWITCH_CATALOGUE = createFlagCatalogue<FlagGroup>(SWITCH_FLAGS);
