import { createFlagCatalogue, type FlagDef as FlagDefGeneric } from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type DiffGrepFlagDef = FlagDefGeneric<FlagGroup>;

/**
 * `staged` models git's `--staged`/`--cached` pair as ONE boolean — they are
 * true synonyms (not two independent toggles), so a second flag would only
 * let the UI express a distinction real git doesn't have.
 */
export const DIFF_FLAGS: readonly DiffGrepFlagDef[] = [
  {
    id: "staged",
    long: "--staged",
    group: "options",
    kind: "boolean",
    summary: "Diff the index against HEAD instead of the working tree against the index.",
    detail: "The same thing as --cached — real git treats them as exact synonyms, so only one is modeled here. Real git rejects combining this with a revision range.",
    order: 10,
  },
  {
    id: "stat",
    long: "--stat",
    group: "options",
    kind: "boolean",
    summary: "Show a per-file change summary instead of the full diff.",
    detail: "Lists files touched and a line-count bar.",
    order: 20,
  },
  {
    id: "nameOnly",
    long: "--name-only",
    group: "options",
    kind: "boolean",
    summary: "List only the names of changed files.",
    detail: "No diff body, no change stats — just the file list.",
    order: 30,
  },
  {
    id: "nameStatus",
    long: "--name-status",
    group: "options",
    kind: "boolean",
    summary: "List changed file names with their status (A/M/D/R...).",
    detail: "Like --name-only, but with a leading letter for added/modified/deleted/renamed.",
    order: 40,
  },
  {
    id: "noIndex",
    long: "--no-index",
    group: "options",
    kind: "boolean",
    summary: "Diff two arbitrary files or directories outside of any git repository.",
    detail: "Lets git diff work like plain diff(1) on files git doesn't even track. Real git rejects combining this with a revision range.",
    order: 50,
  },
  {
    id: "wordDiff",
    long: "--word-diff",
    group: "options",
    kind: "text",
    arg: { placeholder: "color" },
    summary: "Show a word-level diff instead of the usual line-level one.",
    detail: "Accepts color (the default when just enabling it), plain, or none.",
    order: 60,
  },
  {
    id: "ignoreAllSpace",
    short: "-w",
    preferShort: true,
    long: "--ignore-all-space",
    group: "options",
    kind: "boolean",
    summary: "Ignore whitespace entirely when comparing lines.",
    detail: "Lines that differ only in whitespace amount or placement are treated as identical.",
    order: 70,
  },
  {
    id: "ignoreSpaceChange",
    short: "-b",
    preferShort: true,
    long: "--ignore-space-change",
    group: "options",
    kind: "boolean",
    summary: "Treat runs of whitespace as equivalent, but still require whitespace where none existed.",
    detail: "Softer than --ignore-all-space — a line with no space at all still differs from one with some.",
    order: 80,
  },
  {
    id: "colorMoved",
    long: "--color-moved",
    group: "options",
    kind: "text",
    arg: { placeholder: "zebra" },
    summary: "Highlight moved lines with their own color instead of red/green delete-add.",
    detail: "Accepts a detection mode, e.g. zebra (the common default) or plain.",
    order: 90,
  },
  {
    id: "unified",
    short: "-U",
    long: "--unified",
    group: "options",
    kind: "number",
    arg: { placeholder: "3" },
    summary: "Number of context lines shown around each change.",
    detail: "Real git also accepts this attached to -U with no space (-U3) — modeled here as --unified=<n>, an equally valid real spelling.",
    order: 100,
  },
  {
    id: "diffAlgorithm",
    long: "--diff-algorithm",
    group: "options",
    kind: "text",
    arg: { placeholder: "histogram" },
    summary: "Which diff algorithm to use.",
    detail: "Accepts default, myers, minimal, patience, or histogram — histogram is generally the best for source code.",
    order: 110,
  },
  {
    id: "submodule",
    long: "--submodule",
    group: "options",
    kind: "text",
    arg: { placeholder: "log" },
    summary: "How to show changes to submodules.",
    detail: "Accepts short (the default, just the two commit hashes), log (a one-line summary per commit), or diff (a full recursive diff).",
    order: 120,
  },
] as const;
export const DIFF_CATALOGUE = createFlagCatalogue<FlagGroup>(DIFF_FLAGS);

/**
 * `context` renders as `-C <N>` — same short-form trick as `@cmdgen/grep`'s
 * own -C: `long` is set to the short token itself with a space separator,
 * since the generic renderer never falls back from `long` to `short`.
 */
export const GREP_FLAGS: readonly DiffGrepFlagDef[] = [
  {
    id: "ignoreCase",
    short: "-i",
    preferShort: true,
    long: "--ignore-case",
    group: "options",
    kind: "boolean",
    summary: "Match regardless of case.",
    detail: "\"TODO\" matches \"todo\", \"ToDo\", and every other capitalization.",
    order: 10,
  },
  {
    id: "lineNumber",
    short: "-n",
    preferShort: true,
    long: "--line-number",
    group: "options",
    kind: "boolean",
    summary: "Prefix each matching line with its line number.",
    detail: "Line numbers restart at 1 for each file.",
    order: 20,
  },
  {
    id: "count",
    short: "-c",
    preferShort: true,
    long: "--count",
    group: "options",
    kind: "boolean",
    summary: "Print only a count of matching lines per file, not the lines themselves.",
    detail: "One number per file, not a single grand total.",
    order: 30,
  },
  {
    id: "filesWithMatches",
    short: "-l",
    preferShort: true,
    long: "--files-with-matches",
    group: "options",
    kind: "boolean",
    summary: "Print only the names of files containing a match.",
    detail: "Stops scanning each file at its first match.",
    order: 40,
  },
  {
    id: "invertMatch",
    short: "-v",
    preferShort: true,
    long: "--invert-match",
    group: "options",
    kind: "boolean",
    summary: "Print lines that do NOT match, instead of lines that do.",
    detail: "Useful for filtering out noise, e.g. finding lines that don't mention a TODO marker.",
    order: 50,
  },
  {
    id: "wordRegexp",
    short: "-w",
    preferShort: true,
    long: "--word-regexp",
    group: "options",
    kind: "boolean",
    summary: "Only match whole words.",
    detail: "The match must be bounded by non-word characters or the start/end of the line.",
    order: 60,
  },
  {
    id: "extendedRegexp",
    short: "-E",
    preferShort: true,
    long: "--extended-regexp",
    group: "options",
    kind: "boolean",
    conflictsWith: ["fixedStrings", "perlRegexp"],
    summary: "Interpret the pattern as an extended regular expression (ERE).",
    detail: "Mutually exclusive with -F and -P — real git rejects combining any two.",
    order: 70,
  },
  {
    id: "fixedStrings",
    short: "-F",
    preferShort: true,
    long: "--fixed-strings",
    group: "options",
    kind: "boolean",
    conflictsWith: ["extendedRegexp", "perlRegexp"],
    summary: "Treat the pattern as a literal string, not a regular expression.",
    detail: "Mutually exclusive with -E and -P — real git rejects combining any two.",
    order: 80,
  },
  {
    id: "perlRegexp",
    short: "-P",
    preferShort: true,
    long: "--perl-regexp",
    group: "options",
    kind: "boolean",
    conflictsWith: ["extendedRegexp", "fixedStrings"],
    summary: "Interpret the pattern as a Perl-compatible regular expression (PCRE).",
    detail: "Mutually exclusive with -E and -F — real git rejects combining any two.",
    order: 90,
  },
  {
    id: "cached",
    long: "--cached",
    group: "options",
    kind: "boolean",
    summary: "Search the index (staged content) instead of the working tree.",
    detail: "Sees staged edits that haven't been written back to disk in that form.",
    order: 100,
  },
  {
    id: "untracked",
    long: "--untracked",
    group: "options",
    kind: "boolean",
    summary: "Also search untracked files, not just tracked ones.",
    detail: "Still respects .gitignore, unless combined with additional flags that override it.",
    order: 110,
  },
  {
    id: "recurseSubmodules",
    long: "--recurse-submodules",
    group: "options",
    kind: "boolean",
    summary: "Also search inside checked-out submodules.",
    detail: "Without this, a submodule's contents are invisible to the search.",
    order: 120,
  },
  {
    id: "context",
    short: "-C",
    long: "-C",
    group: "options",
    kind: "number",
    arg: { placeholder: "3", separator: " " },
    summary: "Print N lines of context before and after each match.",
    detail: "Separate -A (after) and -B (before) counts exist too, not modeled here since -C covers the common symmetric case.",
    order: 130,
  },
  {
    id: "openFilesInPager",
    short: "-O",
    preferShort: true,
    long: "--open-files-in-pager",
    group: "options",
    kind: "boolean",
    summary: "Open the matching files in a pager/editor instead of printing matches.",
    detail: "Not useful in a generated, non-interactive command — included because it's a real flag some workflows rely on.",
    order: 140,
  },
] as const;
export const GREP_CATALOGUE = createFlagCatalogue<FlagGroup>(GREP_FLAGS);
