import { createFlagCatalogue, type FlagDef as FlagDefGeneric } from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type HistoryFlagDef = FlagDefGeneric<FlagGroup>;

/**
 * `maxCount` renders as `-n <N>` rather than `--max-count=<N>` — real-world
 * git usage is overwhelmingly `-n`. The generic renderer only ever emits
 * `def.long` (never falls back to `short`, even with `preferShort`), so the
 * short form has to be `long` itself with a space separator — same trick
 * `@cmdgen/head`'s `-n`/`@cmdgen/grep`'s `-C` already use.
 */
export const LOG_FLAGS: readonly HistoryFlagDef[] = [
  {
    id: "oneline",
    long: "--oneline",
    group: "options",
    kind: "boolean",
    summary: "Condense each commit to a single line.",
    detail: "Shows the abbreviated hash and subject line only — no author, date, or body.",
    order: 10,
  },
  {
    id: "graph",
    long: "--graph",
    group: "options",
    kind: "boolean",
    summary: "Draw a text-based branch/merge graph on the left.",
    detail: "Most useful combined with --oneline and --all.",
    order: 20,
  },
  {
    id: "all",
    long: "--all",
    group: "options",
    kind: "boolean",
    summary: "Show history reachable from every ref, not just HEAD.",
    detail: "Includes every branch and tag, not only the one currently checked out.",
    order: 30,
  },
  {
    id: "decorate",
    long: "--decorate",
    group: "options",
    kind: "text",
    arg: { placeholder: "short" },
    summary: "Print the branch/tag names pointing at each commit.",
    detail: "Accepts short, full, auto, or no — bare --decorate (short) covers most cases.",
    order: 40,
  },
  {
    id: "maxCount",
    short: "-n",
    long: "-n",
    group: "options",
    kind: "number",
    arg: { placeholder: "10", separator: " " },
    summary: "Limit the number of commits shown.",
    detail: "Real-world usage is almost always -n rather than the equivalent --max-count=.",
    order: 50,
  },
  {
    id: "since",
    long: "--since",
    group: "options",
    kind: "text",
    arg: { placeholder: "2024-01-01" },
    summary: "Only show commits more recent than this date.",
    detail: "Accepts anything git's date parser understands, e.g. \"2 weeks ago\".",
    order: 60,
  },
  {
    id: "until",
    long: "--until",
    group: "options",
    kind: "text",
    arg: { placeholder: "2024-12-31" },
    summary: "Only show commits older than this date.",
    detail: "Combine with --since to bound a window.",
    order: 70,
  },
  {
    id: "author",
    long: "--author",
    group: "options",
    kind: "text",
    arg: { placeholder: "Jane Doe" },
    summary: "Only show commits whose author matches this pattern.",
    detail: "Matched as a regular expression against the author field, not an exact string.",
    order: 80,
  },
  {
    id: "commitGrep",
    long: "--grep",
    group: "options",
    kind: "text",
    arg: { placeholder: "fix the bug" },
    summary: "Only show commits whose message matches this pattern.",
    detail: "Searches commit messages — a different thing entirely from the grep subcommand, which searches file contents.",
    order: 90,
  },
  {
    id: "follow",
    long: "--follow",
    group: "options",
    kind: "boolean",
    summary: "Continue history across a rename, for a single followed file.",
    detail: "Only meaningful with exactly one path — real git requires it.",
    order: 100,
  },
  {
    id: "patch",
    short: "-p",
    preferShort: true,
    long: "--patch",
    group: "options",
    kind: "boolean",
    summary: "Show the diff introduced by each commit.",
    detail: "Prints the full patch alongside each log entry.",
    order: 110,
  },
  {
    id: "stat",
    long: "--stat",
    group: "options",
    kind: "boolean",
    summary: "Show a per-file change summary after each commit.",
    detail: "Lists files touched and a line-count bar, without the full diff.",
    order: 120,
  },
  {
    id: "merges",
    long: "--merges",
    group: "options",
    kind: "boolean",
    conflictsWith: ["noMerges"],
    summary: "Only show merge commits.",
    detail: "Hides every ordinary, single-parent commit.",
    order: 130,
  },
  {
    id: "noMerges",
    long: "--no-merges",
    group: "options",
    kind: "boolean",
    conflictsWith: ["merges"],
    summary: "Hide merge commits.",
    detail: "Only shows ordinary, single-parent commits.",
    order: 140,
  },
  {
    id: "firstParent",
    long: "--first-parent",
    group: "options",
    kind: "boolean",
    summary: "Follow only the first parent of each merge.",
    detail: "Gives a linear history that mirrors what got merged into the current branch, ignoring the commits brought in from the side branch.",
    order: 150,
  },
] as const;
export const LOG_CATALOGUE = createFlagCatalogue<FlagGroup>(LOG_FLAGS);

export const SHOW_FLAGS: readonly HistoryFlagDef[] = [
  {
    id: "stat",
    long: "--stat",
    group: "options",
    kind: "boolean",
    summary: "Show a per-file change summary.",
    detail: "Lists files touched and a line-count bar, without the full diff.",
    order: 10,
  },
  {
    id: "patch",
    short: "-p",
    preferShort: true,
    long: "--patch",
    group: "options",
    kind: "boolean",
    conflictsWith: ["noPatch"],
    summary: "Show the diff, even for a merge commit (the default for non-merges).",
    detail: "Merge commits are otherwise shown without a diff — this forces one.",
    order: 20,
  },
  {
    id: "noPatch",
    short: "-s",
    preferShort: true,
    long: "--no-patch",
    group: "options",
    kind: "boolean",
    conflictsWith: ["patch"],
    summary: "Suppress the diff, showing only the commit metadata.",
    detail: "Useful together with --stat/--name-only when the diff body itself isn't wanted.",
    order: 30,
  },
  {
    id: "nameOnly",
    long: "--name-only",
    group: "options",
    kind: "boolean",
    summary: "List only the names of changed files.",
    detail: "No diff body, no change stats — just the file list.",
    order: 40,
  },
  {
    id: "nameStatus",
    long: "--name-status",
    group: "options",
    kind: "boolean",
    summary: "List changed file names with their status (A/M/D/R...).",
    detail: "Like --name-only, but with a leading letter for added/modified/deleted/renamed.",
    order: 50,
  },
  {
    id: "format",
    long: "--format",
    group: "options",
    kind: "text",
    arg: { placeholder: "%H %s" },
    summary: "Print the commit metadata using this pretty-format string.",
    detail: "Same placeholder syntax as git log's --format, e.g. %H for the full hash, %s for the subject.",
    order: 60,
  },
  {
    id: "abbrevCommit",
    long: "--abbrev-commit",
    group: "options",
    kind: "boolean",
    summary: "Show abbreviated commit hashes instead of the full 40 characters.",
    detail: "Just as unambiguous within the repo, and much shorter to read.",
    order: 70,
  },
  {
    id: "showSignature",
    long: "--show-signature",
    group: "options",
    kind: "boolean",
    summary: "Verify and show the GPG signature of a signed commit or tag.",
    detail: "Prints nothing extra if the object isn't signed.",
    order: 80,
  },
] as const;
export const SHOW_CATALOGUE = createFlagCatalogue<FlagGroup>(SHOW_FLAGS);

export const BLAME_FLAGS: readonly HistoryFlagDef[] = [
  {
    id: "lineRange",
    short: "-L",
    long: "-L",
    group: "options",
    kind: "text",
    arg: { placeholder: "10,20", separator: " " },
    summary: "Only annotate the given line range.",
    detail: "Real git blame has no long form for this — -L is the only spelling.",
    order: 10,
  },
  {
    id: "showEmail",
    short: "-e",
    preferShort: true,
    long: "--show-email",
    group: "options",
    kind: "boolean",
    summary: "Show the author's email instead of their name.",
    detail: "Useful when names collide but emails don't.",
    order: 20,
  },
  {
    id: "showName",
    short: "-f",
    preferShort: true,
    long: "--show-name",
    group: "options",
    kind: "boolean",
    summary: "Always show the source filename for each line.",
    detail: "Normally only shown once the line's origin crosses a rename.",
    order: 30,
  },
  {
    id: "showNumber",
    short: "-n",
    preferShort: true,
    long: "--show-number",
    group: "options",
    kind: "boolean",
    summary: "Show the original line number in the source commit, not the current file.",
    detail: "Useful once lines have moved around across renames/reflows.",
    order: 40,
  },
  {
    id: "ignoreRev",
    long: "--ignore-rev",
    group: "options",
    kind: "text",
    arg: { placeholder: "abcdef1" },
    summary: "Ignore this revision when assigning blame.",
    detail: "Attributes lines it touched to whatever commit came before it instead — useful for skipping a mass-reformat commit.",
    order: 50,
  },
  {
    id: "ignoreRevsFile",
    long: "--ignore-revs-file",
    group: "options",
    kind: "path",
    arg: { placeholder: ".git-blame-ignore-revs" },
    summary: "Ignore every revision listed in this file.",
    detail: "One revision per line — the same mechanism GitHub's blame view uses.",
    order: 60,
  },
  {
    id: "contents",
    long: "--contents",
    group: "options",
    kind: "path",
    arg: { placeholder: "path/to/file.txt" },
    summary: "Annotate the working file's current contents instead of a committed version.",
    detail: "Blames uncommitted local edits against history, using this file's on-disk contents as the tip.",
    order: 70,
  },
  {
    id: "porcelain",
    long: "--porcelain",
    group: "options",
    kind: "boolean",
    conflictsWith: ["linePorcelain"],
    summary: "Machine-readable output, one block of metadata per group of adjacent lines.",
    detail: "Intended for scripts, not for reading directly.",
    order: 80,
  },
  {
    id: "linePorcelain",
    long: "--line-porcelain",
    group: "options",
    kind: "boolean",
    conflictsWith: ["porcelain"],
    summary: "Like --porcelain, but repeats the metadata for every single line.",
    detail: "Larger output than --porcelain, but simpler for a script to parse line-by-line.",
    order: 90,
  },
] as const;
export const BLAME_CATALOGUE = createFlagCatalogue<FlagGroup>(BLAME_FLAGS);

export const STATUS_FLAGS: readonly HistoryFlagDef[] = [
  {
    id: "short",
    short: "-s",
    preferShort: true,
    long: "--short",
    group: "options",
    kind: "boolean",
    conflictsWith: ["long", "porcelain"],
    summary: "Compact, two-column-code output.",
    detail: "Mutually exclusive with --long and --porcelain — real git rejects combining any two of the three.",
    order: 10,
  },
  {
    id: "branch",
    short: "-b",
    preferShort: true,
    long: "--branch",
    group: "options",
    kind: "boolean",
    summary: "Show the current branch and its upstream tracking state too.",
    detail: "Adds a leading ## line naming the branch, ahead/behind counts included.",
    order: 20,
  },
  {
    id: "porcelain",
    long: "--porcelain",
    group: "options",
    kind: "text",
    arg: { placeholder: "v1" },
    conflictsWith: ["short", "long"],
    summary: "Stable, script-friendly output format.",
    detail: "Accepts a version (v1 is the default, v2 adds more detail) — never changes across git versions, unlike the human-facing default. Mutually exclusive with --short and --long.",
    order: 30,
  },
  {
    id: "long",
    long: "--long",
    group: "options",
    kind: "boolean",
    conflictsWith: ["short", "porcelain"],
    summary: "The default, verbose human-readable format — explicit, to override -s/--porcelain.",
    detail: "Mutually exclusive with --short and --porcelain — real git rejects combining any two of the three.",
    order: 40,
  },
  {
    id: "untrackedFiles",
    long: "--untracked-files",
    group: "options",
    kind: "text",
    arg: { placeholder: "all" },
    summary: "How much detail to show for untracked files.",
    detail: "Accepts no, normal, or all — all recurses into untracked directories instead of naming just the directory.",
    order: 50,
  },
  {
    id: "ignored",
    long: "--ignored",
    group: "options",
    kind: "text",
    arg: { placeholder: "traditional" },
    summary: "Show ignored files too.",
    detail: "Accepts traditional, no, or matching — matching also reports which rule ignored each file.",
    order: 60,
  },
  {
    id: "ignoreSubmodules",
    long: "--ignore-submodules",
    group: "options",
    kind: "text",
    arg: { placeholder: "all" },
    summary: "How much submodule state change to report.",
    detail: "Accepts none, untracked, dirty, or all.",
    order: 70,
  },
  {
    id: "findRenames",
    long: "--find-renames",
    group: "options",
    kind: "text",
    arg: { placeholder: "50%" },
    summary: "Detect renamed files, at this similarity threshold.",
    detail: "Without this, a delete-plus-add pair is reported as two unrelated changes rather than one rename.",
    order: 80,
  },
] as const;
export const STATUS_CATALOGUE = createFlagCatalogue<FlagGroup>(STATUS_FLAGS);
