import { createFlagCatalogue, type FlagDef as FlagDefGeneric } from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type MergeRebaseFlagDef = FlagDefGeneric<FlagGroup>;

/**
 * `strategy`/`strategy-option` are shared verbatim across merge/rebase/cherry-pick
 * (real git implements all three on top of the same merge machinery), so each
 * catalogue below repeats the same two entries rather than sharing one array —
 * matching this file's own per-subcommand-catalogue discipline (see
 * `catalogue/staging.ts`/`catalogue/undo.ts`), not a shared "common" import.
 */
export const MERGE_FLAGS: readonly MergeRebaseFlagDef[] = [
  {
    id: "noFf",
    long: "--no-ff",
    group: "options",
    kind: "boolean",
    conflictsWith: ["ffOnly"],
    summary: "Always create a merge commit, even when a fast-forward is possible.",
    detail: "Without this, a merge that could fast-forward moves the branch pointer instead of recording a merge — this forces a real merge commit either way.",
    order: 10,
  },
  {
    id: "ffOnly",
    long: "--ff-only",
    group: "options",
    kind: "boolean",
    conflictsWith: ["noFf"],
    summary: "Refuse to merge unless it can fast-forward.",
    detail: "The safe choice — aborts instead of creating a merge commit or touching the working tree in any way that isn't a pure pointer move.",
    order: 20,
  },
  {
    id: "squash",
    long: "--squash",
    group: "options",
    kind: "boolean",
    summary: "Combine the merged branch's changes into the working tree/index without recording a merge.",
    detail: "Produces no merge commit and does not record the other branch as a parent — history ends up looking like the merge never happened.",
    order: 30,
  },
  {
    id: "noCommit",
    long: "--no-commit",
    group: "options",
    kind: "boolean",
    summary: "Stage the merge result without creating the merge commit yet.",
    detail: "Lets you inspect, amend, or add to the merge before actually committing it.",
    order: 40,
  },
  {
    id: "strategy",
    long: "--strategy",
    group: "options",
    kind: "text",
    arg: { placeholder: "recursive" },
    summary: "Use a specific merge strategy.",
    detail: "e.g. recursive, resolve, octopus, ours, subtree — see git-merge-strategies(7).",
    order: 50,
  },
  {
    id: "strategyOption",
    short: "-X",
    preferShort: true,
    long: "--strategy-option",
    group: "options",
    kind: "text",
    arg: { placeholder: "ours" },
    summary: "Pass an option through to the merge strategy.",
    detail: "ours/theirs silently drop the losing side's conflicting hunks instead of merging them — flagged separately when set to either.",
    order: 60,
  },
  {
    id: "allowUnrelatedHistories",
    long: "--allow-unrelated-histories",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Allow merging two branches that share no common commit history.",
    detail: "Normally git refuses this as a sanity check against merging the wrong repository. Real uses include combining two previously separate repositories.",
    order: 70,
  },
] as const;
export const MERGE_CATALOGUE = createFlagCatalogue<FlagGroup>(MERGE_FLAGS);

export const REBASE_FLAGS: readonly MergeRebaseFlagDef[] = [
  {
    id: "interactive",
    short: "-i",
    preferShort: true,
    long: "--interactive",
    group: "options",
    kind: "boolean",
    summary: "Open an editable to-do list of commits before replaying them.",
    detail: "Lets you reorder, squash, reword, drop, or edit individual commits as part of the rebase.",
    order: 10,
  },
  {
    id: "autosquash",
    long: "--autosquash",
    group: "options",
    kind: "boolean",
    summary: "Automatically move squash!/fixup! commits next to the commits they target.",
    detail: "Only takes effect with an interactive rebase — reorders the to-do list before it's shown.",
    order: 20,
  },
  {
    id: "autostash",
    long: "--autostash",
    group: "options",
    kind: "boolean",
    summary: "Automatically stash uncommitted changes before starting, and reapply them after.",
    detail: "Safety-improving — lets a rebase proceed on a dirty working tree without a manual stash/unstash first.",
    order: 30,
  },
  {
    id: "force",
    short: "-f",
    preferShort: true,
    long: "--force-rebase",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Force a rebase even when the branch is already up to date with its upstream.",
    detail: "Normally rebase takes a no-op fast path when nothing would actually change; this bypasses that and replays every commit anyway.",
    order: 40,
  },
  {
    id: "strategy",
    long: "--strategy",
    group: "options",
    kind: "text",
    arg: { placeholder: "recursive" },
    summary: "Use a specific merge strategy while replaying commits.",
    detail: "e.g. recursive, resolve, ort — see git-merge-strategies(7).",
    order: 50,
  },
  {
    id: "strategyOption",
    short: "-X",
    preferShort: true,
    long: "--strategy-option",
    group: "options",
    kind: "text",
    arg: { placeholder: "ours" },
    summary: "Pass an option through to the merge strategy.",
    detail: "Applied to every commit replayed during the rebase, same as merge's -X.",
    order: 60,
  },
  {
    id: "rebaseMerges",
    long: "--rebase-merges",
    group: "options",
    kind: "boolean",
    summary: "Preserve the branch structure of merge commits being replayed instead of flattening them.",
    detail: "Without this, rebase linearizes history — merge commits in the replayed range are otherwise dropped.",
    order: 70,
  },
  {
    id: "root",
    long: "--root",
    group: "options",
    kind: "boolean",
    summary: "Rebase all commits reachable from the branch, back to the very first one.",
    detail: "Only meaningful with no explicit upstream — real git rejects combining it with one.",
    order: 80,
  },
] as const;
export const REBASE_CATALOGUE = createFlagCatalogue<FlagGroup>(REBASE_FLAGS);

export const CHERRY_PICK_FLAGS: readonly MergeRebaseFlagDef[] = [
  {
    id: "noCommit",
    short: "-n",
    preferShort: true,
    long: "--no-commit",
    group: "options",
    kind: "boolean",
    summary: "Apply the change but don't create a commit for it.",
    detail: "Leaves the picked change staged, so it can be combined with other edits before committing.",
    order: 10,
  },
  {
    id: "edit",
    short: "-e",
    preferShort: true,
    long: "--edit",
    group: "options",
    kind: "boolean",
    summary: "Open an editor to modify the commit message before committing.",
    detail: "Lets you review or change the original commit's message rather than reusing it verbatim.",
    order: 20,
  },
  {
    id: "mainline",
    short: "-m",
    long: "--mainline",
    group: "options",
    kind: "number",
    arg: { placeholder: "1" },
    summary: "Which parent to treat as mainline when picking a merge commit.",
    detail: "Required when the target commit is a merge — can't be validated statically.",
    order: 30,
  },
  {
    id: "signoff",
    short: "-s",
    preferShort: true,
    long: "--signoff",
    group: "options",
    kind: "boolean",
    summary: "Add a Signed-off-by trailer to the new commit.",
    detail: "Common in projects that require contributor sign-off on every commit.",
    order: 40,
  },
  {
    id: "strategy",
    long: "--strategy",
    group: "options",
    kind: "text",
    arg: { placeholder: "recursive" },
    summary: "Use a specific merge strategy when applying the change.",
    detail: "e.g. recursive, resolve, ort — see git-merge-strategies(7).",
    order: 50,
  },
  {
    id: "strategyOption",
    short: "-X",
    preferShort: true,
    long: "--strategy-option",
    group: "options",
    kind: "text",
    arg: { placeholder: "ours" },
    summary: "Pass an option through to the merge strategy.",
    detail: "Applied while resolving the pick, same as merge's -X.",
    order: 60,
  },
  {
    id: "keepRedundantCommits",
    long: "--keep-redundant-commits",
    group: "options",
    kind: "boolean",
    summary: "Create an empty commit instead of skipping a pick that would introduce no changes.",
    detail: "Without this, a pick whose changes are already present is skipped entirely rather than recorded.",
    order: 70,
  },
  {
    id: "allowEmpty",
    long: "--allow-empty",
    group: "options",
    kind: "boolean",
    summary: "Allow recording a commit even if the pick introduces no changes.",
    detail: "Normally an empty resulting commit stops the cherry-pick with an error.",
    order: 80,
  },
  {
    id: "ff",
    long: "--ff",
    group: "options",
    kind: "boolean",
    summary: "Fast-forward if the current branch already has the picked commit as an ancestor.",
    detail: "Avoids creating a duplicate commit when the pick would otherwise be a no-op replay.",
    order: 90,
  },
] as const;
export const CHERRY_PICK_CATALOGUE = createFlagCatalogue<FlagGroup>(CHERRY_PICK_FLAGS);
