import { createFlagCatalogue, type FlagDef as FlagDefGeneric } from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type RemoteFlagDef = FlagDefGeneric<FlagGroup>;

// ── fetch ───────────────────────────────────────────────────────────────────

export const FETCH_FLAGS: readonly RemoteFlagDef[] = [
  {
    id: "all",
    long: "--all",
    group: "options",
    kind: "boolean",
    summary: "Fetch every remote instead of just one.",
    detail: "Real git rejects this combined with an explicit remote — flagged by lint, not silently dropped.",
    order: 10,
  },
  {
    id: "prune",
    short: "-p",
    preferShort: true,
    long: "--prune",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Remove local remote-tracking refs that no longer exist on the remote.",
    detail: "Deletes local tracking refs, e.g. origin/some-deleted-branch, not just skips fetching them.",
    order: 20,
  },
  {
    id: "pruneTags",
    short: "-P",
    preferShort: true,
    long: "--prune-tags",
    group: "options",
    kind: "boolean",
    danger: "caution",
    requires: ["prune"],
    summary: "Also remove local tags that no longer exist on the remote.",
    detail: "More surprising than plain prune — tags are usually treated as permanent, immutable markers.",
    order: 30,
  },
  {
    id: "tags",
    short: "-t",
    long: "--tags",
    group: "options",
    kind: "boolean",
    conflictsWith: ["noTags"],
    summary: "Fetch all tags in addition to whatever else this fetch would bring.",
    detail: "Beyond the tags reachable from fetched branch history.",
    order: 40,
  },
  {
    id: "noTags",
    short: "-n",
    long: "--no-tags",
    group: "options",
    kind: "boolean",
    conflictsWith: ["tags"],
    summary: "Don't fetch any tags at all.",
    detail: "Overrides the remote.<name>.tagOpt config and the usual auto-follow behavior.",
    order: 50,
  },
  {
    id: "depth",
    long: "--depth",
    group: "options",
    kind: "number",
    arg: { placeholder: "1", min: 1, separator: "=" },
    summary: "Deepen or shorten the history fetched to this many commits.",
    detail: "Turns (or keeps) the local repository into a shallow clone from this remote's perspective.",
    order: 60,
  },
  {
    id: "force",
    short: "-f",
    preferShort: true,
    long: "--force",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Allow non-fast-forward updates to local remote-tracking refs.",
    detail: "Without this, fetch refuses to move a tracking ref anywhere but forward.",
    order: 70,
  },
  {
    id: "dryRun",
    long: "--dry-run",
    group: "options",
    kind: "boolean",
    summary: "Show what would be fetched without actually fetching anything.",
    detail: "No refs are actually updated — useful to preview --prune/--all before committing to it.",
    order: 80,
  },
  {
    id: "jobs",
    short: "-j",
    preferShort: true,
    long: "--jobs",
    group: "options",
    kind: "number",
    arg: { placeholder: "4", min: 1, separator: "=" },
    summary: "Number of submodules fetched in parallel.",
    detail: "Only matters when this repository has submodules to recurse into.",
    order: 90,
  },
  {
    id: "recurseSubmodules",
    long: "--recurse-submodules",
    group: "options",
    kind: "text",
    arg: { placeholder: "on-demand" },
    summary: "Control whether submodules are fetched too.",
    detail: 'Typical values are "yes", "on-demand" (only submodules whose superproject commit changed), or "no".',
    order: 100,
  },
] as const;
export const FETCH_CATALOGUE = createFlagCatalogue<FlagGroup>(FETCH_FLAGS);

// ── pull ────────────────────────────────────────────────────────────────────

export const PULL_FLAGS: readonly RemoteFlagDef[] = [
  {
    id: "rebase",
    long: "--rebase",
    group: "options",
    kind: "text",
    danger: "caution",
    conflictsWith: ["ffOnly"],
    arg: { placeholder: "true" },
    summary: "Rebase local commits onto the fetched branch instead of merging.",
    detail:
      'Leave blank and toggle the bare form for plain `--rebase`, or set an explicit value: "true", "false", "merges", or "interactive". Rewrites local commits the same way a plain rebase does.',
    order: 10,
  },
  {
    id: "ffOnly",
    long: "--ff-only",
    group: "options",
    kind: "boolean",
    conflictsWith: ["rebase", "noFf"],
    summary: "Refuse to pull unless it can fast-forward.",
    detail: "The genuinely safer default — never creates a merge commit or rewrites anything local.",
    order: 20,
  },
  {
    id: "noFf",
    long: "--no-ff",
    group: "options",
    kind: "boolean",
    conflictsWith: ["ffOnly"],
    summary: "Always create a merge commit, even when a fast-forward is possible.",
    detail: "Preserves the fact that a branch existed, at the cost of an extra merge commit.",
    order: 30,
  },
  {
    id: "prune",
    short: "-p",
    preferShort: true,
    long: "--prune",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Remove local remote-tracking refs that no longer exist on the remote.",
    detail: "Deletes local tracking refs, e.g. origin/some-deleted-branch, not just skips fetching them.",
    order: 40,
  },
  {
    id: "depth",
    long: "--depth",
    group: "options",
    kind: "number",
    arg: { placeholder: "1", min: 1, separator: "=" },
    summary: "Deepen or shorten the history fetched from this remote.",
    detail: "Turns (or keeps) the local repository into a shallow clone from this remote's perspective.",
    order: 50,
  },
  {
    id: "force",
    short: "-f",
    preferShort: true,
    long: "--force",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Allow non-fast-forward updates to local remote-tracking refs.",
    detail: "Without this, the underlying fetch refuses to move a tracking ref anywhere but forward.",
    order: 60,
  },
  {
    id: "autostash",
    long: "--autostash",
    group: "options",
    kind: "boolean",
    summary: "Stash local changes before pulling, then reapply them afterward.",
    detail: "Safety-improving, not risky — lets a pull proceed instead of refusing on dirty local changes.",
    order: 70,
  },
  {
    id: "strategy",
    short: "-s",
    long: "--strategy",
    group: "options",
    kind: "text",
    arg: { placeholder: "recursive" },
    summary: "Merge strategy to use when a merge is needed.",
    detail: 'E.g. "recursive", "ort", "octopus". Only relevant when the pull actually performs a merge.',
    order: 80,
  },
  {
    id: "noVerify",
    long: "--no-verify",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Skip the pre-merge/pre-rebase hooks.",
    detail: "Bypasses whatever local safety checks those hooks perform.",
    order: 90,
  },
] as const;
export const PULL_CATALOGUE = createFlagCatalogue<FlagGroup>(PULL_FLAGS);

// ── push ────────────────────────────────────────────────────────────────────

export const PUSH_FLAGS: readonly RemoteFlagDef[] = [
  {
    id: "force",
    short: "-f",
    preferShort: true,
    long: "--force",
    group: "options",
    kind: "boolean",
    danger: "destructive",
    conflictsWith: ["forceWithLease"],
    summary: "Overwrite the remote ref even if it isn't a fast-forward.",
    detail: "Can permanently discard commits someone else already pushed. --force-with-lease is the safer alternative.",
    order: 10,
  },
  {
    id: "forceWithLease",
    long: "--force-with-lease",
    group: "options",
    kind: "text",
    danger: "caution",
    conflictsWith: ["force"],
    arg: { placeholder: "refname:expect" },
    summary: "Overwrite the remote ref, but only if it still matches what you last saw.",
    detail:
      "The recommended safer swap for --force — refuses if the remote ref moved since your last fetch. Leave blank to use the bare form; still capable of overwriting if you've already fetched the clobbering change.",
    order: 20,
  },
  {
    id: "forceIfIncludes",
    long: "--force-if-includes",
    group: "options",
    kind: "boolean",
    requires: ["forceWithLease"],
    summary: "Additionally verify the remote's current tip is reachable from what you fetched.",
    detail: "Tightens --force-with-lease's check using the reflog of the remote-tracking ref.",
    order: 30,
  },
  {
    id: "setUpstream",
    short: "-u",
    preferShort: true,
    long: "--set-upstream",
    group: "options",
    kind: "boolean",
    summary: "Set the pushed branch's upstream tracking reference.",
    detail: "Makes future bare `git pull`/`git push` on this branch default to this remote and branch.",
    order: 40,
  },
  {
    id: "delete",
    short: "-d",
    preferShort: true,
    long: "--delete",
    group: "options",
    kind: "boolean",
    danger: "destructive",
    conflictsWith: ["mirror"],
    summary: "Delete the named ref(s) from the remote entirely.",
    detail: "Removes the remote ref outright — not a local operation, and not reversible from here.",
    order: 50,
  },
  {
    id: "tags",
    long: "--tags",
    group: "options",
    kind: "boolean",
    conflictsWith: ["mirror"],
    summary: "Push all local tags as well.",
    detail: "Equivalent to also listing every tag as a refspec.",
    order: 60,
  },
  {
    id: "all",
    long: "--all",
    group: "options",
    kind: "boolean",
    danger: "caution",
    conflictsWith: ["mirror"],
    summary: "Push every local branch.",
    detail: "Easy to accidentally publish a local-only or work-in-progress branch you didn't mean to share.",
    order: 70,
  },
  {
    id: "mirror",
    long: "--mirror",
    group: "options",
    kind: "boolean",
    danger: "destructive",
    conflictsWith: ["all", "tags", "delete"],
    summary: "Make the remote's refs exactly match this repository's, deleting anything else on the remote.",
    detail:
      "The single most dangerous flag here — deletes every remote ref (branch, tag, or otherwise) that doesn't also exist locally.",
    order: 80,
  },
  {
    id: "dryRun",
    short: "-n",
    preferShort: true,
    long: "--dry-run",
    group: "options",
    kind: "boolean",
    summary: "Show what would be pushed without actually pushing anything.",
    detail: "No refs are actually updated on the remote — useful to preview before committing to it.",
    order: 90,
  },
  {
    id: "atomic",
    long: "--atomic",
    group: "options",
    kind: "boolean",
    summary: "Update all refs together, or none at all.",
    detail: "If any ref update would be rejected, the whole push is aborted instead of partially applying.",
    order: 100,
  },
  {
    id: "noVerify",
    long: "--no-verify",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Skip the pre-push hook.",
    detail: "Bypasses whatever local safety checks that hook performs.",
    order: 110,
  },
  {
    id: "pushOption",
    short: "-o",
    long: "--push-option",
    group: "options",
    kind: "text",
    arg: { placeholder: "ci.skip" },
    summary: "Pass a string through to the server-side pre-receive/post-receive hooks.",
    detail: "Only meaningful when the remote's hooks are written to look for it.",
    order: 120,
  },
] as const;
export const PUSH_CATALOGUE = createFlagCatalogue<FlagGroup>(PUSH_FLAGS);
