import { createFlagCatalogue, type FlagDef as FlagDefGeneric } from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type StagingFlagDef = FlagDefGeneric<FlagGroup>;

export const ADD_FLAGS: readonly StagingFlagDef[] = [
  {
    id: "all",
    short: "-A",
    preferShort: true,
    long: "--all",
    group: "options",
    kind: "boolean",
    conflictsWith: ["update"],
    summary: "Stage every change, including deletions, across the whole worktree.",
    detail: "Matches what a user actually intends, including files git has never tracked before.",
    order: 10,
  },
  {
    id: "update",
    short: "-u",
    preferShort: true,
    long: "--update",
    group: "options",
    kind: "boolean",
    conflictsWith: ["all"],
    summary: "Stage changes only to files git already tracks.",
    detail: "Never stages a brand-new, previously untracked file.",
    order: 20,
  },
  {
    id: "force",
    short: "-f",
    preferShort: true,
    long: "--force",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Allow adding files that .gitignore would otherwise exclude.",
    detail: "Can accidentally stage secrets, build output, or other files deliberately ignored.",
    order: 30,
  },
  {
    id: "patch",
    short: "-p",
    preferShort: true,
    long: "--patch",
    group: "options",
    kind: "boolean",
    summary: "Interactively choose hunks to stage.",
    detail: "Opens an interactive prompt — doesn't suit a populate-and-paste workflow, but is a real, common flag.",
    order: 40,
  },
  {
    id: "dryRun",
    short: "-n",
    preferShort: true,
    long: "--dry-run",
    group: "options",
    kind: "boolean",
    summary: "Show what would be added without actually staging anything.",
    detail: "No files are actually staged — useful to preview -A/-u before committing to it.",
    order: 50,
  },
  {
    id: "intentToAdd",
    short: "-N",
    preferShort: true,
    long: "--intent-to-add",
    group: "options",
    kind: "boolean",
    summary: "Record that a new file will be added later, without staging its content yet.",
    detail: "Makes the file show up in diffs against the index without actually staging its contents.",
    order: 60,
  },
] as const;
export const ADD_CATALOGUE = createFlagCatalogue<FlagGroup>(ADD_FLAGS);

export const COMMIT_FLAGS: readonly StagingFlagDef[] = [
  {
    id: "all",
    short: "-a",
    preferShort: true,
    long: "--all",
    group: "options",
    kind: "boolean",
    summary: "Automatically stage every tracked file's modifications and deletions first.",
    detail: "Real git rejects this combined with an explicit list of paths — flagged by lint, not silently dropped.",
    order: 10,
  },
  {
    id: "amend",
    long: "--amend",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Replace the previous commit instead of creating a new one.",
    detail: "Rewrites history — risky once that commit has already been pushed/shared.",
    order: 20,
  },
  {
    id: "noEdit",
    long: "--no-edit",
    group: "options",
    kind: "boolean",
    requires: ["amend"],
    summary: "Amend without changing the commit message.",
    detail: "Only meaningful together with --amend — reuses the previous commit's message as-is.",
    order: 30,
  },
  {
    id: "signoff",
    short: "-s",
    preferShort: true,
    long: "--signoff",
    group: "options",
    kind: "boolean",
    summary: "Add a Signed-off-by trailer to the commit message.",
    detail: "Common in projects (e.g. the Linux kernel) that require contributor sign-off.",
    order: 40,
  },
  {
    id: "noVerify",
    long: "--no-verify",
    group: "options",
    kind: "boolean",
    danger: "caution",
    summary: "Skip the pre-commit and commit-msg hooks.",
    detail: "Bypasses whatever local safety checks those hooks perform.",
    order: 50,
  },
  {
    id: "allowEmpty",
    long: "--allow-empty",
    group: "options",
    kind: "boolean",
    summary: "Allow committing with no staged changes at all.",
    detail: "Normally git refuses to create a commit that changes nothing.",
    order: 60,
  },
  {
    id: "author",
    long: "--author",
    group: "options",
    kind: "text",
    arg: { placeholder: "Name <email@example.com>" },
    summary: "Override the commit's author.",
    detail: "Useful when committing on someone else's behalf.",
    order: 70,
  },
  {
    id: "date",
    long: "--date",
    group: "options",
    kind: "text",
    arg: { placeholder: "2024-01-01T12:00:00" },
    summary: "Override the commit's author date.",
    detail: "Only the author date — the committer date is still set to now unless GIT_COMMITTER_DATE is also set.",
    order: 80,
  },
  {
    id: "verbose",
    short: "-v",
    preferShort: true,
    long: "--verbose",
    group: "options",
    kind: "boolean",
    summary: "Show the diff being committed in the editor/output.",
    detail: "Purely informational — appended below the commit message template, stripped before saving.",
    order: 90,
  },
] as const;
export const COMMIT_CATALOGUE = createFlagCatalogue<FlagGroup>(COMMIT_FLAGS);

export const RM_FLAGS: readonly StagingFlagDef[] = [
  {
    id: "cached",
    long: "--cached",
    group: "options",
    kind: "boolean",
    summary: "Untrack these paths but keep the actual files on disk.",
    detail: "The safe variant — without it, git rm deletes the real file too, not just the index entry.",
    order: 10,
  },
  {
    id: "force",
    short: "-f",
    preferShort: true,
    long: "--force",
    group: "options",
    kind: "boolean",
    danger: "destructive",
    summary: "Remove even if the file differs from HEAD or the index.",
    detail: "Overrides git's own safety check that normally refuses to discard changes this way.",
    order: 20,
  },
  {
    id: "recursive",
    short: "-r",
    long: "-r",
    group: "options",
    kind: "boolean",
    preferShort: true,
    summary: "Allow recursively removing a directory.",
    detail: "Without it, git rm refuses to remove a directory outright.",
    order: 30,
  },
  {
    id: "dryRun",
    short: "-n",
    preferShort: true,
    long: "--dry-run",
    group: "options",
    kind: "boolean",
    summary: "Show what would be removed without actually doing it.",
    detail: "No files are actually removed — useful to check the pathspec before committing to it.",
    order: 40,
  },
  {
    id: "ignoreUnmatch",
    long: "--ignore-unmatch",
    group: "options",
    kind: "boolean",
    summary: "Exit successfully even if no path matched.",
    detail: "Useful in scripts where a missing path shouldn't be a failure.",
    order: 50,
  },
  {
    id: "quiet",
    short: "-q",
    preferShort: true,
    long: "--quiet",
    group: "options",
    kind: "boolean",
    summary: "Don't list each removed file.",
    detail: "Suppresses the per-file removal output.",
    order: 60,
  },
] as const;
export const RM_CATALOGUE = createFlagCatalogue<FlagGroup>(RM_FLAGS);

export const MV_FLAGS: readonly StagingFlagDef[] = [
  {
    id: "force",
    short: "-f",
    preferShort: true,
    long: "--force",
    group: "options",
    kind: "boolean",
    danger: "destructive",
    summary: "Overwrite an existing tracked destination file.",
    detail: "Without this, git mv refuses to silently clobber a tracked file that's already at the destination.",
    order: 10,
  },
  {
    id: "skip",
    short: "-k",
    long: "-k",
    group: "options",
    kind: "boolean",
    preferShort: true,
    summary: "Skip house-keeping — don't move files that don't exist or can't be moved.",
    detail: "Errors that would normally stop the whole operation are skipped instead.",
    order: 20,
  },
  {
    id: "dryRun",
    short: "-n",
    preferShort: true,
    long: "--dry-run",
    group: "options",
    kind: "boolean",
    summary: "Show what would be renamed without actually doing it.",
    detail: "No files are actually renamed — useful to preview the operation first.",
    order: 30,
  },
  {
    id: "verbose",
    short: "-v",
    preferShort: true,
    long: "--verbose",
    group: "options",
    kind: "boolean",
    summary: "List each rename as it happens.",
    detail: "Prints one line per file as it's renamed.",
    order: 40,
  },
] as const;
export const MV_CATALOGUE = createFlagCatalogue<FlagGroup>(MV_FLAGS);

export const RESTORE_FLAGS: readonly StagingFlagDef[] = [
  {
    id: "patch",
    short: "-p",
    preferShort: true,
    long: "--patch",
    group: "options",
    kind: "boolean",
    summary: "Interactively choose hunks to restore.",
    detail: "Opens an interactive prompt — doesn't suit a populate-and-paste workflow, but is a real, common flag.",
    order: 10,
  },
  {
    id: "quiet",
    short: "-q",
    preferShort: true,
    long: "--quiet",
    group: "options",
    kind: "boolean",
    summary: "Suppress feedback messages.",
    detail: "Restore normally prints nothing on success anyway; this suppresses warnings too.",
    order: 20,
  },
  {
    id: "ignoreUnmerged",
    long: "--ignore-unmerged",
    group: "options",
    kind: "boolean",
    summary: "Continue even if some paths are unmerged.",
    detail: "Without this, restoring an unmerged path is refused.",
    order: 30,
  },
  {
    id: "overlay",
    long: "--overlay",
    group: "options",
    kind: "boolean",
    conflictsWith: ["noOverlay"],
    summary: "Don't remove files present in the source but absent from the target tree.",
    detail: "Only meaningful when both Staged and Worktree are checked.",
    order: 40,
  },
  {
    id: "noOverlay",
    long: "--no-overlay",
    group: "options",
    kind: "boolean",
    conflictsWith: ["overlay"],
    summary: "Remove files present in the source but absent from the target tree (the default).",
    detail: "Only meaningful when both Staged and Worktree are checked.",
    order: 50,
  },
] as const;
export const RESTORE_CATALOGUE = createFlagCatalogue<FlagGroup>(RESTORE_FLAGS);
