import {
  createFlagCatalogue,
  flagLabel as flagLabelGeneric,
  validateCatalogue as validateCatalogueGeneric,
  type DangerLevel,
  type FlagArgSpec,
  type FlagDef as FlagDefGeneric,
  type FlagEnumOption,
  type FlagKind,
} from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type { DangerLevel, FlagArgSpec, FlagEnumOption, FlagKind };
export type FlagDef = FlagDefGeneric<FlagGroup>;

/**
 * Every option in curl's own `--help all`, minus five deliberate exclusions:
 *
 * - `-h/--help`, `-V/--version`, `-M/--manual` — doc-viewer flags, excluded
 *   the same way every other command in this app excludes its own help/
 *   version output.
 * - `--url` — not a separate flag; a bare positional URL and `--url <u>` are
 *   the same thing in real curl, and `spec.urls` already models it.
 * - `-H/--header`, `-d/--data*`/`--json`, `-F/--form`/`--form-string` — all
 *   genuinely repeatable (multiple `-H`, multiple `-d` concatenated with
 *   `&`, multiple `-F` for multiple form parts). The flag catalogue has no
 *   repeated-flag concept — same reason tar's `excludes` is a spec field,
 *   not a flag — so these live as `spec.headers`/`spec.dataEntries`/
 *   `spec.formEntries` instead; see `../spec.ts`.
 *
 * A handful of other real curl flags ARE also repeatable (`--resolve`,
 * `--connect-to`, `--proxy-header`, `-Q/--quote`, `-t/--telnet-option`,
 * `--mail-rcpt`) but are modeled here as ordinary single-value flags rather
 * than adding six more array fields — supporting one occurrence covers the
 * overwhelming majority of real usage. Each says so in its own `detail`.
 */
export const FLAGS: readonly FlagDef[] = [
  // ══ global — curl-level behavior, not tied to a protocol ══════════════════
  {
    id: "config",
    short: "-K",
    long: "--config",
    group: "global",
    kind: "path",
    preferShort: true,
    arg: { placeholder: "curlrc", separator: " " },
    summary: "Read curl arguments from a config file.",
    detail: "One argument per line (or space-separated). Useful for credentials you do not want on the command line or in shell history.",
    order: 0,
  },
  {
    id: "disable",
    short: "-q",
    long: "--disable",
    group: "global",
    kind: "boolean",
    preferShort: true,
    summary: "Do not read a default curlrc config file.",
    detail: "Only has an effect as the very first option on the line — curl already read curlrc by the time it processes options after that.",
    order: 10,
  },
  {
    id: "fail",
    short: "-f",
    long: "--fail",
    group: "global",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["failWithBody"],
    summary: "Exit with an error on an HTTP response ≥ 400.",
    detail: "Without this, curl considers a 404 or 500 page a successful transfer and exits 0 — this is almost always what scripts actually want.",
    order: 20,
  },
  {
    id: "failEarly",
    long: "--fail-early",
    group: "global",
    kind: "boolean",
    requires: ["parallel"],
    summary: "Stop the whole batch on the first failed transfer.",
    detail: "Only meaningful with multiple URLs or --parallel; otherwise a single transfer already stops on its own failure.",
    order: 30,
  },
  {
    id: "failWithBody",
    long: "--fail-with-body",
    group: "global",
    kind: "boolean",
    conflictsWith: ["fail"],
    summary: "Fail on HTTP errors ≥ 400, but still write the response body.",
    detail: "Plain --fail discards the error page; this keeps it (e.g. to inspect an API's JSON error detail) while still exiting non-zero.",
    order: 40,
  },
  {
    id: "globoff",
    short: "-g",
    long: "--globoff",
    group: "global",
    kind: "boolean",
    preferShort: true,
    summary: "Disable URL globbing with {} and [].",
    detail: "Without this, curl expands http://x.com/{a,b}.txt and [1-9].txt itself. Needed when a URL genuinely contains a literal brace or bracket.",
    order: 50,
  },
  {
    id: "next",
    short: "-:",
    long: "--next",
    group: "global",
    kind: "boolean",
    summary: "Start a new, separate request for the next URL.",
    detail:
      "Real curl lets every option before --next apply only to the URLs before it, so one command line can run several genuinely different requests. This app models one flags record per command like every other tool here, so enabling this renders a single --next token — it does not give the URLs after it their own independent flags.",
    order: 60,
  },
  {
    id: "parallel",
    short: "-Z",
    long: "--parallel",
    group: "global",
    kind: "boolean",
    preferShort: true,
    summary: "Fetch multiple URLs in parallel instead of one at a time.",
    detail: "Only useful with more than one URL listed.",
    order: 70,
  },
  {
    id: "parallelImmediate",
    long: "--parallel-immediate",
    group: "global",
    kind: "boolean",
    requires: ["parallel"],
    summary: "Start every parallel transfer immediately instead of waiting to reuse connections.",
    detail: "Trades connection reuse for lower latency per transfer.",
    order: 80,
  },
  {
    id: "parallelMax",
    long: "--parallel-max",
    group: "global",
    kind: "number",
    requires: ["parallel"],
    arg: { placeholder: "50", min: 1, separator: " " },
    summary: "Maximum number of parallel transfers at once.",
    detail: "Default is 50.",
    order: 90,
  },
  {
    id: "parallelMaxHost",
    long: "--parallel-max-host",
    group: "global",
    kind: "number",
    requires: ["parallel"],
    arg: { placeholder: "6", min: 1, separator: " " },
    summary: "Maximum parallel transfers to a single host.",
    detail: "Caps concurrency per host separately from the overall --parallel-max.",
    order: 100,
  },
  {
    id: "proto",
    long: "--proto",
    group: "global",
    kind: "text",
    arg: { placeholder: "=http,https", separator: " " },
    summary: "Restrict which protocols this transfer may use.",
    detail: "Prefix with = to set exactly this list, + to add, - to remove, e.g. --proto -all,https to allow only https.",
    order: 110,
  },
  {
    id: "protoDefault",
    long: "--proto-default",
    group: "global",
    kind: "text",
    arg: { placeholder: "https", separator: " " },
    summary: "Protocol to assume for a URL with no scheme.",
    detail: "Applies when a URL is given without http:// or https:// in front.",
    order: 120,
  },
  {
    id: "protoRedir",
    long: "--proto-redir",
    group: "global",
    kind: "text",
    requires: ["location"],
    arg: { placeholder: "-all,https", separator: " " },
    summary: "Restrict which protocols a redirect may follow to.",
    detail: "Same syntax as --proto. Without this, a redirect can silently switch protocol, including away from https.",
    order: 130,
  },
  {
    id: "variable",
    long: "--variable",
    group: "global",
    kind: "text",
    arg: { placeholder: "name=value", separator: " " },
    summary: "Set a variable for later --config expansion.",
    detail: "Mostly useful inside a curl config file (-K) that references %{name} elsewhere on the line.",
    order: 140,
  },
  {
    id: "libcurl",
    long: "--libcurl",
    group: "global",
    kind: "path",
    arg: { placeholder: "code.c", separator: " " },
    summary: "Write the equivalent libcurl C source for this command to a file.",
    detail: "A debugging/learning aid — has no effect on the actual transfer.",
    order: 150,
  },
  {
    id: "metalink",
    long: "--metalink",
    group: "global",
    kind: "boolean",
    summary: "Interpret the downloaded file as a Metalink and fetch from it.",
    detail: "curl removed Metalink support some years ago for security reasons — modern curl accepts this flag but it is a no-op.",
    order: 160,
  },
  {
    id: "ipfsGateway",
    long: "--ipfs-gateway",
    group: "global",
    kind: "text",
    arg: { placeholder: "http://127.0.0.1:8080", separator: " " },
    summary: "Gateway to use for ipfs:// and ipns:// URLs.",
    detail: "Overrides the IPFS_GATEWAY environment variable.",
    order: 170,
  },
  {
    id: "requestTarget",
    long: "--request-target",
    group: "global",
    kind: "text",
    arg: { placeholder: "*", separator: " " },
    summary: "Send this exact string as the HTTP request-target instead of the URL's path.",
    detail: "Needed for unusual request lines such as OPTIONS *.",
    order: 180,
  },
  {
    id: "pathAsIs",
    long: "--path-as-is",
    group: "global",
    kind: "boolean",
    summary: "Do not squash ../ and ./ sequences in the URL path.",
    detail: "curl normally resolves these before sending the request; some servers behave differently when they see the literal sequence.",
    order: 190,
  },
  {
    id: "raw",
    long: "--raw",
    group: "global",
    kind: "boolean",
    summary: "Disable all internal HTTP decoding of content or transfer encodings.",
    detail: "Delivers the response exactly as the server sent it on the wire.",
    order: 200,
  },
  {
    id: "urlQuery",
    long: "--url-query",
    group: "global",
    kind: "text",
    arg: { placeholder: "key=value", separator: " " },
    summary: "Append this as a URL query component.",
    detail: "Added and percent-encoded the same way curl encodes the URL itself, unlike hand-appending ?key=value.",
    order: 210,
  },

  // ══ auth ═══════════════════════════════════════════════════════════════════
  {
    id: "user",
    short: "-u",
    long: "--user",
    group: "auth",
    kind: "text",
    preferShort: true,
    danger: "caution",
    arg: { placeholder: "user:password", separator: " " },
    summary: "Credentials for server authentication.",
    detail: "Visible in shell history and to anyone who can list processes on this machine. Prefer --netrc or a config file (-K) for anything real.",
    order: 1000,
  },
  {
    id: "basic",
    long: "--basic",
    group: "auth",
    kind: "boolean",
    conflictsWith: ["digest", "ntlm", "negotiate", "anyauth"],
    summary: "Force HTTP Basic authentication.",
    detail: "Sends credentials base64-encoded, not encrypted — only meaningfully safe over TLS.",
    order: 1010,
  },
  {
    id: "digest",
    long: "--digest",
    group: "auth",
    kind: "boolean",
    conflictsWith: ["basic", "ntlm", "negotiate", "anyauth"],
    summary: "Force HTTP Digest authentication.",
    detail: "Does not send the password in the clear, unlike Basic.",
    order: 1020,
  },
  {
    id: "ntlm",
    long: "--ntlm",
    group: "auth",
    kind: "boolean",
    conflictsWith: ["basic", "digest", "negotiate", "anyauth"],
    summary: "Force HTTP NTLM authentication.",
    detail: "Common against IIS/Windows-hosted services.",
    order: 1030,
  },
  {
    id: "negotiate",
    long: "--negotiate",
    group: "auth",
    kind: "boolean",
    conflictsWith: ["basic", "digest", "ntlm", "anyauth"],
    summary: "Force HTTP Negotiate (SPNEGO/Kerberos) authentication.",
    detail: "Needs a valid Kerberos ticket already in your credential cache.",
    order: 1040,
  },
  {
    id: "anyauth",
    long: "--anyauth",
    group: "auth",
    kind: "boolean",
    conflictsWith: ["basic", "digest", "ntlm", "negotiate"],
    summary: "Let curl pick an authentication method automatically.",
    detail: "curl probes the server and picks the most secure method it offers. The safe default when you are not sure which the server wants.",
    order: 1050,
  },
  {
    id: "netrc",
    short: "-n",
    long: "--netrc",
    group: "auth",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["netrcOptional"],
    summary: "Read credentials from ~/.netrc, and fail if the host is not listed there.",
    detail: "Keeps credentials out of the command line entirely.",
    order: 1060,
  },
  {
    id: "netrcOptional",
    long: "--netrc-optional",
    group: "auth",
    kind: "boolean",
    conflictsWith: ["netrc"],
    summary: "Read credentials from ~/.netrc if present, but do not require it.",
    detail: "Like --netrc but falls back to the URL or --user instead of failing when the host is not listed.",
    order: 1070,
  },
  {
    id: "netrcFile",
    long: "--netrc-file",
    group: "auth",
    kind: "path",
    requires: ["netrc"],
    arg: { placeholder: "~/.my-netrc", separator: " " },
    summary: "Use this file instead of ~/.netrc.",
    detail: "Applies with either --netrc or --netrc-optional.",
    order: 1080,
  },
  {
    id: "oauth2Bearer",
    long: "--oauth2-bearer",
    group: "auth",
    kind: "text",
    danger: "caution",
    arg: { placeholder: "eyJhbGciOi...", separator: " " },
    summary: "Send this OAuth 2.0 Bearer token.",
    detail: "Sent as an Authorization: Bearer header. Visible in shell history the same as --user.",
    order: 1090,
  },
  {
    id: "awsSigv4",
    long: "--aws-sigv4",
    group: "auth",
    kind: "text",
    arg: { placeholder: "aws:amz:us-east-1:s3", separator: " " },
    summary: "Sign the request with AWS Signature Version 4.",
    detail: "Needs --user to supply the access key and secret. provider1:provider2:region:service, e.g. aws:amz:eu-west-1:s3.",
    order: 1100,
  },
  {
    id: "delegation",
    long: "--delegation",
    group: "auth",
    kind: "enum",
    options: [
      { value: "none", label: "curl default (no delegation)", renders: "" },
      { value: "policy", label: "policy — delegate per KDC policy", renders: "--delegation policy" },
      { value: "always", label: "always — always delegate", renders: "--delegation always" },
    ],
    summary: "GSS-API credential delegation level.",
    detail: "Only relevant with Negotiate/Kerberos authentication.",
    order: 1110,
  },
  {
    id: "serviceName",
    long: "--service-name",
    group: "auth",
    kind: "text",
    arg: { placeholder: "http", separator: " " },
    summary: "SPNEGO service name to use instead of the default.",
    detail: "Rarely needed outside nonstandard Kerberos service principal setups.",
    order: 1120,
  },
  {
    id: "saslAuthzid",
    long: "--sasl-authzid",
    group: "auth",
    kind: "text",
    arg: { placeholder: "admin", separator: " " },
    summary: "Identity to act as, for SASL PLAIN authentication.",
    detail: "Used by the mail protocols when authenticating as one user but acting on behalf of another.",
    order: 1130,
  },
  {
    id: "saslIr",
    long: "--sasl-ir",
    group: "auth",
    kind: "boolean",
    summary: "Send the SASL initial response in the first request, saving a round trip.",
    detail: "Only meaningful for the mail protocols.",
    order: 1140,
  },
  {
    id: "ntlmWb",
    long: "--ntlm-wb",
    group: "deprecated",
    kind: "boolean",
    summary: "NTLM via a winbind ntlm_auth helper process.",
    detail: "Removed from modern curl builds; accepted here for scripts that still pass it, but it will not do anything.",
    order: 17000,
  },
  {
    id: "krb",
    long: "--krb",
    group: "deprecated",
    kind: "text",
    arg: { placeholder: "private", separator: " " },
    summary: "Kerberos security level for FTP.",
    detail: "clear, safe, confidential or private. FTP-only, and FTP's Kerberos support is legacy at this point.",
    order: 17010,
  },

  // ══ connection ═════════════════════════════════════════════════════════════
  {
    id: "interface",
    long: "--interface",
    group: "connection",
    kind: "text",
    arg: { placeholder: "eth0", separator: " " },
    summary: "Bind to this network interface, or local IP/hostname.",
    detail: "Picks which local NIC or address the connection originates from, when the machine has more than one.",
    order: 2000,
  },
  {
    id: "localPort",
    long: "--local-port",
    group: "connection",
    kind: "text",
    arg: { placeholder: "1024-2048", separator: " " },
    summary: "Use a local source port within this range.",
    detail: "Useful when a firewall rule needs a predictable outbound port range.",
    order: 2010,
  },
  {
    id: "ipv4",
    short: "-4",
    long: "--ipv4",
    group: "connection",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["ipv6"],
    summary: "Resolve names to IPv4 addresses only.",
    detail: "Forces the connection over IPv4 even when the host also has an IPv6 address.",
    order: 2020,
  },
  {
    id: "ipv6",
    short: "-6",
    long: "--ipv6",
    group: "connection",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["ipv4"],
    summary: "Resolve names to IPv6 addresses only.",
    detail: "Forces the connection over IPv6.",
    order: 2030,
  },
  {
    id: "happyEyeballsTimeoutMs",
    long: "--happy-eyeballs-timeout-ms",
    group: "connection",
    kind: "number",
    arg: { placeholder: "200", min: 0, unit: "ms", separator: " " },
    summary: "How long to wait for a working IPv6 connection before also trying IPv4.",
    detail: "Default is 200ms. Lowering it fails over to IPv4 sooner on networks with broken IPv6.",
    order: 2040,
  },
  {
    id: "connectTo",
    long: "--connect-to",
    group: "connection",
    kind: "text",
    arg: { placeholder: "example.com:443:127.0.0.1:8443", separator: " " },
    summary: "Connect to a different host/port than the URL says, without changing what curl sends.",
    detail:
      "Unlike --resolve, the Host header and TLS SNI still use the URL's original host. Real curl allows this repeated for several mappings; only one is modeled here.",
    order: 2050,
  },
  {
    id: "unixSocket",
    long: "--unix-socket",
    group: "connection",
    kind: "path",
    arg: { placeholder: "/var/run/docker.sock", separator: " " },
    summary: "Connect through this Unix domain socket instead of TCP.",
    detail: "The classic way to talk to the Docker Engine API.",
    order: 2060,
  },
  {
    id: "abstractUnixSocket",
    long: "--abstract-unix-socket",
    group: "connection",
    kind: "path",
    arg: { placeholder: "/socket", separator: " " },
    summary: "Connect through this abstract Unix domain socket (Linux only).",
    detail: "An abstract socket has no filesystem path — this is the namespace address instead.",
    order: 2070,
  },
  {
    id: "noKeepalive",
    long: "--no-keepalive",
    group: "connection",
    kind: "boolean",
    summary: "Disable TCP keepalive on the connection.",
    detail: "curl sends TCP keepalive probes by default; this turns that off.",
    order: 2080,
  },
  {
    id: "keepaliveTime",
    long: "--keepalive-time",
    group: "connection",
    kind: "number",
    conflictsWith: ["noKeepalive"],
    arg: { placeholder: "60", min: 1, unit: "s", separator: " " },
    summary: "Seconds of idle time before a keepalive probe is sent.",
    detail: "Default is 60 seconds.",
    order: 2090,
  },
  {
    id: "keepaliveCnt",
    long: "--keepalive-cnt",
    group: "connection",
    kind: "number",
    conflictsWith: ["noKeepalive"],
    arg: { placeholder: "9", min: 1, separator: " " },
    summary: "Maximum number of missed keepalive probes before giving up.",
    detail: "Not supported on every platform's TCP stack.",
    order: 2100,
  },
  {
    id: "tcpNodelay",
    long: "--tcp-nodelay",
    group: "connection",
    kind: "boolean",
    summary: "Disable Nagle's algorithm on the connection.",
    detail: "Reduces latency for small, frequent writes at the cost of more, smaller packets on the wire.",
    order: 2110,
  },
  {
    id: "tcpFastopen",
    long: "--tcp-fastopen",
    group: "connection",
    kind: "boolean",
    summary: "Use TCP Fast Open where the platform supports it.",
    detail: "Sends data in the TCP handshake itself, saving a round trip on repeat connections to the same server.",
    order: 2120,
  },
  {
    id: "mptcp",
    long: "--mptcp",
    group: "connection",
    kind: "boolean",
    summary: "Enable Multipath TCP where the platform supports it.",
    detail: "Lets the connection use more than one network path at once.",
    order: 2130,
  },
  {
    id: "ipTos",
    long: "--ip-tos",
    group: "connection",
    kind: "text",
    arg: { placeholder: "throughput", separator: " " },
    summary: "Set the IP Type-of-Service / Traffic Class on outgoing packets.",
    detail: "Accepts a numeric value or a symbolic name like lowdelay or throughput.",
    order: 2140,
  },
  {
    id: "vlanPriority",
    long: "--vlan-priority",
    group: "connection",
    kind: "number",
    arg: { placeholder: "3", min: 0, max: 7, separator: " " },
    summary: "802.1p VLAN priority for outgoing packets.",
    detail: "Only effective where the platform and network stack support tagging it.",
    order: 2150,
  },
  {
    id: "haproxyClientip",
    long: "--haproxy-clientip",
    group: "connection",
    kind: "text",
    arg: { placeholder: "10.0.0.1", separator: " " },
    summary: "Client IP to report in an HAProxy PROXY protocol header.",
    detail: "Used together with --haproxy-protocol to spoof the reported originating address.",
    order: 2160,
  },
  {
    id: "haproxyProtocol",
    long: "--haproxy-protocol",
    group: "connection",
    kind: "boolean",
    summary: "Send an HAProxy PROXY protocol v1 header before the real request.",
    detail: "Lets curl speak directly to a service that expects to sit behind a proxy that adds this header.",
    order: 2170,
  },

  // ══ dns ════════════════════════════════════════════════════════════════════
  {
    id: "resolve",
    long: "--resolve",
    group: "dns",
    kind: "text",
    arg: { placeholder: "example.com:443:127.0.0.1", separator: " " },
    summary: "Provide a custom host-to-IP mapping, bypassing normal DNS.",
    detail: "The usual way to hit a specific server for a domain before DNS is updated. Real curl allows this repeated for several mappings; only one is modeled here.",
    order: 3000,
  },
  {
    id: "dnsInterface",
    long: "--dns-interface",
    group: "dns",
    kind: "text",
    arg: { placeholder: "eth0", separator: " " },
    summary: "Send DNS requests from this network interface.",
    detail: "Only relevant when curl is built against c-ares.",
    order: 3010,
  },
  {
    id: "dnsIpv4Addr",
    long: "--dns-ipv4-addr",
    group: "dns",
    kind: "text",
    arg: { placeholder: "10.0.0.1", separator: " " },
    summary: "Source IPv4 address to send DNS requests from.",
    detail: "Only relevant when curl is built against c-ares.",
    order: 3020,
  },
  {
    id: "dnsIpv6Addr",
    long: "--dns-ipv6-addr",
    group: "dns",
    kind: "text",
    arg: { placeholder: "::1", separator: " " },
    summary: "Source IPv6 address to send DNS requests from.",
    detail: "Only relevant when curl is built against c-ares.",
    order: 3030,
  },
  {
    id: "dnsServers",
    long: "--dns-servers",
    group: "dns",
    kind: "text",
    arg: { placeholder: "1.1.1.1,8.8.8.8", separator: " " },
    summary: "Use these DNS servers instead of the system default.",
    detail: "Only relevant when curl is built against c-ares.",
    order: 3040,
  },
  {
    id: "dohUrl",
    long: "--doh-url",
    group: "dns",
    kind: "text",
    arg: { placeholder: "https://cloudflare-dns.com/dns-query", separator: " " },
    summary: "Resolve hostnames via DNS-over-HTTPS at this URL.",
    detail: "Encrypts DNS lookups, hiding them from a network-level observer.",
    order: 3050,
  },
  {
    id: "dohInsecure",
    long: "--doh-insecure",
    group: "dns",
    kind: "boolean",
    danger: "caution",
    requires: ["dohUrl"],
    summary: "Do not verify the DoH server's TLS certificate.",
    detail: "Defeats the point of using an encrypted resolver in the first place — only for testing.",
    order: 3060,
  },
  {
    id: "dohCertStatus",
    long: "--doh-cert-status",
    group: "dns",
    kind: "boolean",
    requires: ["dohUrl"],
    summary: "Verify the DoH server's certificate revocation status via OCSP stapling.",
    detail: "Fails the DoH lookup if the server's certificate is reported revoked.",
    order: 3070,
  },

  // ══ tls / ssl ══════════════════════════════════════════════════════════════
  {
    id: "insecure",
    short: "-k",
    long: "--insecure",
    group: "tls",
    kind: "boolean",
    preferShort: true,
    danger: "caution",
    summary: "Skip TLS certificate verification.",
    detail: "Defeats the entire point of TLS — the connection is no longer protected against interception. Only for testing against a server with a self-signed or expired cert you already trust for other reasons.",
    order: 4000,
  },
  {
    id: "cacert",
    long: "--cacert",
    group: "tls",
    kind: "path",
    arg: { placeholder: "ca-bundle.pem", separator: " " },
    summary: "Use this CA certificate bundle instead of the system default.",
    detail: "Needed when talking to a server whose certificate chains to a private/internal CA.",
    order: 4010,
  },
  {
    id: "capath",
    long: "--capath",
    group: "tls",
    kind: "path",
    arg: { placeholder: "/etc/ssl/certs", separator: " " },
    summary: "Directory of CA certificates, hashed for OpenSSL's lookup format.",
    detail: "An alternative to --cacert when the CAs are laid out as an OpenSSL hash directory rather than one bundle file.",
    order: 4020,
  },
  {
    id: "caNative",
    long: "--ca-native",
    group: "tls",
    kind: "boolean",
    summary: "Load CA certificates from the OS trust store.",
    detail: "Uses the platform's own certificate store (e.g. Windows/macOS keychain) instead of a bundled CA file.",
    order: 4030,
  },
  {
    id: "cert",
    short: "-E",
    long: "--cert",
    group: "tls",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "client.pem:password", separator: " " },
    summary: "Client certificate to present for mutual TLS.",
    detail: "certificate[:password] — the password half is optional and, like --user, visible in shell history if given here.",
    order: 4040,
  },
  {
    id: "certType",
    long: "--cert-type",
    group: "tls",
    kind: "enum",
    requires: ["cert"],
    options: [
      { value: "none", label: "curl default (PEM)", renders: "" },
      { value: "PEM", label: "PEM", renders: "--cert-type PEM" },
      { value: "DER", label: "DER", renders: "--cert-type DER" },
      { value: "P12", label: "P12 (PKCS#12)", renders: "--cert-type P12" },
      { value: "ENG", label: "ENG (engine-provided)", renders: "--cert-type ENG" },
    ],
    summary: "Format of the file given to --cert.",
    detail: "PEM is curl's default and by far the most common.",
    order: 4050,
  },
  {
    id: "certStatus",
    long: "--cert-status",
    group: "tls",
    kind: "boolean",
    summary: "Verify the server certificate's revocation status via OCSP stapling.",
    detail: "Fails the connection if the server's own certificate comes back revoked.",
    order: 4060,
  },
  {
    id: "key",
    long: "--key",
    group: "tls",
    kind: "path",
    requires: ["cert"],
    arg: { placeholder: "client.key", separator: " " },
    summary: "Private key file for the client certificate.",
    detail: "Only needed when the key is not already bundled inside the --cert file.",
    order: 4070,
  },
  {
    id: "keyType",
    long: "--key-type",
    group: "tls",
    kind: "enum",
    requires: ["key"],
    options: [
      { value: "none", label: "curl default (PEM)", renders: "" },
      { value: "PEM", label: "PEM", renders: "--key-type PEM" },
      { value: "DER", label: "DER", renders: "--key-type DER" },
      { value: "ENG", label: "ENG (engine-provided)", renders: "--key-type ENG" },
    ],
    summary: "Format of the file given to --key.",
    detail: "PEM is curl's default.",
    order: 4080,
  },
  {
    id: "pass",
    long: "--pass",
    group: "tls",
    kind: "text",
    danger: "caution",
    requires: ["key"],
    arg: { placeholder: "passphrase", separator: " " },
    summary: "Passphrase for an encrypted private key.",
    detail: "Visible in shell history the same as --user's password half.",
    order: 4090,
  },
  {
    id: "engine",
    long: "--engine",
    group: "tls",
    kind: "text",
    arg: { placeholder: "pkcs11", separator: " " },
    summary: "OpenSSL crypto engine to use for keys and certificates.",
    detail: "For hardware security modules and smart cards. Run curl --engine list to see what your build supports.",
    order: 4100,
  },
  {
    id: "ciphers",
    long: "--ciphers",
    group: "tls",
    kind: "text",
    arg: { placeholder: "ECDHE-RSA-AES256-GCM-SHA384", separator: " " },
    summary: "TLS 1.0-1.2 cipher suite list to offer.",
    detail: "Colon-separated, in the TLS library's own cipher-name syntax. Use --tls13-ciphers for TLS 1.3.",
    order: 4110,
  },
  {
    id: "tls13Ciphers",
    long: "--tls13-ciphers",
    group: "tls",
    kind: "text",
    arg: { placeholder: "TLS_AES_256_GCM_SHA384", separator: " " },
    summary: "TLS 1.3 cipher suite list to offer.",
    detail: "TLS 1.3 uses a separate, smaller cipher-suite namespace from --ciphers.",
    order: 4120,
  },
  {
    id: "curves",
    long: "--curves",
    group: "tls",
    kind: "text",
    arg: { placeholder: "X25519", separator: " " },
    summary: "TLS key-exchange (elliptic curve) algorithms to offer.",
    detail: "Colon-separated list, in preference order.",
    order: 4130,
  },
  {
    id: "sigalgs",
    long: "--sigalgs",
    group: "tls",
    kind: "text",
    arg: { placeholder: "ECDSA+SHA256", separator: " " },
    summary: "TLS signature algorithms to offer.",
    detail: "Colon-separated, in the TLS library's own syntax.",
    order: 4140,
  },
  {
    id: "ech",
    long: "--ech",
    group: "tls",
    kind: "text",
    arg: { placeholder: "true", separator: " " },
    summary: "Configure TLS Encrypted Client Hello.",
    detail: "true/false/hard-fail, or grease/pn:<name> — hides the SNI hostname from network observers on servers that support ECH.",
    order: 4150,
  },
  {
    id: "tlsv1",
    short: "-1",
    long: "--tlsv1",
    group: "tls",
    kind: "boolean",
    preferShort: true,
    summary: "Require TLS 1.0 or newer.",
    detail: "Sets a floor, not a ceiling — the actual version negotiated may be higher.",
    order: 4160,
  },
  {
    id: "tlsv12",
    long: "--tlsv1.2",
    group: "tls",
    kind: "boolean",
    summary: "Require TLS 1.2 or newer.",
    detail: "A reasonable minimum floor for a modern service.",
    order: 4170,
  },
  {
    id: "tlsv13",
    long: "--tlsv1.3",
    group: "tls",
    kind: "boolean",
    summary: "Require TLS 1.3 or newer.",
    detail: "The strictest floor curl offers.",
    order: 4180,
  },
  {
    id: "tlsMax",
    long: "--tls-max",
    group: "tls",
    kind: "enum",
    options: [
      { value: "none", label: "curl default (no ceiling)", renders: "" },
      { value: "default", label: "default — TLS library's own default", renders: "--tls-max default" },
      { value: "1.2", label: "1.2", renders: "--tls-max 1.2" },
      { value: "1.3", label: "1.3", renders: "--tls-max 1.3" },
    ],
    summary: "Highest TLS version curl may negotiate.",
    detail: "A ceiling, the opposite of --tlsv1.2/--tlsv1.3's floor. Useful for reproducing an old client's behavior against a server.",
    order: 4190,
  },
  {
    id: "tlsEarlydata",
    long: "--tls-earlydata",
    group: "tls",
    kind: "boolean",
    summary: "Allow TLS 1.3 early data (0-RTT).",
    detail: "Sends request data in the first flight of the TLS handshake — faster, but that data has weaker replay protection than after the handshake completes.",
    order: 4200,
  },
  {
    id: "alpnDisable",
    long: "--no-alpn",
    group: "tls",
    kind: "boolean",
    summary: "Disable the TLS ALPN extension.",
    detail: "ALPN is how curl and the server agree on HTTP/2 vs HTTP/1.1 during the TLS handshake; disabling it forces HTTP/1.1-style negotiation.",
    order: 4210,
  },
  {
    id: "falseStart",
    long: "--false-start",
    group: "deprecated",
    kind: "boolean",
    summary: "Enable TLS False Start.",
    detail: "An older latency optimization that sends application data before the handshake fully finishes. Superseded by TLS 1.3's own early-data design.",
    order: 17020,
  },
  {
    id: "noNpn",
    long: "--no-npn",
    group: "deprecated",
    kind: "boolean",
    summary: "Disable the (obsolete) NPN TLS extension.",
    detail: "NPN was replaced by ALPN years ago and modern curl builds no longer support it — this flag is accepted but does nothing.",
    order: 17030,
  },
  {
    id: "noSessionid",
    long: "--no-sessionid",
    group: "tls",
    kind: "boolean",
    danger: "caution",
    summary: "Disable TLS session-ID reuse.",
    detail: "Forces a full handshake on every connection instead of resuming a session — slower, purely for testing/debugging.",
    order: 4220,
  },
  {
    id: "hsts",
    long: "--hsts",
    group: "tls",
    kind: "path",
    arg: { placeholder: "hsts-cache.txt", separator: " " },
    summary: "Enable HSTS and persist the cache to this file.",
    detail: "Remembers which hosts have demanded HTTPS, so a later plain http:// URL to the same host is upgraded automatically.",
    order: 4230,
  },
  {
    id: "altSvc",
    long: "--alt-svc",
    group: "tls",
    kind: "path",
    arg: { placeholder: "altsvc-cache.txt", separator: " " },
    summary: "Enable the Alt-Svc: cache, persisted to this file.",
    detail: "Lets curl remember and use an alternate service (e.g. an HTTP/3 endpoint) a server previously advertised.",
    order: 4240,
  },
  {
    id: "pinnedpubkey",
    long: "--pinnedpubkey",
    group: "tls",
    kind: "text",
    arg: { placeholder: "sha256//AAAAAAAAAAAAAAAAAAAAAA==", separator: " " },
    summary: "Only accept a server whose public key matches this pin.",
    detail: "A file path to the key, or sha256// followed by the base64 hash. Defends against a compromised or coerced CA issuing a valid-but-wrong certificate.",
    order: 4250,
  },
  {
    id: "crlfile",
    long: "--crlfile",
    group: "tls",
    kind: "path",
    arg: { placeholder: "revoked.pem", separator: " " },
    summary: "Certificate Revocation List to check the server certificate against.",
    detail: "Rejects the connection if the server's certificate appears on this CRL.",
    order: 4260,
  },
  {
    id: "sslReqd",
    long: "--ssl-reqd",
    group: "tls",
    kind: "boolean",
    conflictsWith: ["ssl"],
    summary: "Require an explicit TLS upgrade (STARTTLS) to succeed; fail otherwise.",
    detail: "For protocols that opportunistically upgrade to TLS (FTP, SMTP, POP3, IMAP) — unlike plain --ssl, this refuses to fall back to plaintext.",
    order: 4270,
  },
  {
    id: "ssl",
    long: "--ssl",
    group: "tls",
    kind: "boolean",
    conflictsWith: ["sslReqd"],
    summary: "Try to use TLS/SSL, but continue over plaintext if it fails.",
    detail: "The opportunistic counterpart to --ssl-reqd, for the protocols that support STARTTLS-style upgrade.",
    order: 4280,
  },
  {
    id: "sslNoRevoke",
    long: "--ssl-no-revoke",
    group: "tls",
    kind: "boolean",
    danger: "caution",
    summary: "Disable certificate revocation checks (Schannel only).",
    detail: "Windows Schannel builds only. Skips checking whether the server's certificate has been revoked.",
    order: 4290,
  },
  {
    id: "sslRevokeBestEffort",
    long: "--ssl-revoke-best-effort",
    group: "tls",
    kind: "boolean",
    conflictsWith: ["sslNoRevoke"],
    summary: "Ignore revocation-check failures caused by an offline or unreachable CRL/OCSP endpoint (Schannel only).",
    detail: "Softer than --ssl-no-revoke: still checks when it can, just does not fail the connection when the check itself is unavailable.",
    order: 4300,
  },
  {
    id: "sslAutoClientCert",
    long: "--ssl-auto-client-cert",
    group: "tls",
    kind: "boolean",
    summary: "Automatically locate and use a client certificate (Schannel only).",
    detail: "Lets Windows' own certificate store supply the client cert instead of pointing curl at one with --cert.",
    order: 4310,
  },
  {
    id: "sslAllowBeast",
    long: "--ssl-allow-beast",
    group: "deprecated",
    kind: "boolean",
    danger: "caution",
    summary: "Tolerate the BEAST TLS vulnerability for compatibility with very old servers.",
    detail: "Deliberately weakens transport security. Only for interoperating with something that cannot be fixed or upgraded.",
    order: 17040,
  },
  {
    id: "sslSessions",
    long: "--ssl-sessions",
    group: "tls",
    kind: "path",
    arg: { placeholder: "sessions.txt", separator: " " },
    summary: "Load and save TLS session tickets to this file between runs.",
    detail: "Lets a fresh curl process resume a TLS session instead of starting a full handshake.",
    order: 4320,
  },
  {
    id: "dumpCaEmbed",
    long: "--dump-ca-embed",
    group: "tls",
    kind: "boolean",
    summary: "Write curl's embedded CA bundle to standard output and exit.",
    detail: "Only relevant on builds that ship a bundled CA store.",
    order: 4330,
  },
  {
    id: "sslv2",
    short: "-2",
    long: "--sslv2",
    group: "deprecated",
    kind: "boolean",
    preferShort: true,
    danger: "caution",
    summary: "Use SSLv2.",
    detail: "SSLv2 has been broken for decades and modern TLS libraries refuse to negotiate it at all — this flag has no effect on any current build.",
    order: 17050,
  },
  {
    id: "sslv3",
    short: "-3",
    long: "--sslv3",
    group: "deprecated",
    kind: "boolean",
    preferShort: true,
    danger: "caution",
    summary: "Use SSLv3.",
    detail: "SSLv3 is broken (POODLE) and disabled in essentially every modern TLS library build — this flag has no practical effect.",
    order: 17060,
  },
  {
    id: "tlsv10",
    long: "--tlsv1.0",
    group: "deprecated",
    kind: "boolean",
    danger: "caution",
    summary: "Require exactly TLS 1.0.",
    detail: "TLS 1.0 is deprecated industry-wide; most servers and many TLS library builds no longer accept it.",
    order: 17070,
  },
  {
    id: "tlsv11",
    long: "--tlsv1.1",
    group: "deprecated",
    kind: "boolean",
    danger: "caution",
    summary: "Require exactly TLS 1.1.",
    detail: "TLS 1.1 is deprecated industry-wide alongside 1.0.",
    order: 17080,
  },
  {
    id: "tlsauthtype",
    long: "--tlsauthtype",
    group: "deprecated",
    kind: "text",
    arg: { placeholder: "SRP", separator: " " },
    summary: "TLS authentication type — only SRP is defined.",
    detail: "TLS-SRP is rarely implemented by servers or TLS libraries today.",
    order: 17090,
  },
  {
    id: "tlspassword",
    long: "--tlspassword",
    group: "deprecated",
    kind: "text",
    danger: "caution",
    requires: ["tlsauthtype"],
    arg: { placeholder: "password", separator: " " },
    summary: "Password for TLS-SRP authentication.",
    detail: "Visible in shell history. Only meaningful alongside --tlsauthtype SRP.",
    order: 17100,
  },
  {
    id: "tlsuser",
    long: "--tlsuser",
    group: "deprecated",
    kind: "text",
    requires: ["tlsauthtype"],
    arg: { placeholder: "user", separator: " " },
    summary: "Username for TLS-SRP authentication.",
    detail: "Only meaningful alongside --tlsauthtype SRP.",
    order: 17110,
  },
  {
    id: "egdFile",
    long: "--egd-file",
    group: "deprecated",
    kind: "path",
    arg: { placeholder: "/path/egd-socket", separator: " " },
    summary: "EGD socket path for random data.",
    detail: "Modern TLS libraries no longer use an Entropy Gathering Daemon — this flag is a no-op on any current build.",
    order: 17120,
  },
  {
    id: "randomFile",
    long: "--random-file",
    group: "deprecated",
    kind: "path",
    arg: { placeholder: "/dev/urandom", separator: " " },
    summary: "File to read extra random data from.",
    detail: "Modern TLS libraries seed themselves from the OS CSPRNG — this flag is a no-op on any current build.",
    order: 17130,
  },

  // ══ proxy ══════════════════════════════════════════════════════════════════
  {
    id: "proxy",
    short: "-x",
    long: "--proxy",
    group: "proxy",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "http://proxy:8080", separator: " " },
    summary: "Use this proxy for the request.",
    detail: "Scheme defaults to http:// if omitted. Use socks5:// / socks4:// etc. for a SOCKS proxy instead of the dedicated --socks* flags.",
    order: 5000,
  },
  {
    id: "preproxy",
    long: "--preproxy",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "socks5://127.0.0.1:1080", separator: " " },
    summary: "SOCKS proxy to connect through before reaching --proxy.",
    detail: "Chains a SOCKS hop in front of an HTTP(S) proxy.",
    order: 5010,
  },
  {
    id: "proxytunnel",
    short: "-p",
    long: "--proxytunnel",
    group: "proxy",
    kind: "boolean",
    preferShort: true,
    summary: "Tunnel through an HTTP proxy via CONNECT, even for a plain http:// URL.",
    detail: "Normally only https:// URLs get a CONNECT tunnel through an HTTP proxy; this forces it for http:// too.",
    order: 5020,
  },
  {
    id: "noproxy",
    long: "--noproxy",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "localhost,127.0.0.1", separator: " " },
    summary: "Hosts that should bypass the proxy entirely.",
    detail: "Comma-separated list; * disables the proxy for every host.",
    order: 5030,
  },
  {
    id: "proxy10",
    long: "--proxy1.0",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "proxyhost:8080", separator: " " },
    summary: "Use this HTTP/1.0 proxy.",
    detail: "Like --proxy, but forces HTTP/1.0 towards the proxy specifically.",
    order: 5040,
  },
  {
    id: "socks4",
    long: "--socks4",
    group: "proxy",
    kind: "text",
    conflictsWith: ["socks4a", "socks5", "socks5Hostname", "proxy"],
    arg: { placeholder: "proxyhost:1080", separator: " " },
    summary: "Use this SOCKS4 proxy.",
    detail: "DNS resolution happens locally, then the resolved IP is sent to the proxy.",
    order: 5050,
  },
  {
    id: "socks4a",
    long: "--socks4a",
    group: "proxy",
    kind: "text",
    conflictsWith: ["socks4", "socks5", "socks5Hostname", "proxy"],
    arg: { placeholder: "proxyhost:1080", separator: " " },
    summary: "Use this SOCKS4a proxy.",
    detail: "Like SOCKS4, but the hostname is resolved by the proxy instead of locally.",
    order: 5060,
  },
  {
    id: "socks5",
    long: "--socks5",
    group: "proxy",
    kind: "text",
    conflictsWith: ["socks4", "socks4a", "socks5Hostname", "proxy"],
    arg: { placeholder: "proxyhost:1080", separator: " " },
    summary: "Use this SOCKS5 proxy, resolving the hostname locally.",
    detail: "For proxy-side resolution instead, use --socks5-hostname.",
    order: 5070,
  },
  {
    id: "socks5Hostname",
    long: "--socks5-hostname",
    group: "proxy",
    kind: "text",
    conflictsWith: ["socks4", "socks4a", "socks5", "proxy"],
    arg: { placeholder: "proxyhost:1080", separator: " " },
    summary: "Use this SOCKS5 proxy, letting the proxy resolve the hostname.",
    detail: "Keeps DNS lookups off the local network entirely.",
    order: 5080,
  },
  {
    id: "socks5Basic",
    long: "--socks5-basic",
    group: "proxy",
    kind: "boolean",
    summary: "Use username/password authentication with the SOCKS5 proxy.",
    detail: "Pair with --proxy-user for the credentials.",
    order: 5090,
  },
  {
    id: "socks5Gssapi",
    long: "--socks5-gssapi",
    group: "proxy",
    kind: "boolean",
    summary: "Use GSS-API authentication with the SOCKS5 proxy.",
    detail: "Needs a valid Kerberos ticket already in your credential cache.",
    order: 5100,
  },
  {
    id: "socks5GssapiNec",
    long: "--socks5-gssapi-nec",
    group: "proxy",
    kind: "boolean",
    requires: ["socks5Gssapi"],
    summary: "Compatibility mode for NEC's SOCKS5 GSS-API implementation.",
    detail: "Only needed against that specific, uncommon proxy implementation.",
    order: 5110,
  },
  {
    id: "socks5GssapiService",
    long: "--socks5-gssapi-service",
    group: "proxy",
    kind: "text",
    requires: ["socks5Gssapi"],
    arg: { placeholder: "rcmd", separator: " " },
    summary: "SOCKS5 GSS-API service name, if not the default.",
    detail: "Only needed when the proxy registered its Kerberos principal under a nonstandard service name.",
    order: 5120,
  },
  {
    id: "proxyUser",
    short: "-U",
    long: "--proxy-user",
    group: "proxy",
    kind: "text",
    preferShort: true,
    danger: "caution",
    arg: { placeholder: "user:password", separator: " " },
    summary: "Credentials for the proxy.",
    detail: "Same shell-history exposure caveat as --user.",
    order: 5130,
  },
  {
    id: "proxyBasic",
    long: "--proxy-basic",
    group: "proxy",
    kind: "boolean",
    conflictsWith: ["proxyDigest", "proxyNtlm", "proxyNegotiate", "proxyAnyauth"],
    summary: "Force HTTP Basic authentication with the proxy.",
    detail: "Only meaningfully safe when the hop to the proxy itself is also encrypted.",
    order: 5140,
  },
  {
    id: "proxyDigest",
    long: "--proxy-digest",
    group: "proxy",
    kind: "boolean",
    conflictsWith: ["proxyBasic", "proxyNtlm", "proxyNegotiate", "proxyAnyauth"],
    summary: "Force HTTP Digest authentication with the proxy.",
    detail: "Does not send the proxy password in the clear, unlike Basic.",
    order: 5150,
  },
  {
    id: "proxyNtlm",
    long: "--proxy-ntlm",
    group: "proxy",
    kind: "boolean",
    conflictsWith: ["proxyBasic", "proxyDigest", "proxyNegotiate", "proxyAnyauth"],
    summary: "Force NTLM authentication with the proxy.",
    detail: "Common against Windows-hosted corporate proxies.",
    order: 5160,
  },
  {
    id: "proxyNegotiate",
    long: "--proxy-negotiate",
    group: "proxy",
    kind: "boolean",
    conflictsWith: ["proxyBasic", "proxyDigest", "proxyNtlm", "proxyAnyauth"],
    summary: "Force Negotiate (SPNEGO/Kerberos) authentication with the proxy.",
    detail: "Needs a valid Kerberos ticket already in your credential cache.",
    order: 5170,
  },
  {
    id: "proxyAnyauth",
    long: "--proxy-anyauth",
    group: "proxy",
    kind: "boolean",
    conflictsWith: ["proxyBasic", "proxyDigest", "proxyNtlm", "proxyNegotiate"],
    summary: "Let curl pick the proxy authentication method automatically.",
    detail: "curl probes the proxy and picks the most secure method it offers.",
    order: 5180,
  },
  {
    id: "proxyServiceName",
    long: "--proxy-service-name",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "rcmd", separator: " " },
    summary: "SPNEGO service name to use against the proxy.",
    detail: "Only needed when the proxy registered its Kerberos principal under a nonstandard service name.",
    order: 5190,
  },
  {
    id: "proxyHeader",
    long: "--proxy-header",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "X-Proxy-Auth: token", separator: " " },
    summary: "Extra header to send only to the proxy in a CONNECT request.",
    detail: "Same syntax as -H, but scoped to the CONNECT request rather than the real request. Real curl allows this repeated; only one is modeled here.",
    order: 5200,
  },
  {
    id: "suppressConnectHeaders",
    long: "--suppress-connect-headers",
    group: "proxy",
    kind: "boolean",
    requires: ["proxytunnel"],
    summary: "Do not show proxy CONNECT response headers in verbose/include output.",
    detail: "Keeps -v/-i output focused on the real server's response instead of the proxy handshake.",
    order: 5210,
  },
  {
    id: "proxyInsecure",
    long: "--proxy-insecure",
    group: "proxy",
    kind: "boolean",
    danger: "caution",
    summary: "Skip TLS certificate verification for an HTTPS proxy.",
    detail: "Same trade-off as --insecure, scoped to the connection to the proxy.",
    order: 5220,
  },
  {
    id: "proxyCacert",
    long: "--proxy-cacert",
    group: "proxy",
    kind: "path",
    arg: { placeholder: "proxy-ca.pem", separator: " " },
    summary: "CA bundle to verify the HTTPS proxy's certificate against.",
    detail: "The proxy-hop equivalent of --cacert.",
    order: 5230,
  },
  {
    id: "proxyCapath",
    long: "--proxy-capath",
    group: "proxy",
    kind: "path",
    arg: { placeholder: "/etc/ssl/certs", separator: " " },
    summary: "CA directory to verify the HTTPS proxy's certificate against.",
    detail: "The proxy-hop equivalent of --capath.",
    order: 5240,
  },
  {
    id: "proxyCaNative",
    long: "--proxy-ca-native",
    group: "proxy",
    kind: "boolean",
    summary: "Load CA certificates from the OS trust store for verifying the proxy.",
    detail: "The proxy-hop equivalent of --ca-native.",
    order: 5250,
  },
  {
    id: "proxyCert",
    long: "--proxy-cert",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "client.pem:password", separator: " " },
    summary: "Client certificate to present to an HTTPS proxy.",
    detail: "The proxy-hop equivalent of --cert.",
    order: 5260,
  },
  {
    id: "proxyCertType",
    long: "--proxy-cert-type",
    group: "proxy",
    kind: "enum",
    requires: ["proxyCert"],
    options: [
      { value: "none", label: "curl default (PEM)", renders: "" },
      { value: "PEM", label: "PEM", renders: "--proxy-cert-type PEM" },
      { value: "DER", label: "DER", renders: "--proxy-cert-type DER" },
      { value: "P12", label: "P12 (PKCS#12)", renders: "--proxy-cert-type P12" },
    ],
    summary: "Format of the file given to --proxy-cert.",
    detail: "The proxy-hop equivalent of --cert-type.",
    order: 5270,
  },
  {
    id: "proxyKey",
    long: "--proxy-key",
    group: "proxy",
    kind: "path",
    requires: ["proxyCert"],
    arg: { placeholder: "client.key", separator: " " },
    summary: "Private key for the proxy client certificate.",
    detail: "The proxy-hop equivalent of --key.",
    order: 5280,
  },
  {
    id: "proxyKeyType",
    long: "--proxy-key-type",
    group: "proxy",
    kind: "enum",
    requires: ["proxyKey"],
    options: [
      { value: "none", label: "curl default (PEM)", renders: "" },
      { value: "PEM", label: "PEM", renders: "--proxy-key-type PEM" },
      { value: "DER", label: "DER", renders: "--proxy-key-type DER" },
    ],
    summary: "Format of the file given to --proxy-key.",
    detail: "The proxy-hop equivalent of --key-type.",
    order: 5290,
  },
  {
    id: "proxyPass",
    long: "--proxy-pass",
    group: "proxy",
    kind: "text",
    danger: "caution",
    requires: ["proxyKey"],
    arg: { placeholder: "passphrase", separator: " " },
    summary: "Passphrase for an encrypted proxy client key.",
    detail: "The proxy-hop equivalent of --pass.",
    order: 5300,
  },
  {
    id: "proxyCiphers",
    long: "--proxy-ciphers",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "ECDHE-RSA-AES256-GCM-SHA384", separator: " " },
    summary: "TLS 1.0-1.2 cipher suite list to offer the proxy.",
    detail: "The proxy-hop equivalent of --ciphers.",
    order: 5310,
  },
  {
    id: "proxyTls13Ciphers",
    long: "--proxy-tls13-ciphers",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "TLS_AES_256_GCM_SHA384", separator: " " },
    summary: "TLS 1.3 cipher suite list to offer the proxy.",
    detail: "The proxy-hop equivalent of --tls13-ciphers.",
    order: 5320,
  },
  {
    id: "proxyCrlfile",
    long: "--proxy-crlfile",
    group: "proxy",
    kind: "path",
    arg: { placeholder: "revoked.pem", separator: " " },
    summary: "Certificate Revocation List to check the proxy's certificate against.",
    detail: "The proxy-hop equivalent of --crlfile.",
    order: 5330,
  },
  {
    id: "proxyPinnedpubkey",
    long: "--proxy-pinnedpubkey",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "sha256//AAAAAAAAAAAAAAAAAAAAAA==", separator: " " },
    summary: "Only accept a proxy whose public key matches this pin.",
    detail: "The proxy-hop equivalent of --pinnedpubkey.",
    order: 5340,
  },
  {
    id: "proxyTlsv1",
    long: "--proxy-tlsv1",
    group: "proxy",
    kind: "boolean",
    summary: "Require TLS 1.0 or newer when connecting to the proxy.",
    detail: "The proxy-hop equivalent of --tlsv1.",
    order: 5350,
  },
  {
    id: "proxyTlsauthtype",
    long: "--proxy-tlsauthtype",
    group: "proxy",
    kind: "text",
    arg: { placeholder: "SRP", separator: " " },
    summary: "TLS authentication type for the proxy — only SRP is defined.",
    detail: "The proxy-hop equivalent of --tlsauthtype.",
    order: 5360,
  },
  {
    id: "proxyTlsuser",
    long: "--proxy-tlsuser",
    group: "proxy",
    kind: "text",
    requires: ["proxyTlsauthtype"],
    arg: { placeholder: "user", separator: " " },
    summary: "Username for TLS-SRP authentication with the proxy.",
    detail: "The proxy-hop equivalent of --tlsuser.",
    order: 5370,
  },
  {
    id: "proxyTlspassword",
    long: "--proxy-tlspassword",
    group: "proxy",
    kind: "text",
    danger: "caution",
    requires: ["proxyTlsauthtype"],
    arg: { placeholder: "password", separator: " " },
    summary: "Password for TLS-SRP authentication with the proxy.",
    detail: "The proxy-hop equivalent of --tlspassword.",
    order: 5380,
  },
  {
    id: "proxyHttp2",
    long: "--proxy-http2",
    group: "proxy",
    kind: "boolean",
    summary: "Attempt HTTP/2 towards an HTTPS proxy.",
    detail: "The proxy-hop equivalent of --http2.",
    order: 5390,
  },
  {
    id: "proxyHttp3",
    long: "--proxy-http3",
    group: "proxy",
    kind: "boolean",
    summary: "Attempt HTTP/3 towards the proxy.",
    detail: "The proxy-hop equivalent of --http3.",
    order: 5400,
  },
  {
    id: "proxySslAutoClientCert",
    long: "--proxy-ssl-auto-client-cert",
    group: "proxy",
    kind: "boolean",
    summary: "Automatically locate and use a client certificate for the proxy (Schannel only).",
    detail: "The proxy-hop equivalent of --ssl-auto-client-cert.",
    order: 5410,
  },
  {
    id: "proxySslAllowBeast",
    long: "--proxy-ssl-allow-beast",
    group: "deprecated",
    kind: "boolean",
    danger: "caution",
    summary: "Tolerate the BEAST TLS vulnerability towards the proxy.",
    detail: "The proxy-hop equivalent of --ssl-allow-beast.",
    order: 17140,
  },

  // ══ http ═══════════════════════════════════════════════════════════════════
  {
    id: "request",
    short: "-X",
    long: "--request",
    group: "http",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "POST", separator: " " },
    summary: "HTTP method to use instead of curl's own default.",
    detail: "curl infers GET, or POST when a body is given — this overrides that inference, e.g. for PUT, PATCH or DELETE.",
    order: 6000,
  },
  {
    id: "head",
    short: "-I",
    long: "--head",
    group: "http",
    kind: "boolean",
    preferShort: true,
    summary: "Fetch headers only, via an HTTP HEAD request.",
    detail: "No response body is requested or shown.",
    order: 6010,
  },
  {
    id: "get",
    short: "-G",
    long: "--get",
    group: "http",
    kind: "boolean",
    preferShort: true,
    summary: "Send any -d/--data as a URL query string via GET instead of as a POST body.",
    detail: "Turns curl -d 'a=1' url into a GET to url?a=1 — handy for building a query string from repeated -d entries.",
    order: 6020,
  },
  {
    id: "location",
    short: "-L",
    long: "--location",
    group: "http",
    kind: "boolean",
    preferShort: true,
    summary: "Follow HTTP redirects.",
    detail: "Without this, curl prints the redirect response itself rather than following it.",
    order: 6030,
  },
  {
    id: "follow",
    long: "--follow",
    group: "http",
    kind: "boolean",
    summary: "Follow redirects, per the current redirect-handling spec.",
    detail: "Newer alias curl is transitioning towards in place of --location; behaves the same way today.",
    order: 6040,
  },
  {
    id: "locationTrusted",
    long: "--location-trusted",
    group: "http",
    kind: "boolean",
    danger: "caution",
    requires: ["location"],
    summary: "Follow redirects and keep sending --user credentials, even to a different host.",
    detail: "Plain --location strips Authorization on a cross-host redirect to avoid leaking credentials to a server you did not intend to send them to. This flag disables that protection.",
    order: 6050,
  },
  {
    id: "maxRedirs",
    long: "--max-redirs",
    group: "http",
    kind: "number",
    requires: ["location"],
    arg: { placeholder: "50", min: 0, separator: " " },
    summary: "Maximum number of redirects to follow.",
    detail: "Guards against a redirect loop running forever.",
    order: 6060,
  },
  {
    id: "post301",
    long: "--post301",
    group: "http",
    kind: "boolean",
    requires: ["location"],
    summary: "Keep the POST method across a 301 redirect.",
    detail: "By default curl (like most browsers) switches to GET after a 301 following a POST — this preserves the original method instead.",
    order: 6070,
  },
  {
    id: "post302",
    long: "--post302",
    group: "http",
    kind: "boolean",
    requires: ["location"],
    summary: "Keep the POST method across a 302 redirect.",
    detail: "The 302 counterpart to --post301.",
    order: 6080,
  },
  {
    id: "post303",
    long: "--post303",
    group: "http",
    kind: "boolean",
    requires: ["location"],
    summary: "Keep the POST method across a 303 redirect.",
    detail: "The 303 counterpart to --post301/--post302.",
    order: 6090,
  },
  {
    id: "userAgent",
    short: "-A",
    long: "--user-agent",
    group: "http",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "MyApp/1.0", separator: " " },
    summary: "User-Agent header to send.",
    detail: "Shorthand for -H 'User-Agent: ...' — if both are given, the last one on the line wins.",
    order: 6100,
  },
  {
    id: "referer",
    short: "-e",
    long: "--referer",
    group: "http",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "https://example.com/", separator: " " },
    summary: "Referer header to send.",
    detail: "Pass ;auto after a URL (e.g. -e ';auto') to have curl set it automatically from the previous redirect target.",
    order: 6110,
  },
  {
    id: "cookie",
    short: "-b",
    long: "--cookie",
    group: "http",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "name=value", separator: " " },
    summary: "Cookie data to send, or a file to read cookies from.",
    detail: "A literal 'name=value' pair/list is sent as-is; a path is read as a Netscape-format cookie file.",
    order: 6120,
  },
  {
    id: "cookieJar",
    short: "-c",
    long: "--cookie-jar",
    group: "http",
    kind: "path",
    preferShort: true,
    arg: { placeholder: "cookies.txt", separator: " " },
    summary: "Write cookies received from the server to this file when the transfer ends.",
    detail: "Netscape cookie-file format, the same one --cookie reads back in.",
    order: 6130,
  },
  {
    id: "junkSessionCookies",
    short: "-j",
    long: "--junk-session-cookies",
    group: "http",
    kind: "boolean",
    preferShort: true,
    requires: ["cookie"],
    summary: "Discard session cookies (ones with no expiry) read from the --cookie file.",
    detail: "Mirrors what a browser does on restart — a fresh run behaves like a fresh session instead of replaying stale cookies.",
    order: 6140,
  },
  {
    id: "compressed",
    long: "--compressed",
    group: "http",
    kind: "boolean",
    summary: "Request a compressed response and decompress it automatically.",
    detail: "Only works when curl's build supports the compression the server picks (gzip/deflate/br/zstd) — fails otherwise.",
    order: 6150,
  },
  {
    id: "http10",
    short: "-0",
    long: "--http1.0",
    group: "http",
    kind: "boolean",
    preferShort: true,
    summary: "Use HTTP/1.0.",
    detail: "For a server or intermediary that misbehaves with keep-alive or chunked transfer encoding.",
    order: 6160,
  },
  {
    id: "http11",
    long: "--http1.1",
    group: "http",
    kind: "boolean",
    summary: "Use HTTP/1.1.",
    detail: "curl's traditional default before HTTP/2 support existed.",
    order: 6170,
  },
  {
    id: "http2",
    long: "--http2",
    group: "http",
    kind: "boolean",
    summary: "Attempt HTTP/2, with a fallback to HTTP/1.1.",
    detail: "Negotiated via TLS ALPN for https://, or via Upgrade: for plain http://.",
    order: 6180,
  },
  {
    id: "http2PriorKnowledge",
    long: "--http2-prior-knowledge",
    group: "http",
    kind: "boolean",
    summary: "Use HTTP/2 directly, without the HTTP/1.1 upgrade dance.",
    detail: "For a server you already know speaks HTTP/2 in cleartext — skips the negotiation round trip.",
    order: 6190,
  },
  {
    id: "http3",
    long: "--http3",
    group: "http",
    kind: "boolean",
    summary: "Attempt HTTP/3, with a fallback to an earlier version.",
    detail: "Needs a curl build with HTTP/3 (QUIC) support.",
    order: 6200,
  },
  {
    id: "http3Only",
    long: "--http3-only",
    group: "http",
    kind: "boolean",
    summary: "Use HTTP/3 only — fail if it cannot be negotiated.",
    detail: "Unlike --http3, does not fall back to an earlier HTTP version.",
    order: 6210,
  },
  {
    id: "http09",
    long: "--http0.9",
    group: "deprecated",
    kind: "boolean",
    danger: "caution",
    summary: "Accept an HTTP/0.9 response (no headers, body only).",
    detail: "curl rejects HTTP/0.9 responses by default since they cannot be told apart from a broken/truncated response — only re-enable this against a server you know genuinely speaks it.",
    order: 17150,
  },
  {
    id: "ignoreContentLength",
    long: "--ignore-content-length",
    group: "http",
    kind: "boolean",
    summary: "Ignore the Content-Length header on an HTTP response.",
    detail: "For a server that sends an incorrect length; curl then relies on the connection closing to know the body is done.",
    order: 6220,
  },
  {
    id: "disallowUsernameInUrl",
    long: "--disallow-username-in-url",
    group: "http",
    kind: "boolean",
    summary: "Refuse a URL that embeds a username (https://user@host/...).",
    detail: "A defense against SSRF-style URLs that smuggle credentials or confuse a naive URL parser downstream.",
    order: 6230,
  },
  {
    id: "etagSave",
    long: "--etag-save",
    group: "http",
    kind: "path",
    arg: { placeholder: "etag.txt", separator: " " },
    summary: "Save the response's ETag to this file.",
    detail: "Pair with --etag-compare on a later request to make a conditional GET.",
    order: 6240,
  },
  {
    id: "etagCompare",
    long: "--etag-compare",
    group: "http",
    kind: "path",
    arg: { placeholder: "etag.txt", separator: " " },
    summary: "Send If-None-Match with the ETag stored in this file.",
    detail: "The read half of the --etag-save/--etag-compare pair — turns a repeat request into a conditional GET.",
    order: 6250,
  },
  {
    id: "timeCond",
    short: "-z",
    long: "--time-cond",
    group: "http",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "20-Jan-2026", separator: " " },
    summary: "Only transfer if the remote file's timestamp matches this condition.",
    detail: "Prefix with - for \"older than\". Also accepts a filename, using that file's own mtime as the comparison point.",
    order: 6260,
  },
  {
    id: "trEncoding",
    long: "--tr-encoding",
    group: "http",
    kind: "boolean",
    summary: "Request a compressed transfer encoding for the response.",
    detail: "Distinct from --compressed's content-encoding — this asks for TE: compress-family encoding of the transfer itself.",
    order: 6270,
  },

  // ══ post — shaping for the -d/-F body entries in spec.ts ══════════════════
  {
    id: "formEscape",
    long: "--form-escape",
    group: "post",
    kind: "boolean",
    summary: "Escape form field names/filenames with backslashes instead of quotes.",
    detail: "Changes how -F field names or filenames containing \" or \\r/\\n are escaped in the multipart body.",
    order: 7000,
  },

  // ══ upload ═════════════════════════════════════════════════════════════════
  {
    id: "uploadFile",
    short: "-T",
    long: "--upload-file",
    group: "upload",
    kind: "path",
    preferShort: true,
    arg: { placeholder: "localfile", separator: " " },
    summary: "Send this local file as the request body (PUT-style upload).",
    detail: "Use - to read from stdin. Real curl allows pairing several -T with several URLs on one line; only one file is modeled here.",
    order: 8000,
  },
  {
    id: "append",
    short: "-a",
    long: "--append",
    group: "upload",
    kind: "boolean",
    preferShort: true,
    requires: ["uploadFile"],
    summary: "Append to the target file instead of overwriting it, when uploading.",
    detail: "FTP-only in practice — most other upload targets have no append semantics.",
    order: 8010,
  },
  {
    id: "createDirs",
    long: "--create-dirs",
    group: "upload",
    kind: "boolean",
    summary: "Create the local directory hierarchy for -o's path if it does not exist.",
    detail: "Without this, curl fails if the output path names a directory that is not there yet.",
    order: 8020,
  },
  {
    id: "createFileMode",
    long: "--create-file-mode",
    group: "upload",
    kind: "text",
    arg: { placeholder: "0600", separator: " " },
    summary: "Permission mode for a file curl creates (SFTP/FTP/FILE uploads).",
    detail: "Octal mode, applied only when curl itself creates the remote file.",
    order: 8030,
  },
  {
    id: "removeOnError",
    long: "--remove-on-error",
    group: "upload",
    kind: "boolean",
    summary: "Delete a partially written output file if the transfer fails.",
    detail: "Without this, a failed download or upload can leave a truncated file behind that looks complete at a glance.",
    order: 8040,
  },
  {
    id: "xattr",
    long: "--xattr",
    group: "upload",
    kind: "boolean",
    summary: "Store the URL and original filename in extended file attributes on the downloaded file.",
    detail: "Metadata only — has no effect on the file's actual content.",
    order: 8050,
  },

  // ══ ftp ════════════════════════════════════════════════════════════════════
  {
    id: "ftpMethod",
    long: "--ftp-method",
    group: "ftp",
    kind: "enum",
    options: [
      { value: "none", label: "curl default (multicwd)", renders: "" },
      { value: "multicwd", label: "multicwd — one CWD per path segment", renders: "--ftp-method multicwd" },
      { value: "nocwd", label: "nocwd — CWD never sent, full path with each command", renders: "--ftp-method nocwd" },
      { value: "singlecwd", label: "singlecwd — one CWD with the whole path", renders: "--ftp-method singlecwd" },
    ],
    summary: "How curl changes directory on the FTP server.",
    detail: "multicwd is most compatible but slowest against a deep path; nocwd/singlecwd trade compatibility for fewer round trips.",
    order: 9000,
  },
  {
    id: "ftpPasv",
    long: "--ftp-pasv",
    group: "ftp",
    kind: "boolean",
    summary: "Use passive (PASV) mode for the data connection.",
    detail: "curl already prefers passive mode by default; this makes it explicit.",
    order: 9010,
  },
  {
    id: "ftpPort",
    short: "-P",
    long: "--ftp-port",
    group: "ftp",
    kind: "text",
    preferShort: true,
    conflictsWith: ["ftpPasv"],
    arg: { placeholder: "eth0", separator: " " },
    summary: "Use active (PORT) mode, from this address/interface.",
    detail: "The opposite of passive mode — the server connects back to curl for the data channel.",
    order: 9020,
  },
  {
    id: "ftpSkipPasvIp",
    long: "--ftp-skip-pasv-ip",
    group: "ftp",
    kind: "boolean",
    summary: "Ignore the IP address the server offers in its PASV response.",
    detail: "Uses the same address curl already connected to instead — helps behind some NATs where the server reports its internal IP.",
    order: 9030,
  },
  {
    id: "ftpPret",
    long: "--ftp-pret",
    group: "ftp",
    kind: "boolean",
    summary: "Send PRET before PASV.",
    detail: "Required by some FTP servers (notably drftpd) before they will accept a passive-mode request.",
    order: 9040,
  },
  {
    id: "disableEprt",
    long: "--disable-eprt",
    group: "ftp",
    kind: "boolean",
    summary: "Never use EPRT or LPRT; use PORT instead.",
    detail: "For an FTP server whose EPRT/LPRT support is broken.",
    order: 9050,
  },
  {
    id: "disableEpsv",
    long: "--disable-epsv",
    group: "ftp",
    kind: "boolean",
    summary: "Never use EPSV; use PASV instead.",
    detail: "For an FTP server whose EPSV support is broken.",
    order: 9060,
  },
  {
    id: "ftpSslControl",
    long: "--ftp-ssl-control",
    group: "ftp",
    kind: "boolean",
    summary: "Require TLS for the login, but allow the data transfer to be plaintext.",
    detail: "A middle ground: credentials are protected but the file contents are not.",
    order: 9070,
  },
  {
    id: "ftpSslCcc",
    long: "--ftp-ssl-ccc",
    group: "ftp",
    kind: "boolean",
    summary: "Send CCC (Clear Command Channel) after authenticating, dropping back to plaintext control.",
    detail: "Some firewalls and NAT devices cannot follow an FTP session once the control channel is encrypted; CCC works around that.",
    order: 9080,
  },
  {
    id: "ftpSslCccMode",
    long: "--ftp-ssl-ccc-mode",
    group: "ftp",
    kind: "enum",
    requires: ["ftpSslCcc"],
    options: [
      { value: "none", label: "curl default (passive)", renders: "" },
      { value: "active", label: "active", renders: "--ftp-ssl-ccc-mode active" },
      { value: "passive", label: "passive", renders: "--ftp-ssl-ccc-mode passive" },
    ],
    summary: "How --ftp-ssl-ccc shuts down the TLS layer on the control connection.",
    detail: "passive is curl's default and works with more servers.",
    order: 9090,
  },
  {
    id: "ftpAccount",
    long: "--ftp-account",
    group: "ftp",
    kind: "text",
    arg: { placeholder: "account", separator: " " },
    summary: "Send an ACCT command with this value after login.",
    detail: "Only needed against FTP servers that require account information beyond username/password.",
    order: 9100,
  },
  {
    id: "ftpAlternativeToUser",
    long: "--ftp-alternative-to-user",
    group: "ftp",
    kind: "text",
    arg: { placeholder: "NOOP", separator: " " },
    summary: "Command to try if the normal USER/PASS login sequence fails.",
    detail: "A fallback for unusual FTP server login flows.",
    order: 9110,
  },
  {
    id: "ftpCreateDirs",
    long: "--ftp-create-dirs",
    group: "ftp",
    kind: "boolean",
    summary: "Create missing remote directories on an FTP upload.",
    detail: "Without this, uploading into a directory that does not exist yet on the server fails.",
    order: 9120,
  },
  {
    id: "quote",
    short: "-Q",
    long: "--quote",
    group: "ftp",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "-DELE remote-file", separator: " " },
    summary: "Send this raw command to the FTP/SFTP server before the transfer.",
    detail: "Prefix with - to run it only before an upload, or + to also run it before a download. Real curl allows this repeated for several commands; only one is modeled here.",
    order: 9130,
  },
  {
    id: "useAscii",
    short: "-B",
    long: "--use-ascii",
    group: "ftp",
    kind: "boolean",
    preferShort: true,
    summary: "Use ASCII/text transfer mode instead of binary.",
    detail: "Converts line endings in transit — appropriate for plain text, wrong for anything binary.",
    order: 9140,
  },
  {
    id: "crlf",
    long: "--crlf",
    group: "ftp",
    kind: "boolean",
    summary: "Convert LF to CRLF when uploading.",
    detail: "Matches the line-ending convention FTP and SMTP servers historically expect for text content.",
    order: 9150,
  },
  {
    id: "listOnly",
    short: "-l",
    long: "--list-only",
    group: "ftp",
    kind: "boolean",
    preferShort: true,
    summary: "List directory contents only, without transferring anything.",
    detail: "Works for FTP and, more recently, SFTP directory listings.",
    order: 9160,
  },

  // ══ ssh / scp / sftp ═══════════════════════════════════════════════════════
  {
    id: "pubkey",
    long: "--pubkey",
    group: "ssh",
    kind: "path",
    arg: { placeholder: "~/.ssh/id_ed25519.pub", separator: " " },
    summary: "Public key file for SSH authentication.",
    detail: "Pair with --key for the matching private key.",
    order: 10000,
  },
  {
    id: "hostpubmd5",
    long: "--hostpubmd5",
    group: "ssh",
    kind: "text",
    conflictsWith: ["hostpubsha256"],
    arg: { placeholder: "afe17cd62c4d3374a45b0d5f1b0c...", separator: " " },
    summary: "Only accept a server whose host key MD5 fingerprint matches this.",
    detail: "32 hex characters. Superseded in most modern setups by --hostpubsha256.",
    order: 10010,
  },
  {
    id: "hostpubsha256",
    long: "--hostpubsha256",
    group: "ssh",
    kind: "text",
    conflictsWith: ["hostpubmd5"],
    arg: { placeholder: "NcRedS+ULj3yLDIQTBd8P0nCTr...", separator: " " },
    summary: "Only accept a server whose host key SHA256 fingerprint matches this.",
    detail: "Base64, the same format ssh-keygen -l -E sha256 prints.",
    order: 10020,
  },
  {
    id: "knownhosts",
    long: "--knownhosts",
    group: "ssh",
    kind: "path",
    arg: { placeholder: "~/.ssh/known_hosts", separator: " " },
    summary: "known_hosts file to verify the server's host key against.",
    detail: "Standard OpenSSH known_hosts format.",
    order: 10030,
  },
  {
    id: "compressedSsh",
    long: "--compressed-ssh",
    group: "ssh",
    kind: "boolean",
    summary: "Enable SSH compression.",
    detail: "Trades CPU for bandwidth on the SCP/SFTP transfer.",
    order: 10040,
  },

  // ══ mail (smtp / pop3 / imap) ══════════════════════════════════════════════
  {
    id: "mailFrom",
    long: "--mail-from",
    group: "mail",
    kind: "text",
    arg: { placeholder: "sender@example.com", separator: " " },
    summary: "Envelope sender address for an SMTP send.",
    detail: "The MAIL FROM address, distinct from any From: header in the message body itself.",
    order: 11000,
  },
  {
    id: "mailRcpt",
    long: "--mail-rcpt",
    group: "mail",
    kind: "text",
    arg: { placeholder: "recipient@example.com", separator: " " },
    summary: "Envelope recipient address for an SMTP send.",
    detail: "The RCPT TO address. Real curl allows this repeated for several recipients; only one is modeled here.",
    order: 11010,
  },
  {
    id: "mailRcptAllowfails",
    long: "--mail-rcpt-allowfails",
    group: "mail",
    kind: "boolean",
    requires: ["mailRcpt"],
    summary: "Continue even if the server rejects one RCPT TO recipient.",
    detail: "Without this, one bad recipient aborts the whole send.",
    order: 11020,
  },
  {
    id: "mailAuth",
    long: "--mail-auth",
    group: "mail",
    kind: "text",
    arg: { placeholder: "originator@example.com", separator: " " },
    summary: "Originator address for an SMTP relay, when relaying on someone else's behalf.",
    detail: "Sent as the AUTH parameter on MAIL FROM — an SMTP relaying detail most sends do not need.",
    order: 11030,
  },
  {
    id: "loginOptions",
    long: "--login-options",
    group: "mail",
    kind: "text",
    arg: { placeholder: "AUTH=NTLM", separator: " " },
    summary: "Extra login options to send during server authentication.",
    detail: "Protocol-specific — mainly relevant to IMAP/POP3/SMTP servers with nonstandard auth setup requirements.",
    order: 11040,
  },
  {
    id: "uploadFlags",
    long: "--upload-flags",
    group: "mail",
    kind: "text",
    arg: { placeholder: "\\Seen", separator: " " },
    summary: "IMAP flags to set on an uploaded message.",
    detail: "IMAP-only — e.g. marking an appended message as already read.",
    order: 11050,
  },

  // ══ telnet ═════════════════════════════════════════════════════════════════
  {
    id: "telnetOption",
    short: "-t",
    long: "--telnet-option",
    group: "telnet",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "TTYPE=vt100", separator: " " },
    summary: "Option to pass to curl's telnet support.",
    detail: "Real curl allows this repeated for several options; only one is modeled here.",
    order: 12000,
  },

  // ══ tftp ═══════════════════════════════════════════════════════════════════
  {
    id: "tftpBlksize",
    long: "--tftp-blksize",
    group: "tftp",
    kind: "number",
    arg: { placeholder: "512", min: 8, max: 65464, separator: " " },
    summary: "TFTP BLKSIZE option to request.",
    detail: "Larger blocks reduce round trips on a low-latency network; the server may ignore the request.",
    order: 13000,
  },
  {
    id: "tftpNoOptions",
    long: "--tftp-no-options",
    group: "tftp",
    kind: "boolean",
    conflictsWith: ["tftpBlksize"],
    summary: "Do not send any TFTP options at all.",
    detail: "For a server that rejects the (RFC 2347) options extension outright.",
    order: 13010,
  },

  // ══ output ═════════════════════════════════════════════════════════════════
  {
    id: "output",
    short: "-o",
    long: "--output",
    group: "output",
    kind: "path",
    preferShort: true,
    conflictsWith: ["remoteName", "outNull"],
    arg: { placeholder: "result.json", separator: " " },
    summary: "Write the response body to this file instead of stdout.",
    detail: "Use #1, #2, ... as placeholders that expand from URL globs when fetching several URLs at once.",
    order: 14000,
  },
  {
    id: "remoteName",
    short: "-O",
    long: "--remote-name",
    group: "output",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["output", "outNull"],
    summary: "Save the response using the remote file's own name.",
    detail: "Takes the filename from the last path segment of the URL.",
    order: 14010,
  },
  {
    id: "remoteNameAll",
    long: "--remote-name-all",
    group: "output",
    kind: "boolean",
    requires: ["remoteName"],
    summary: "Apply --remote-name's naming to every URL on the line, not just ones after -O.",
    detail: "Without this, a bare URL after the last -O falls back to stdout instead of being named too.",
    order: 14020,
  },
  {
    id: "outputDir",
    long: "--output-dir",
    group: "output",
    kind: "path",
    arg: { placeholder: "downloads/", separator: " " },
    summary: "Directory to save -o/-O output into.",
    detail: "Applied as a prefix to whatever filename -o/-O would otherwise use.",
    order: 14030,
  },
  {
    id: "outNull",
    long: "--out-null",
    group: "output",
    kind: "boolean",
    conflictsWith: ["output", "remoteName"],
    summary: "Discard the response body entirely.",
    detail: "For when only headers, status, or side effects (e.g. a POST's server-side action) matter.",
    order: 14040,
  },
  {
    id: "remoteTime",
    short: "-R",
    long: "--remote-time",
    group: "output",
    kind: "boolean",
    preferShort: true,
    summary: "Set the local file's timestamp from the remote Last-Modified header, if present.",
    detail: "Makes the downloaded file's mtime match the server's, instead of the moment it was saved.",
    order: 14050,
  },
  {
    id: "skipExisting",
    long: "--skip-existing",
    group: "output",
    kind: "boolean",
    summary: "Skip the download if the local output file already exists.",
    detail: "Useful when re-running a batch of downloads and only wanting to fetch what is missing.",
    order: 14060,
  },
  {
    id: "noClobber",
    long: "--no-clobber",
    group: "output",
    kind: "boolean",
    summary: "Append a numeric suffix rather than overwrite an existing output file.",
    detail: "result.json becomes result.json.1, .2, and so on rather than replacing what's already there.",
    order: 14070,
  },
  {
    id: "remoteHeaderName",
    short: "-J",
    long: "--remote-header-name",
    group: "output",
    kind: "boolean",
    preferShort: true,
    requires: ["remoteName"],
    summary: "Prefer the filename from a Content-Disposition response header over the URL.",
    detail: "Only takes effect together with -O/--remote-name.",
    order: 14080,
  },
  {
    id: "showHeaders",
    short: "-i",
    long: "--show-headers",
    group: "output",
    kind: "boolean",
    preferShort: true,
    summary: "Include the response headers in the output, before the body.",
    detail: "Unlike -I/--head, the body is still fetched and shown too.",
    order: 14090,
  },
  {
    id: "dumpHeader",
    short: "-D",
    long: "--dump-header",
    group: "output",
    kind: "path",
    preferShort: true,
    arg: { placeholder: "headers.txt", separator: " " },
    summary: "Write the received response headers to this file.",
    detail: "Keeps headers out of the main output stream entirely, saved separately instead.",
    order: 14100,
  },
  {
    id: "writeOut",
    short: "-w",
    long: "--write-out",
    group: "output",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "%{http_code}\\n", separator: " " },
    summary: "Print this format string after the transfer completes.",
    detail: "curl's own variable-substitution syntax, e.g. %{http_code}, %{time_total}, %{size_download} — the standard way to script against curl's own metadata.",
    order: 14110,
  },
  {
    id: "silent",
    short: "-s",
    long: "--silent",
    group: "output",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["verbose"],
    summary: "Suppress the progress meter and error messages.",
    detail: "Pair with -S/--show-error to keep error messages while still hiding the progress meter.",
    order: 14120,
  },
  {
    id: "showError",
    short: "-S",
    long: "--show-error",
    group: "output",
    kind: "boolean",
    preferShort: true,
    requires: ["silent"],
    summary: "Show an error message even when --silent is set.",
    detail: "Only meaningful together with -s.",
    order: 14130,
  },
  {
    id: "verbose",
    short: "-v",
    long: "--verbose",
    group: "output",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["silent"],
    summary: "Show the full request and response, including headers.",
    detail: "The first thing to reach for when a request is not doing what you expect.",
    order: 14140,
  },
  {
    id: "noProgressMeter",
    long: "--no-progress-meter",
    group: "output",
    kind: "boolean",
    conflictsWith: ["progressBar"],
    summary: "Hide the progress meter, but keep error messages and any -v/-w output.",
    detail: "A middle ground between the default meter and full -s silence.",
    order: 14150,
  },
  {
    id: "progressBar",
    short: "-#",
    long: "--progress-bar",
    group: "output",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["noProgressMeter"],
    summary: "Show progress as a simple bar instead of the default meter.",
    detail: "More readable in a narrow terminal or a log file than the default stats line.",
    order: 14160,
  },
  {
    id: "styledOutput",
    long: "--styled-output",
    group: "output",
    kind: "boolean",
    summary: "Enable bold/colored styling for -I/--head output where the terminal supports it.",
    detail: "Cosmetic only.",
    order: 14170,
  },
  {
    id: "noBuffer",
    short: "-N",
    long: "--no-buffer",
    group: "output",
    kind: "boolean",
    preferShort: true,
    summary: "Disable buffering of the output stream.",
    detail: "Makes output appear immediately, at some cost to throughput — useful when piping to something that reacts to each line as it arrives.",
    order: 14180,
  },
  {
    id: "stderrFile",
    long: "--stderr",
    group: "output",
    kind: "path",
    arg: { placeholder: "curl.log", separator: " " },
    summary: "Redirect curl's own error/progress output to this file.",
    detail: "Use - to explicitly mean stdout.",
    order: 14190,
  },
  {
    id: "trace",
    long: "--trace",
    group: "output",
    kind: "path",
    conflictsWith: ["traceAscii"],
    arg: { placeholder: "trace.txt", separator: " " },
    summary: "Write a full protocol trace, including a hex dump, to this file.",
    detail: "The most detailed diagnostic curl offers — everything sent and received, byte for byte.",
    order: 14200,
  },
  {
    id: "traceAscii",
    long: "--trace-ascii",
    group: "output",
    kind: "path",
    conflictsWith: ["trace"],
    arg: { placeholder: "trace.txt", separator: " " },
    summary: "Like --trace, but without the hex dump — ASCII only.",
    detail: "Easier to read when the traffic is genuinely text-based (HTTP headers, plain-text protocols).",
    order: 14210,
  },
  {
    id: "traceIds",
    long: "--trace-ids",
    group: "output",
    kind: "boolean",
    requires: ["trace"],
    summary: "Include the transfer and connection IDs in the trace.",
    detail: "Distinguishes lines from different transfers when running several in parallel.",
    order: 14220,
  },
  {
    id: "traceTime",
    long: "--trace-time",
    group: "output",
    kind: "boolean",
    requires: ["trace"],
    summary: "Add timestamps to trace/verbose output.",
    detail: "Makes it possible to measure how long each stage of the transfer actually took.",
    order: 14230,
  },
  {
    id: "traceConfig",
    long: "--trace-config",
    group: "output",
    kind: "text",
    requires: ["trace"],
    arg: { placeholder: "all", separator: " " },
    summary: "Select which detail categories appear in the trace/verbose output.",
    detail: "Comma-separated component names, e.g. tcp,tls,http — narrows a busy trace down to what you actually care about.",
    order: 14240,
  },

  // ══ timeouts, retries, rate limiting ═══════════════════════════════════════
  {
    id: "connectTimeout",
    long: "--connect-timeout",
    group: "timeout",
    kind: "number",
    arg: { placeholder: "10", min: 0, unit: "s", separator: " " },
    summary: "Maximum time allowed just to establish the connection.",
    detail: "Fails fast on an unreachable host instead of waiting for the OS's own TCP timeout.",
    order: 15000,
  },
  {
    id: "maxTime",
    short: "-m",
    long: "--max-time",
    group: "timeout",
    kind: "number",
    preferShort: true,
    arg: { placeholder: "30", min: 0, unit: "s", separator: " " },
    summary: "Maximum time allowed for the whole operation, connection included.",
    detail: "The overall deadline — unlike --connect-timeout, this also bounds how long the actual transfer may run.",
    order: 15010,
  },
  {
    id: "expect100Timeout",
    long: "--expect100-timeout",
    group: "timeout",
    kind: "number",
    arg: { placeholder: "1", min: 0, unit: "s", separator: " " },
    summary: "How long to wait for a 100-continue response before sending the body anyway.",
    detail: "Only relevant to requests with an Expect: 100-continue header, which curl adds automatically for a sufficiently large body.",
    order: 15020,
  },
  {
    id: "retry",
    long: "--retry",
    group: "timeout",
    kind: "number",
    arg: { placeholder: "3", min: 0, separator: " " },
    summary: "Retry a failed transfer this many times.",
    detail: "Only retries transient-looking failures (timeouts, some 5xx responses) — not every kind of error.",
    order: 15030,
  },
  {
    id: "retryDelay",
    long: "--retry-delay",
    group: "timeout",
    kind: "number",
    requires: ["retry"],
    arg: { placeholder: "0", min: 0, unit: "s", separator: " " },
    summary: "Fixed delay between retries, overriding curl's default backoff.",
    detail: "Without this, curl waits progressively longer between attempts on its own.",
    order: 15040,
  },
  {
    id: "retryMaxTime",
    long: "--retry-max-time",
    group: "timeout",
    kind: "number",
    requires: ["retry"],
    arg: { placeholder: "60", min: 0, unit: "s", separator: " " },
    summary: "Stop retrying once this much total time has passed.",
    detail: "A ceiling on top of --retry's count, so a long chain of quick retries cannot run indefinitely.",
    order: 15050,
  },
  {
    id: "retryConnrefused",
    long: "--retry-connrefused",
    group: "timeout",
    kind: "boolean",
    requires: ["retry"],
    summary: "Also retry when the connection is actively refused.",
    detail: "curl does not treat connection-refused as retryable by default — for a service that is briefly restarting, this makes it retryable.",
    order: 15060,
  },
  {
    id: "retryAllErrors",
    long: "--retry-all-errors",
    group: "timeout",
    kind: "boolean",
    requires: ["retry"],
    danger: "caution",
    summary: "Retry on any error, not just curl's normal transient-failure list.",
    detail: "Broadens retries to include errors that are not actually transient — can retry something that will never succeed.",
    order: 15070,
  },
  {
    id: "rate",
    long: "--rate",
    group: "timeout",
    kind: "text",
    arg: { placeholder: "2/s", separator: " " },
    summary: "Maximum request rate — this many transfers per second/minute/hour.",
    detail: "e.g. 10/m for 10 per minute. Spaces curl's own requests out to stay under a rate limit.",
    order: 15080,
  },
  {
    id: "limitRate",
    long: "--limit-rate",
    group: "timeout",
    kind: "text",
    arg: { placeholder: "1M", separator: " " },
    summary: "Cap transfer speed, upload and download.",
    detail: "Accepts a plain byte count or a suffix like K/M/G.",
    order: 15090,
  },
  {
    id: "speedLimit",
    short: "-Y",
    long: "--speed-limit",
    group: "timeout",
    kind: "number",
    preferShort: true,
    arg: { placeholder: "1000", min: 0, unit: "bytes/s", separator: " " },
    summary: "Abort if transfer speed stays below this for too long.",
    detail: "Pair with -y/--speed-time to set how long is \"too long\" — default is 30 seconds.",
    order: 15100,
  },
  {
    id: "speedTime",
    short: "-y",
    long: "--speed-time",
    group: "timeout",
    kind: "number",
    preferShort: true,
    requires: ["speedLimit"],
    arg: { placeholder: "30", min: 1, unit: "s", separator: " " },
    summary: "How long the speed may stay below --speed-limit before aborting.",
    detail: "Only meaningful together with -Y/--speed-limit.",
    order: 15110,
  },
  {
    id: "maxFilesize",
    long: "--max-filesize",
    group: "timeout",
    kind: "number",
    arg: { placeholder: "10000000", min: 0, unit: "bytes", separator: " " },
    summary: "Abort the download if the remote file is larger than this.",
    detail: "Checked against the size the server reports before the transfer, where the protocol makes that available.",
    order: 15120,
  },

  // ══ transfer range, resume, remote metadata ════════════════════════════════
  {
    id: "range",
    short: "-r",
    long: "--range",
    group: "transfer",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "0-499", separator: " " },
    summary: "Fetch only this byte range of the resource.",
    detail: "start-end, start- for \"to the end\", or -end for \"the last N bytes\". Server support (Range:) is required.",
    order: 16000,
  },
  {
    id: "continueAt",
    short: "-C",
    long: "--continue-at",
    group: "transfer",
    kind: "text",
    preferShort: true,
    arg: { placeholder: "-", separator: " " },
    summary: "Resume a transfer from this byte offset.",
    detail: "Use - to have curl figure out the offset itself from the local output file's current size.",
    order: 16010,
  },
];

export const CATALOGUE = createFlagCatalogue<FlagGroup>(FLAGS);
export const getFlag = CATALOGUE.getFlag;
export const requireFlag = CATALOGUE.requireFlag;
export const flagsInGroup = CATALOGUE.flagsInGroup;
export const flagsInArgvOrder = CATALOGUE.flagsInArgvOrder;
export function flagLabel(flag: FlagDef): string {
  return flagLabelGeneric(flag);
}

/** Sanity check for the catalogue itself, exercised by the test suite. */
export function validateCatalogue(): string[] {
  return validateCatalogueGeneric(FLAGS);
}
