import {
  createFlagCatalogue,
  flagLabel as flagLabelGeneric,
  type DangerLevel,
  type FlagArgSpec,
  type FlagDef as FlagDefGeneric,
  type FlagEnumOption,
  type FlagKind,
} from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type { DangerLevel, FlagArgSpec, FlagEnumOption, FlagKind };
export type FlagDef = FlagDefGeneric<FlagGroup>;

export const FLAGS: readonly FlagDef[] = [
  {
    id: "strip",
    // Number/text/path-kind flags always render via `long` (the shared
    // engine's `renderFlag` doesn't consult `preferShort` for these kinds,
    // only for booleans/enums), so `long` is set to the short spelling
    // directly — same precedent as `@cmdgen/mount`'s own "-t".
    long: "-p",
    group: "options",
    kind: "number",
    arg: { placeholder: "1", separator: " " },
    summary: "Strip this many leading path components from file names named in the patch.",
    detail: "Patches generated by git or diff -up often carry a/ and b/ prefixes — strip 1 removes exactly one such component so the names match real files.",
    order: 10,
  },
  {
    id: "reverse",
    short: "-R",
    long: "--reverse",
    group: "options",
    kind: "boolean",
    preferShort: true,
    danger: "caution",
    summary: "Assume the patch has old and new files swapped, and un-apply it.",
    detail: "Easy to invoke by mistake when what you actually meant to do was apply the patch normally — double-check before running.",
    order: 20,
  },
  {
    id: "backup",
    short: "-b",
    long: "--backup",
    group: "options",
    kind: "boolean",
    preferShort: true,
    summary: "Keep a copy of every file before patching it.",
    detail: "Each modified file gets an .orig backup alongside it — the safer choice when you haven't fully verified a patch.",
    order: 30,
  },
  {
    id: "dryRun",
    long: "--dry-run",
    group: "options",
    kind: "boolean",
    summary: "Show what would happen without changing any files.",
    detail: "The safest way to check whether a patch applies cleanly before committing to it for real.",
    order: 40,
  },
  {
    id: "input",
    // Same `long`-only rendering limitation as "strip" above.
    long: "-i",
    group: "options",
    kind: "path",
    arg: { placeholder: "changes.patch", separator: " " },
    summary: "Read the patch from this file instead of the positional patch file or stdin.",
    detail: "Equivalent to giving the patch file as the final operand — this app renders whichever one is set, not both.",
    order: 50,
  },
] as const;

export const CATALOGUE = createFlagCatalogue<FlagGroup>(FLAGS);

export const getFlag = CATALOGUE.getFlag;
export const requireFlag = CATALOGUE.requireFlag;
export const flagsInGroup = CATALOGUE.flagsInGroup;
export const flagsInArgvOrder = CATALOGUE.flagsInArgvOrder;

export function flagLabel(flag: FlagDef): string {
  return flagLabelGeneric(flag);
}
