import {
  createFlagCatalogue,
  flagLabel as flagLabelGeneric,
  isAvailableOn as isAvailableOnGeneric,
  type DangerLevel,
  type FlagArgSpec,
  type FlagDef as FlagDefGeneric,
  type FlagEnumOption,
  type FlagKind,
} from "@cmdgen/engine";
import type { FlagGroup } from "./groups";
import type { GrepPlatform } from "../spec";

export type { DangerLevel, FlagArgSpec, FlagEnumOption, FlagKind };
export type FlagDef = FlagDefGeneric<FlagGroup>;

export const FLAGS: readonly FlagDef[] = [
  // ── POSIX (grep) ──────────────────────────────────────────────────────────
  {
    id: "ignoreCase",
    short: "-i",
    long: "--ignore-case",
    group: "matching",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    summary: "Match regardless of case.",
    detail: "\"TODO\" matches \"todo\", \"ToDo\", and every other capitalization.",
    order: 10,
  },
  {
    id: "invertMatch",
    short: "-v",
    long: "--invert-match",
    group: "matching",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    summary: "Print lines that do NOT match, instead of lines that do.",
    detail: "Useful for filtering out noise, e.g. grep -v '^#' to drop comment lines.",
    order: 20,
  },
  {
    id: "wordRegexp",
    short: "-w",
    long: "--word-regexp",
    group: "matching",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    summary: "Only match whole words.",
    detail: "\"cat\" won't match inside \"category\" — the match must be bounded by non-word characters or the start/end of the line.",
    order: 30,
  },
  {
    id: "lineRegexp",
    short: "-x",
    long: "--line-regexp",
    group: "matching",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    summary: "Only match whole lines.",
    detail: "The pattern must match the entire line, not just some part of it.",
    order: 40,
  },
  {
    id: "extendedRegexp",
    short: "-E",
    long: "--extended-regexp",
    group: "matching",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    conflictsWith: ["fixedStrings"],
    summary: "Interpret the pattern as an extended regular expression (ERE).",
    detail: "Lets you use +, ?, |, and () without backslash-escaping them, unlike basic regular expressions.",
    order: 50,
  },
  {
    id: "fixedStrings",
    short: "-F",
    long: "--fixed-strings",
    group: "matching",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    conflictsWith: ["extendedRegexp"],
    summary: "Treat the pattern as a literal string, not a regular expression.",
    detail: "Every regex metacharacter in the pattern is matched literally — the same behavior fgrep gives.",
    order: 60,
  },
  {
    id: "recursive",
    short: "-r",
    long: "--recursive",
    group: "matching",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    summary: "Search every file under each given directory, recursively.",
    detail: "Turns a file-search command into a directory-tree search.",
    order: 70,
  },
  {
    id: "count",
    short: "-c",
    long: "--count",
    group: "output",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    summary: "Print only a count of matching lines per file, not the lines themselves.",
    detail: "One number per file when multiple files are given, not a single total.",
    order: 10,
  },
  {
    id: "lineNumber",
    short: "-n",
    long: "--line-number",
    group: "output",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    summary: "Prefix each matching line with its line number.",
    detail: "Line numbers restart at 1 for each file when multiple files are given.",
    order: 20,
  },
  {
    id: "filesWithMatches",
    short: "-l",
    long: "--files-with-matches",
    group: "output",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    conflictsWith: ["filesWithoutMatch"],
    summary: "Print only the names of files containing a match.",
    detail: "Stops scanning each file at its first match — faster than printing every match when only the filename matters.",
    order: 30,
  },
  {
    id: "filesWithoutMatch",
    short: "-L",
    long: "--files-without-match",
    group: "output",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    conflictsWith: ["filesWithMatches"],
    summary: "Print only the names of files containing no match.",
    detail: "The inverse of --files-with-matches — useful for finding files that are missing something expected.",
    order: 40,
  },
  {
    id: "onlyMatching",
    short: "-o",
    long: "--only-matching",
    group: "output",
    kind: "boolean",
    preferShort: true,
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    summary: "Print only the matched part of each line, not the whole line.",
    detail: "Each match prints on its own line, even if several matches occur on the same input line.",
    order: 50,
  },
  {
    id: "context",
    short: "-C",
    long: "-C",
    group: "output",
    kind: "number",
    availableOn: ["linux", "mac", "windows-cygwin", "windows-msys", "windows-wsl"],
    arg: { placeholder: "3", separator: " " },
    summary: "Print N lines of context before and after each match.",
    detail: "Separate -A (after) and -B (before) counts exist too, for when the two sides shouldn't match — not modeled here since -C covers the common symmetric case.",
    order: 60,
  },

  // ── cmd.exe (findstr) ─────────────────────────────────────────────────────
  {
    id: "ignoreCaseCmd",
    long: "/I",
    group: "matching",
    kind: "boolean",
    availableOn: ["windows-cmd"],
    summary: "Match regardless of case.",
    detail: "\"TODO\" matches \"todo\" and every other capitalization.",
    order: 10,
  },
  {
    id: "invertMatchCmd",
    long: "/V",
    group: "matching",
    kind: "boolean",
    availableOn: ["windows-cmd"],
    summary: "Print lines that do NOT match.",
    detail: "Useful for filtering out noise, e.g. findstr /V \"^#\" to drop comment lines.",
    order: 20,
  },
  {
    id: "regexCmd",
    long: "/R",
    group: "matching",
    kind: "boolean",
    availableOn: ["windows-cmd"],
    summary: "Treat the pattern as a regular expression.",
    detail: "findstr's own regex dialect, not grep's — narrower, with different escaping rules. Without this, the pattern is matched literally.",
    order: 30,
  },
  {
    id: "recursiveCmd",
    long: "/S",
    group: "matching",
    kind: "boolean",
    availableOn: ["windows-cmd"],
    summary: "Search matching files in the current directory and all subdirectories.",
    detail: "Turns a file-search command into a directory-tree search — the same idea as grep's own -r.",
    order: 40,
  },
  {
    id: "lineNumberCmd",
    long: "/N",
    group: "output",
    kind: "boolean",
    availableOn: ["windows-cmd"],
    summary: "Prefix each matching line with its line number.",
    detail: "Line numbers restart at 1 for each file when multiple files are given.",
    order: 10,
  },

  // ── PowerShell (Select-String) ───────────────────────────────────────────
  {
    id: "caseSensitivePs",
    long: "-CaseSensitive",
    group: "matching",
    kind: "boolean",
    availableOn: ["windows-powershell"],
    summary: "Match case-sensitively.",
    detail: "Select-String is case-INSENSITIVE by default — the opposite of grep's own default — so this is the closest equivalent to grep's plain, flag-less behavior, not to grep -i.",
    order: 10,
  },
  {
    id: "notMatchPs",
    long: "-NotMatch",
    group: "matching",
    kind: "boolean",
    availableOn: ["windows-powershell"],
    summary: "Return lines that do NOT match, instead of lines that do.",
    detail: "The equivalent of grep -v.",
    order: 20,
  },
  {
    id: "simpleMatchPs",
    long: "-SimpleMatch",
    group: "matching",
    kind: "boolean",
    availableOn: ["windows-powershell"],
    summary: "Treat the pattern as a literal string, not a regular expression.",
    detail: "Every regex metacharacter in the pattern is matched literally — the equivalent of grep -F.",
    order: 30,
  },
  {
    id: "contextPs",
    long: "-Context",
    group: "output",
    kind: "number",
    availableOn: ["windows-powershell"],
    arg: { placeholder: "3", separator: " " },
    summary: "Print N lines of context before and after each match.",
    detail: "The equivalent of grep -C.",
    order: 10,
  },
] as const;

export const CATALOGUE = createFlagCatalogue<FlagGroup>(FLAGS);

export const getFlag = CATALOGUE.getFlag;
export const requireFlag = CATALOGUE.requireFlag;
export const flagsInGroup = CATALOGUE.flagsInGroup;
export const flagsInArgvOrder = CATALOGUE.flagsInArgvOrder;

export function isAvailableOn(flag: FlagDef, platform: GrepPlatform): boolean {
  return isAvailableOnGeneric(flag, platform);
}

export function flagLabel(flag: FlagDef): string {
  return flagLabelGeneric(flag);
}
