import {
  createFlagCatalogue,
  flagLabel as flagLabelGeneric,
  isAvailableOn as isAvailableOnGeneric,
  type DangerLevel,
  type FlagArgSpec,
  type FlagDef as FlagDefGeneric,
  type FlagEnumOption,
  type FlagKind,
} from "@cmdgen/engine";
import type { FlagGroup } from "./groups";
import type { TarVariant } from "../spec";

export type { DangerLevel, FlagArgSpec, FlagEnumOption, FlagKind };
export type FlagDef = FlagDefGeneric<FlagGroup>;

/**
 * The complete option surface of GNU tar's `--help`, plus bsdtar's documented
 * set, in one catalogue.
 *
 * Three conventions carry most of the weight:
 *
 * 1. `availableOn` is the GNU-vs-bsdtar split. Absent = present in both. Where
 *    the two spell the same idea differently they get separate entries; where
 *    they spell *different* ideas with the same letter — `-n`, `-s`, `-L`, `-W`
 *    — separate entries are mandatory, since one variant's token would silently
 *    mean something else in the other.
 *
 * 2. A `--foo` / `--no-foo` pair is ONE tri-state enum, not two booleans. tar
 *    has ~15 such pairs; as booleans they would let the form express
 *    "--acls --no-acls" simultaneously, which is meaningless. An enum makes the
 *    mutual exclusion structural rather than something lint has to police.
 *
 * 3. `order` is globally unique (`flagsInArgvOrder()` sorts the whole array)
 *    and load-bearing: anything below `ARCHIVE_ORDER` (see ../argv.ts)
 *    renders before `-f <archive>`, which is what produces tar's universal
 *    bundled form `tar -czvf archive.tar.gz`.
 */
export const FLAGS: readonly FlagDef[] = [
  // ══ compression — renders before -f so it bundles into -czf ═══════════════
  // The compressor sets genuinely differ, so this is two gated enums rather
  // than one shared list: GNU has lzip/lzop, bsdtar has lz4/lrzip/grzip and
  // the uuencode/b64encode text wrappers.
  {
    // `long` is a UI grouping label, not a real tar option — the actual tokens
    // come from each option's `renders`. Same shape as cd's `--symlink-mode`.
    id: "compressionGnu",
    long: "--compress-with",
    group: "compression",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "None — plain .tar", renders: "" },
      { value: "gzip", label: "gzip (-z) — .tar.gz / .tgz", renders: "-z" },
      { value: "bzip2", label: "bzip2 (-j) — .tar.bz2", renders: "-j" },
      { value: "xz", label: "xz (-J) — .tar.xz", renders: "-J" },
      { value: "zstd", label: "zstd (--zstd) — .tar.zst", renders: "--zstd" },
      { value: "lzma", label: "lzma (--lzma) — .tar.lzma", renders: "--lzma" },
      { value: "lzip", label: "lzip (--lzip) — .tar.lz", renders: "--lzip" },
      { value: "lzop", label: "lzop (--lzop) — .tar.lzo", renders: "--lzop" },
      { value: "compress", label: "compress (-Z) — .tar.Z, legacy", renders: "-Z" },
    ],
    summary: "Which compressor to filter the archive through.",
    detail:
      "tar does not compress by itself — it pipes the archive through an external compressor. gzip is the safe default; xz compresses hardest; zstd is far faster than xz at similar ratios.",
    order: 100,
  },
  {
    id: "compressionBsd",
    long: "--compress-with",
    group: "compression",
    kind: "enum",
    availableOn: ["bsd"],
    options: [
      { value: "none", label: "None — plain .tar", renders: "" },
      { value: "gzip", label: "gzip (-z) — .tar.gz / .tgz", renders: "-z" },
      { value: "bzip2", label: "bzip2 (-j) — .tar.bz2", renders: "-j" },
      { value: "xz", label: "xz (-J) — .tar.xz", renders: "-J" },
      { value: "zstd", label: "zstd (--zstd) — .tar.zst", renders: "--zstd" },
      { value: "lzma", label: "lzma (--lzma) — .tar.lzma", renders: "--lzma" },
      { value: "lz4", label: "lz4 (--lz4) — .tar.lz4", renders: "--lz4" },
      { value: "lrzip", label: "lrzip (--lrzip) — .tar.lrz", renders: "--lrzip" },
      { value: "grzip", label: "grzip (--grzip)", renders: "--grzip" },
      { value: "compress", label: "compress (-Z) — .tar.Z, legacy", renders: "-Z" },
      { value: "uuencode", label: "uuencode (--uuencode) — text-safe", renders: "--uuencode" },
      { value: "b64encode", label: "base64 (--b64encode) — text-safe", renders: "--b64encode" },
    ],
    summary: "Which compressor or encoder to filter the archive through.",
    detail:
      "bsdtar's filter list differs from GNU tar's: it adds lz4, lrzip and grzip, plus uuencode/b64encode for producing an archive that survives text-only transport. It has no lzip or lzop.",
    order: 105,
  },
  {
    id: "autoCompress",
    short: "-a",
    long: "-a",
    group: "compression",
    kind: "boolean",
    preferShort: true,
    summary: "Pick the compressor from the archive's file extension.",
    detail: "Naming the archive .tar.zst then uses zstd, making the choice above redundant. Only meaningful when creating.",
    order: 110,
  },
  {
    id: "noAutoCompress",
    long: "--no-auto-compress",
    group: "compression",
    kind: "boolean",
    conflictsWith: ["autoCompress"],
    availableOn: ["gnu"],
    summary: "Ignore the archive suffix when choosing a compressor.",
    detail: "Cancels -a, e.g. to write an uncompressed archive that is nonetheless named .tar.gz.",
    order: 115,
  },
  {
    id: "useCompressProgram",
    long: "-I",
    group: "compression",
    kind: "text",
    danger: "caution",
    availableOn: ["gnu"],
    arg: { placeholder: "zstd -19 -T0", separator: " " },
    summary: "Filter through an arbitrary program.",
    detail:
      "Runs the named program (which must accept -d to decompress). The usual reason is passing compressor options, e.g. -I 'zstd -19 -T0'. Note that this executes whatever you name here.",
    order: 120,
  },
  {
    id: "useCompressProgramBsd",
    long: "--use-compress-program",
    group: "compression",
    kind: "text",
    danger: "caution",
    availableOn: ["bsd"],
    arg: { placeholder: "zstd -19 -T0", separator: " " },
    summary: "Filter through an arbitrary program.",
    detail: "bsdtar spells this out in full — it has no -I short form. Executes whatever you name here.",
    order: 125,
  },

  // ══ verbose — also pre-archive, purely so it joins the -czvf bundle ════════
  {
    id: "verbose",
    short: "-v",
    long: "-v",
    group: "output",
    kind: "boolean",
    preferShort: true,
    summary: "List each file as it is processed.",
    detail:
      "Given twice on GNU tar (-vv) it also prints a long listing while extracting. With -O this output interleaves with the file data.",
    order: 200,
  },

  // ══ selection: what goes in ═══════════════════════════════════════════════
  {
    id: "addFile",
    long: "--add-file",
    group: "selection",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: "-weird-name", separator: "=" },
    summary: "Add a file whose name would otherwise look like an option.",
    detail: "The escape hatch for archiving a file literally called something like \"-x\".",
    order: 300,
  },
  {
    id: "excludeFrom",
    short: "-X",
    long: "-X",
    group: "selection",
    kind: "path",
    preferShort: true,
    arg: { placeholder: ".tarignore", separator: " " },
    summary: "Read exclude patterns from a file, one per line.",
    detail: "Easier to version-control than a long list of --exclude flags.",
    order: 310,
  },
  {
    id: "filesFrom",
    short: "-T",
    long: "-T",
    group: "selection",
    kind: "path",
    preferShort: true,
    arg: { placeholder: "filelist.txt", separator: " " },
    summary: "Read the list of files to process from a file.",
    detail: "Use - to read the list from stdin, e.g. from find. Pair with --null when names may contain newlines.",
    order: 320,
  },
  {
    id: "nullSeparated",
    long: "--null",
    group: "selection",
    kind: "boolean",
    requires: ["filesFrom"],
    summary: "The -T list is NUL-separated, not newline-separated.",
    detail: "The correct pairing for `find ... -print0 | tar -T -`, which survives filenames containing newlines.",
    order: 330,
  },
  {
    id: "noNull",
    long: "--no-null",
    group: "selection",
    kind: "boolean",
    conflictsWith: ["nullSeparated"],
    availableOn: ["gnu"],
    summary: "Cancel a previous --null.",
    detail: "Only useful when options come from TAR_OPTIONS or a wrapper script that already set --null.",
    order: 335,
  },
  {
    id: "verbatimFilesFrom",
    long: "--verbatim-files-from",
    group: "selection",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default (-T treats leading dashes as options)", renders: "" },
      { value: "verbatim", label: "Verbatim — no escape or option handling", renders: "--verbatim-files-from" },
      { value: "options", label: "Explicitly allow options in the list", renders: "--no-verbatim-files-from" },
    ],
    summary: "Whether names in the -T list may be options.",
    detail: "--verbatim-files-from is the safe choice for a machine-generated list, where a filename starting with - is a filename.",
    order: 340,
  },
  {
    id: "unquoteMode",
    long: "--unquote",
    group: "selection",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default (unquote)", renders: "" },
      { value: "unquote", label: "Unquote input names", renders: "--unquote" },
      { value: "no-unquote", label: "Do not unquote input names", renders: "--no-unquote" },
    ],
    summary: "Whether escape sequences in input names are interpreted.",
    detail: "--no-unquote is what you want when a real filename genuinely contains a backslash.",
    order: 350,
  },
  {
    id: "recursionMode",
    long: "--recursion",
    group: "selection",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default (recurse)", renders: "" },
      { value: "recursion", label: "Recurse into directories", renders: "--recursion" },
      { value: "no-recursion", label: "Do not descend into directories", renders: "--no-recursion" },
    ],
    summary: "Whether directories are descended into.",
    detail: "--no-recursion archives a named directory as a single entry without its contents.",
    order: 360,
  },
  {
    id: "noRecursionBsd",
    short: "-n",
    long: "-n",
    group: "selection",
    kind: "boolean",
    preferShort: true,
    availableOn: ["bsd"],
    summary: "Do not descend into directories.",
    detail:
      "bsdtar's spelling of --no-recursion. GNU tar's -n means something entirely different (--seek), which is why these are separate entries.",
    order: 370,
  },
  {
    id: "excludeVcs",
    long: "--exclude-vcs",
    group: "selection",
    kind: "boolean",
    summary: "Skip version-control directories (.git, .svn, .hg, ...).",
    detail: "The single most useful exclusion when archiving a source tree for distribution.",
    order: 380,
  },
  {
    id: "excludeVcsIgnores",
    long: "--exclude-vcs-ignores",
    group: "selection",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Also honour .gitignore and friends.",
    detail: "Reads the VCS ignore files it finds and applies them as exclude patterns.",
    order: 385,
  },
  {
    id: "excludeCaches",
    long: "--exclude-caches",
    group: "selection",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "Do not treat CACHEDIR.TAG specially", renders: "" },
      { value: "caches", label: "Skip contents, keep the tag file", renders: "--exclude-caches" },
      { value: "caches-all", label: "Skip the directory entirely", renders: "--exclude-caches-all" },
      { value: "caches-under", label: "Skip everything under it", renders: "--exclude-caches-under" },
    ],
    summary: "How to handle directories tagged CACHEDIR.TAG.",
    detail:
      "Respects the Cache Directory Tagging Standard so build and browser caches drop out of backups. The three variants differ only in whether the tag file and the directory entry itself survive.",
    order: 390,
  },
  {
    id: "excludeBackups",
    long: "--exclude-backups",
    group: "selection",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Skip editor backup and lock files (*~, .#*).",
    detail: "Keeps transient editor droppings out of an archive.",
    order: 400,
  },
  {
    id: "excludeTag",
    long: "--exclude-tag",
    group: "selection",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: "SKIP_BACKUP", separator: "=" },
    summary: "Skip the contents of directories containing this file.",
    detail: "Your own version of CACHEDIR.TAG. The tag file itself is still archived.",
    order: 410,
  },
  {
    id: "excludeTagAll",
    long: "--exclude-tag-all",
    group: "selection",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: "SKIP_BACKUP", separator: "=" },
    summary: "Skip directories containing this file entirely.",
    detail: "Unlike --exclude-tag, the tag file is not archived either.",
    order: 415,
  },
  {
    id: "excludeTagUnder",
    long: "--exclude-tag-under",
    group: "selection",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: "SKIP_BACKUP", separator: "=" },
    summary: "Skip everything under directories containing this file.",
    detail: "Keeps the directory entry but drops all of its contents.",
    order: 420,
  },
  {
    id: "excludeIgnore",
    long: "--exclude-ignore",
    group: "selection",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: ".tarignore", separator: "=" },
    summary: "Read per-directory exclude patterns from this file.",
    detail: "Like .gitignore but under your own filename, applied to the directory it sits in.",
    order: 425,
  },
  {
    id: "excludeIgnoreRecursive",
    long: "--exclude-ignore-recursive",
    group: "selection",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: ".tarignore", separator: "=" },
    summary: "Like --exclude-ignore, but also applies to subdirectories.",
    detail: "Closer to .gitignore semantics, where a rule reaches down the tree.",
    order: 430,
  },
  {
    id: "oneFileSystem",
    long: "--one-file-system",
    group: "selection",
    kind: "boolean",
    summary: "Stay on one filesystem — do not cross mount points.",
    detail: "Standard for whole-system backups, so /proc, /sys and network mounts do not get pulled in.",
    order: 440,
  },
  {
    id: "newer",
    short: "-N",
    long: "--newer",
    group: "selection",
    kind: "text",
    arg: { placeholder: "2026-01-01", separator: "=" },
    summary: "Only include files newer than this date (or than this file's mtime).",
    detail: "A snapshot-free incremental backup — but it also re-archives unchanged directories.",
    order: 450,
  },
  {
    id: "newerMtime",
    long: "--newer-mtime",
    group: "selection",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: "2026-01-01", separator: "=" },
    summary: "Like --newer, but compare only data modification time.",
    detail: "Ignores inode/ctime changes, so a permission change alone will not re-include a file.",
    order: 455,
  },
  {
    id: "newerThanBsd",
    long: "--newer-than",
    group: "selection",
    kind: "path",
    availableOn: ["bsd"],
    arg: { placeholder: "last-backup.marker", separator: " " },
    summary: "Only include files newer than this file.",
    detail: "bsdtar's file-relative form: touch a marker file after each backup and compare against it.",
    order: 460,
  },
  {
    id: "newerMtimeThanBsd",
    long: "--newer-mtime-than",
    group: "selection",
    kind: "path",
    availableOn: ["bsd"],
    arg: { placeholder: "last-backup.marker", separator: " " },
    summary: "Like --newer-than, comparing modification time only.",
    detail: "Ignores inode changes, so only real content edits re-include a file.",
    order: 465,
  },
  {
    id: "startingFile",
    short: "-K",
    long: "--starting-file",
    group: "selection",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: "path/in/archive", separator: "=" },
    summary: "Begin reading the archive at this member.",
    detail: "Resumes an interrupted extraction without re-processing everything before it.",
    order: 470,
  },
  {
    id: "nodumpBsd",
    long: "--nodump",
    group: "selection",
    kind: "boolean",
    availableOn: ["bsd"],
    summary: "Honour the nodump file flag.",
    detail: "Skips files marked nodump, a BSD filesystem flag meaning \"do not back this up\".",
    order: 475,
  },
  {
    id: "removeFiles",
    long: "--remove-files",
    group: "selection",
    kind: "boolean",
    danger: "destructive",
    availableOn: ["gnu"],
    summary: "Delete each file from disk after adding it to the archive.",
    detail:
      "The originals are gone once tar has written them. If the archive turns out to be corrupt or written somewhere unexpected, there is nothing to fall back to.",
    order: 480,
  },
  {
    id: "backup",
    long: "--backup",
    group: "selection",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "No backups", renders: "" },
      { value: "default", label: "Back up before removal (default control)", renders: "--backup" },
      { value: "numbered", label: "Numbered backups (file.~1~)", renders: "--backup=numbered" },
      { value: "existing", label: "Numbered if numbered exist, else simple", renders: "--backup=existing" },
      { value: "simple", label: "Simple backups (file~)", renders: "--backup=simple" },
    ],
    summary: "Back up files before they are replaced or removed.",
    detail: "The counterweight to --remove-files and --overwrite: keeps a copy of whatever was about to be destroyed.",
    order: 485,
  },
  {
    id: "backupSuffix",
    long: "--suffix",
    group: "selection",
    kind: "text",
    requires: ["backup"],
    availableOn: ["gnu"],
    arg: { placeholder: ".bak", separator: "=" },
    summary: "Override the simple-backup suffix (default ~).",
    detail: "Equivalent to setting SIMPLE_BACKUP_SUFFIX in the environment.",
    order: 490,
  },

  // ══ pattern matching ══════════════════════════════════════════════════════
  {
    id: "wildcardsMode",
    long: "--wildcards",
    group: "matching",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default (wildcards when excluding)", renders: "" },
      { value: "wildcards", label: "Treat patterns as shell wildcards", renders: "--wildcards" },
      { value: "no-wildcards", label: "Verbatim string matching", renders: "--no-wildcards" },
    ],
    summary: "Whether patterns are globs or literal strings.",
    detail:
      "Wildcards are the default for exclusion but not for member selection, so extracting '*.txt' from an archive needs --wildcards.",
    order: 500,
  },
  {
    id: "wildcardsSlashMode",
    long: "--wildcards-match-slash",
    group: "matching",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default", renders: "" },
      { value: "match", label: "Wildcards match '/'", renders: "--wildcards-match-slash" },
      { value: "no-match", label: "Wildcards do not match '/'", renders: "--no-wildcards-match-slash" },
    ],
    summary: "Whether * crosses directory separators.",
    detail: "With --no-wildcards-match-slash, 'a/*' matches only one level down rather than the whole subtree.",
    order: 510,
  },
  {
    id: "anchoredMode",
    long: "--anchored",
    group: "matching",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default (unanchored when excluding)", renders: "" },
      { value: "anchored", label: "Match from the start of the name", renders: "--anchored" },
      { value: "no-anchored", label: "Match after any '/'", renders: "--no-anchored" },
    ],
    summary: "Whether patterns must match from the beginning of a member name.",
    detail: "Unanchored is the exclusion default, which is usually broader than intended — --anchored narrows it.",
    order: 520,
  },
  {
    id: "ignoreCaseMode",
    long: "--ignore-case",
    group: "matching",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default (case sensitive)", renders: "" },
      { value: "ignore", label: "Ignore case", renders: "--ignore-case" },
      { value: "respect", label: "Case sensitive", renders: "--no-ignore-case" },
    ],
    summary: "Whether pattern matching is case-sensitive.",
    detail: "Applies to both include and exclude patterns.",
    order: 530,
  },

  // ══ operation modifiers ═══════════════════════════════════════════════════
  {
    id: "occurrence",
    long: "--occurrence",
    group: "modifiers",
    kind: "number",
    availableOn: ["gnu"],
    arg: { placeholder: "1", min: 1, separator: "=" },
    summary: "Act on only the Nth occurrence of each named member.",
    detail:
      "An archive can contain the same name several times (append/update do this). Valid only with --delete, --diff, --extract or --list, and only when members are named.",
    order: 600,
  },
  {
    id: "seekMode",
    long: "--seek",
    group: "modifiers",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "Let tar decide", renders: "" },
      { value: "seek", label: "Archive is seekable (-n)", renders: "-n" },
      { value: "no-seek", label: "Archive is not seekable", renders: "--no-seek" },
    ],
    summary: "Whether tar may skip rather than read through data.",
    detail:
      "Spelled -n in GNU tar — the same letter bsdtar uses for --norecurse, hence the separate entries here.",
    order: 610,
  },
  {
    id: "holeDetection",
    long: "--hole-detection",
    group: "modifiers",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "Let tar decide", renders: "" },
      { value: "seek", label: "seek — ask the filesystem", renders: "--hole-detection=seek" },
      { value: "raw", label: "raw — scan for zero blocks", renders: "--hole-detection=raw" },
    ],
    summary: "How to find holes in a sparse file.",
    detail: "seek is fast but needs filesystem support; raw always works but reads the whole file.",
    order: 620,
  },
  {
    id: "ignoreFailedRead",
    long: "--ignore-failed-read",
    group: "modifiers",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Do not fail the whole run on an unreadable file.",
    detail: "Common in system backups, where a few unreadable files are expected rather than fatal.",
    order: 630,
  },
  {
    id: "fastReadBsd",
    short: "-q",
    long: "--fast-read",
    group: "modifiers",
    kind: "boolean",
    preferShort: true,
    availableOn: ["bsd"],
    summary: "Stop after finding the named members.",
    detail: "Avoids reading the rest of a large archive once everything asked for has been found.",
    order: 640,
  },
  {
    id: "restrict",
    long: "--restrict",
    group: "modifiers",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Disable options that could be abused.",
    detail: "Intended for wrapper scripts that pass user-supplied options through to tar.",
    order: 650,
  },

  // ══ overwrite control ═════════════════════════════════════════════════════
  {
    id: "keepOldFiles",
    short: "-k",
    long: "-k",
    group: "overwrite",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["overwrite"],
    summary: "Never replace an existing file; report it as an error.",
    detail: "The safe default when extracting into a directory that already has contents.",
    order: 700,
  },
  {
    id: "skipOldFiles",
    long: "--skip-old-files",
    group: "overwrite",
    kind: "boolean",
    conflictsWith: ["overwrite"],
    availableOn: ["gnu"],
    summary: "Never replace an existing file; skip it silently.",
    detail: "Like -k but without the non-zero exit status, for when pre-existing files are expected.",
    order: 705,
  },
  {
    id: "keepNewerFiles",
    long: "--keep-newer-files",
    group: "overwrite",
    kind: "boolean",
    summary: "Do not replace a file that is newer than the archived copy.",
    detail: "Useful for restoring a backup over a tree that has since been partly updated.",
    order: 710,
  },
  {
    id: "overwrite",
    long: "--overwrite",
    group: "overwrite",
    kind: "boolean",
    danger: "caution",
    conflictsWith: ["keepOldFiles"],
    availableOn: ["gnu"],
    summary: "Replace existing files unconditionally.",
    detail: "Truncates and rewrites in place rather than unlinking first, which matters for hard links and open files.",
    order: 715,
  },
  {
    id: "overwriteDirMode",
    long: "--overwrite-dir",
    group: "overwrite",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default (overwrite dir metadata)", renders: "" },
      { value: "overwrite", label: "Overwrite existing directory metadata", renders: "--overwrite-dir" },
      { value: "keep", label: "Keep existing directory metadata", renders: "--no-overwrite-dir" },
    ],
    summary: "Whether directories already on disk have their metadata replaced.",
    detail: "--no-overwrite-dir stops an archive from loosening the permissions of a directory you already have.",
    order: 720,
  },
  {
    id: "keepDirectorySymlink",
    long: "--keep-directory-symlink",
    group: "overwrite",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Follow an existing symlink-to-directory instead of replacing it.",
    detail: "Without this, tar replaces the symlink with a real directory.",
    order: 725,
  },
  {
    id: "oneTopLevel",
    long: "--one-top-level",
    group: "overwrite",
    kind: "boolean",
    conflictsWith: ["oneTopLevelDir"],
    availableOn: ["gnu"],
    summary: "Extract everything into a single new subdirectory.",
    detail:
      "The fix for a \"tar bomb\" — an archive whose members sit at the top level and scatter across your current directory. The directory is named after the archive.",
    order: 730,
  },
  {
    id: "oneTopLevelDir",
    long: "--one-top-level",
    group: "overwrite",
    kind: "path",
    conflictsWith: ["oneTopLevel"],
    availableOn: ["gnu"],
    arg: { placeholder: "unpacked", separator: "=" },
    summary: "Extract everything into this named subdirectory.",
    detail: "The same containment as --one-top-level, but you choose the directory name instead of inheriting the archive's.",
    order: 735,
  },
  {
    id: "recursiveUnlink",
    long: "--recursive-unlink",
    group: "overwrite",
    kind: "boolean",
    danger: "destructive",
    availableOn: ["gnu"],
    summary: "Delete existing directory trees before extracting over them.",
    detail:
      "Empties a whole hierarchy first, so anything in the target directory that is not in the archive is destroyed rather than merged.",
    order: 740,
  },
  {
    id: "unlinkFirst",
    short: "-U",
    long: "-U",
    group: "overwrite",
    kind: "boolean",
    preferShort: true,
    danger: "caution",
    availableOn: ["gnu"],
    summary: "Delete each file before extracting over it.",
    detail: "Breaks hard links and existing file handles instead of overwriting in place.",
    order: 745,
  },
  {
    id: "verify",
    short: "-W",
    long: "--verify",
    group: "overwrite",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Re-read the archive after writing it and compare.",
    detail:
      "Roughly doubles the work but catches a bad disk or truncated write. Note bsdtar's -W means --options instead, so these are separate entries.",
    order: 750,
  },
  {
    id: "optionsBsd",
    short: "-W",
    long: "--options",
    group: "overwrite",
    kind: "text",
    availableOn: ["bsd"],
    arg: { placeholder: "zstd:compression-level=19", separator: " " },
    summary: "Set format- and filter-specific options.",
    detail:
      "bsdtar's general tuning knob, e.g. per-compressor levels or format quirks. GNU tar's -W is --verify, an unrelated thing.",
    order: 755,
  },
  {
    id: "safeWritesModeBsd",
    long: "--safe-writes",
    group: "overwrite",
    kind: "enum",
    availableOn: ["bsd"],
    options: [
      { value: "none", label: "bsdtar default", renders: "" },
      { value: "safe", label: "Replace files atomically", renders: "--safe-writes" },
      { value: "unsafe", label: "Write in place", renders: "--no-safe-writes" },
    ],
    summary: "Whether extraction replaces files atomically.",
    detail: "Atomic replacement means a reader never sees a half-written file, at the cost of breaking hard links.",
    order: 760,
  },

  // ══ output stream ═════════════════════════════════════════════════════════
  {
    id: "toStdout",
    short: "-O",
    long: "-O",
    group: "outputStream",
    kind: "boolean",
    preferShort: true,
    summary: "Write member contents to stdout instead of to disk.",
    detail: "Turns tar into a viewer: extract one member and pipe it somewhere without touching the filesystem.",
    order: 800,
  },
  {
    id: "toCommand",
    long: "--to-command",
    group: "outputStream",
    kind: "text",
    danger: "caution",
    availableOn: ["gnu"],
    arg: { placeholder: "sha256sum", separator: "=" },
    summary: "Pipe each extracted member into a program.",
    detail:
      "tar runs the command once per member with the data on its stdin. This executes whatever you name here, once per file in the archive.",
    order: 810,
  },
  {
    id: "commandErrorMode",
    long: "--ignore-command-error",
    group: "outputStream",
    kind: "enum",
    requires: ["toCommand"],
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default", renders: "" },
      { value: "ignore", label: "Ignore the child's exit code", renders: "--ignore-command-error" },
      { value: "fail", label: "Treat a non-zero exit as an error", renders: "--no-ignore-command-error" },
    ],
    summary: "Whether --to-command failures fail the run.",
    detail: "Only meaningful alongside --to-command.",
    order: 820,
  },

  // ══ ownership & metadata ══════════════════════════════════════════════════
  {
    id: "preservePermissions",
    short: "-p",
    long: "-p",
    group: "attributes",
    kind: "boolean",
    preferShort: true,
    summary: "Restore the exact permissions recorded in the archive.",
    detail: "Already the default for root; for an ordinary user the umask is applied unless this is set.",
    order: 850,
  },
  {
    id: "noSamePermissions",
    long: "--no-same-permissions",
    group: "attributes",
    kind: "boolean",
    conflictsWith: ["preservePermissions"],
    availableOn: ["gnu"],
    summary: "Apply your umask to extracted permissions.",
    detail: "The counterpart to -p, and the default for non-root users.",
    order: 855,
  },
  {
    id: "sameOwner",
    long: "--same-owner",
    group: "attributes",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Restore the original owner and group.",
    detail: "Requires root. The default for root; ignored with a warning otherwise.",
    order: 860,
  },
  {
    id: "noSameOwner",
    long: "--no-same-owner",
    group: "attributes",
    kind: "boolean",
    conflictsWith: ["sameOwner"],
    summary: "Own extracted files yourself.",
    detail: "The default for ordinary users. Worth setting explicitly in scripts that may run as root.",
    order: 865,
  },
  {
    id: "numericOwner",
    long: "--numeric-owner",
    group: "attributes",
    kind: "boolean",
    summary: "Store/restore numeric UIDs and GIDs rather than names.",
    detail: "Essential for reproducible archives and for restoring onto a machine with a different user database.",
    order: 870,
  },
  {
    id: "owner",
    long: "--owner",
    group: "attributes",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: "0", separator: "=" },
    summary: "Force this owner for every file added.",
    detail: "Use --owner=0 --group=0 so an archive does not leak your local account names.",
    order: 875,
  },
  {
    id: "group",
    long: "--group",
    group: "attributes",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: "0", separator: "=" },
    summary: "Force this group for every file added.",
    detail: "The companion to --owner.",
    order: 880,
  },
  {
    id: "ownerMap",
    long: "--owner-map",
    group: "attributes",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: "uidmap.txt", separator: "=" },
    summary: "Remap owner UIDs and names from a file.",
    detail: "For rewriting ownership wholesale when moving archives between machines.",
    order: 885,
  },
  {
    id: "groupMap",
    long: "--group-map",
    group: "attributes",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: "gidmap.txt", separator: "=" },
    summary: "Remap group GIDs and names from a file.",
    detail: "The group counterpart to --owner-map.",
    order: 890,
  },
  {
    id: "uidBsd",
    long: "--uid",
    group: "attributes",
    kind: "number",
    availableOn: ["bsd"],
    arg: { placeholder: "0", min: 0, separator: " " },
    summary: "Force this numeric owner for every file added.",
    detail: "bsdtar splits GNU's --owner into numeric (--uid) and name (--uname) forms.",
    order: 892,
  },
  {
    id: "unameBsd",
    long: "--uname",
    group: "attributes",
    kind: "text",
    availableOn: ["bsd"],
    arg: { placeholder: "root", separator: " " },
    summary: "Force this owner name for every file added.",
    detail: "The name half of bsdtar's owner override.",
    order: 894,
  },
  {
    id: "gidBsd",
    long: "--gid",
    group: "attributes",
    kind: "number",
    availableOn: ["bsd"],
    arg: { placeholder: "0", min: 0, separator: " " },
    summary: "Force this numeric group for every file added.",
    detail: "The group counterpart to --uid.",
    order: 896,
  },
  {
    id: "gnameBsd",
    long: "--gname",
    group: "attributes",
    kind: "text",
    availableOn: ["bsd"],
    arg: { placeholder: "wheel", separator: " " },
    summary: "Force this group name for every file added.",
    detail: "The group counterpart to --uname.",
    order: 898,
  },
  {
    id: "modeOverride",
    long: "--mode",
    group: "attributes",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: "go-w", separator: "=" },
    summary: "Force these permissions for every file added.",
    detail: "Takes a symbolic chmod expression, e.g. go-w to strip group/other write bits as you archive.",
    order: 900,
  },
  {
    id: "mtime",
    long: "--mtime",
    group: "attributes",
    kind: "text",
    arg: { placeholder: "@0", separator: "=" },
    summary: "Force this modification time for every file added.",
    detail:
      "The key to byte-identical rebuilds: a fixed --mtime removes timestamps as a source of nondeterminism. Accepts a date or @SECONDS.",
    order: 905,
  },
  {
    id: "clampMtime",
    long: "--clamp-mtime",
    group: "attributes",
    kind: "boolean",
    requires: ["mtime"],
    summary: "Only apply --mtime to files that are newer than it.",
    detail: "Preserves genuinely older timestamps while capping everything recent, keeping archives stable over time.",
    order: 910,
  },
  {
    id: "touch",
    short: "-m",
    long: "-m",
    group: "attributes",
    kind: "boolean",
    preferShort: true,
    summary: "Do not restore modification times; use now instead.",
    detail: "Makes every extracted file look freshly written, which is what some build systems want.",
    order: 915,
  },
  {
    id: "delayDirectoryRestoreMode",
    long: "--delay-directory-restore",
    group: "attributes",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default", renders: "" },
      { value: "delay", label: "Set directory times/modes at the end", renders: "--delay-directory-restore" },
      { value: "immediate", label: "Set them as directories are created", renders: "--no-delay-directory-restore" },
    ],
    summary: "When directory timestamps and permissions are applied.",
    detail:
      "Delaying is necessary when an archive stores a read-only directory before the files that go inside it.",
    order: 920,
  },
  {
    id: "atimePreserve",
    long: "--atime-preserve",
    group: "attributes",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "Let archiving update access times", renders: "" },
      { value: "default", label: "Restore atime after reading", renders: "--atime-preserve" },
      { value: "replace", label: "replace — restore afterwards", renders: "--atime-preserve=replace" },
      { value: "system", label: "system — never set atime at all", renders: "--atime-preserve=system" },
    ],
    summary: "Do not let archiving update access times.",
    detail:
      "Reading a file normally bumps its atime, so a backup leaves fingerprints. 'system' avoids touching it in the first place; 'replace' puts it back afterwards.",
    order: 930,
  },
  {
    id: "sortOrder",
    long: "--sort",
    group: "attributes",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "Directory order (default)", renders: "" },
      { value: "name", label: "By name — reproducible", renders: "--sort=name" },
      { value: "inode", label: "By inode — fastest on spinning disks", renders: "--sort=inode" },
    ],
    summary: "Order in which directory entries are archived.",
    detail:
      "--sort=name is the other half of a reproducible archive: without it, member order follows the filesystem's iteration order.",
    order: 940,
  },
  {
    id: "sameOrder",
    // -s is declared (it is a real GNU alias, also spelled --preserve-order)
    // but `preferShort` is deliberately left off so this always RENDERS as
    // --same-order: bsdtar's -s is a substitution expression, and emitting the
    // bare letter would be the one token most likely to be misread if someone
    // moved the command between implementations.
    short: "-s",
    long: "--same-order",
    group: "attributes",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "The member arguments are listed in archive order.",
    detail:
      "Lets GNU tar process a huge archive in one pass. Also spelled -s and --preserve-order; rendered in long form here because bsdtar's -s means something completely different.",
    order: 950,
  },
  {
    id: "macMetadataModeBsd",
    long: "--mac-metadata",
    group: "attributes",
    kind: "enum",
    availableOn: ["bsd"],
    options: [
      { value: "none", label: "bsdtar default", renders: "" },
      { value: "store", label: "Store macOS metadata", renders: "--mac-metadata" },
      { value: "skip", label: "Skip macOS metadata", renders: "--no-mac-metadata" },
    ],
    summary: "Whether macOS extended metadata is archived.",
    detail:
      "Preserves resource forks and Finder info, at the cost of ._ AppleDouble entries that look like junk on other systems.",
    order: 960,
  },
  {
    id: "fflagsModeBsd",
    long: "--fflags",
    group: "attributes",
    kind: "enum",
    availableOn: ["bsd"],
    options: [
      { value: "none", label: "bsdtar default", renders: "" },
      { value: "store", label: "Store platform file flags", renders: "--fflags" },
      { value: "skip", label: "Ignore platform file flags", renders: "--no-fflags" },
    ],
    summary: "Whether BSD/macOS file flags are archived.",
    detail: "Covers flags like uchg (immutable) and nodump.",
    order: 970,
  },

  // ══ extended attributes ═══════════════════════════════════════════════════
  {
    id: "aclsMode",
    long: "--acls",
    group: "xattrs",
    kind: "enum",
    options: [
      { value: "none", label: "Default for this tar", renders: "" },
      { value: "enable", label: "Store and restore POSIX ACLs", renders: "--acls" },
      { value: "disable", label: "Ignore POSIX ACLs", renders: "--no-acls" },
    ],
    summary: "Whether POSIX ACLs are carried.",
    detail: "Requires a format that can hold them (pax) — ustar and v7 cannot.",
    order: 1000,
  },
  {
    id: "xattrsMode",
    long: "--xattrs",
    group: "xattrs",
    kind: "enum",
    options: [
      { value: "none", label: "Default for this tar", renders: "" },
      { value: "enable", label: "Store and restore extended attributes", renders: "--xattrs" },
      { value: "disable", label: "Ignore extended attributes", renders: "--no-xattrs" },
    ],
    summary: "Whether extended attributes are carried.",
    detail: "Needed to round-trip capabilities and user.* metadata. Implies the pax format.",
    order: 1010,
  },
  {
    id: "selinuxMode",
    long: "--selinux",
    group: "xattrs",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default", renders: "" },
      { value: "enable", label: "Store and restore SELinux contexts", renders: "--selinux" },
      { value: "disable", label: "Ignore SELinux contexts", renders: "--no-selinux" },
    ],
    summary: "Whether SELinux security contexts are carried.",
    detail: "Only meaningful on an SELinux-enabled system.",
    order: 1020,
  },
  {
    id: "xattrsInclude",
    long: "--xattrs-include",
    group: "xattrs",
    kind: "text",
    requires: ["xattrsMode"],
    availableOn: ["gnu"],
    arg: { placeholder: "user.*", separator: "=" },
    summary: "Only carry xattr keys matching this mask.",
    detail: "Narrows what --xattrs picks up, e.g. to user.* while dropping security.*.",
    order: 1030,
  },
  {
    id: "xattrsExclude",
    long: "--xattrs-exclude",
    group: "xattrs",
    kind: "text",
    requires: ["xattrsMode"],
    availableOn: ["gnu"],
    arg: { placeholder: "security.*", separator: "=" },
    summary: "Skip xattr keys matching this mask.",
    detail: "The inverse of --xattrs-include.",
    order: 1040,
  },

  // ══ archive format ════════════════════════════════════════════════════════
  {
    id: "formatGnu",
    short: "-H",
    long: "--format",
    group: "format",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      // "none" (not "default") is the engine's inactive-enum sentinel — see
      // `isFlagActive`. Naming it anything else makes an untouched dropdown
      // count as a set flag in lint and diagnostics.
      { value: "none", label: "GNU tar default (gnu)", renders: "" },
      { value: "gnu", label: "gnu — GNU tar 1.13+", renders: "--format=gnu" },
      { value: "oldgnu", label: "oldgnu — GNU tar ≤ 1.12", renders: "--format=oldgnu" },
      { value: "pax", label: "pax / posix — POSIX 1003.1-2001", renders: "--format=pax" },
      { value: "ustar", label: "ustar — POSIX 1003.1-1988", renders: "--format=ustar" },
      { value: "v7", label: "v7 — ancient V7 tar", renders: "--format=v7" },
    ],
    summary: "Container format to write.",
    detail:
      "pax is the most capable and most portable modern choice — no path-length or UID limits, and it can carry xattrs. ustar is maximally compatible but caps paths at 255 bytes.",
    order: 1100,
  },
  {
    id: "formatBsd",
    long: "--format",
    group: "format",
    kind: "enum",
    availableOn: ["bsd"],
    options: [
      { value: "none", label: "bsdtar default (pax restricted)", renders: "" },
      { value: "pax", label: "pax — POSIX 1003.1-2001", renders: "--format=pax" },
      { value: "ustar", label: "ustar — POSIX 1003.1-1988", renders: "--format=ustar" },
      { value: "cpio", label: "cpio", renders: "--format=cpio" },
      { value: "shar", label: "shar — shell archive", renders: "--format=shar" },
      { value: "v7tar", label: "v7tar — ancient V7 tar", renders: "--format=v7tar" },
      { value: "mtree", label: "mtree — a manifest, not an archive", renders: "--format=mtree" },
      { value: "zip", label: "zip", renders: "--format=zip" },
      { value: "7zip", label: "7zip", renders: "--format=7zip" },
    ],
    summary: "Container format to write.",
    detail:
      "bsdtar's format list genuinely differs: libarchive can also write cpio, shar, zip, 7zip and mtree manifests, and has no gnu/oldgnu. Its default is \"pax restricted\", which uses ustar headers and only reaches for pax extensions when a file needs them.",
    order: 1105,
  },
  {
    id: "posixFormat",
    long: "--posix",
    group: "format",
    kind: "boolean",
    conflictsWith: ["formatGnu"],
    availableOn: ["gnu"],
    summary: "Shorthand for --format=posix (pax).",
    detail: "Identical to selecting pax above; kept because scripts in the wild use this spelling.",
    order: 1110,
  },
  {
    id: "oldArchive",
    long: "--old-archive",
    group: "format",
    kind: "boolean",
    conflictsWith: ["formatGnu"],
    availableOn: ["gnu"],
    summary: "Shorthand for --format=v7 (also spelled --portability).",
    detail: "The oldest, least capable format. Only for feeding genuinely ancient tools.",
    order: 1115,
  },
  {
    id: "label",
    short: "-V",
    long: "--label",
    group: "format",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: "backup-2026-07", separator: "=" },
    summary: "Write a volume label into the archive.",
    detail: "When listing or extracting, the same option instead matches the label as a glob pattern.",
    order: 1120,
  },
  {
    id: "paxOption",
    long: "--pax-option",
    group: "format",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: "delete=atime,delete=ctime", separator: "=" },
    summary: "Set or delete pax keywords.",
    detail: "Mostly used for reproducibility — deleting atime/ctime drops timestamps the format would otherwise record.",
    order: 1130,
  },

  // ══ paths, links & name rewriting ═════════════════════════════════════════
  {
    id: "dereference",
    short: "-h",
    long: "-h",
    group: "paths",
    kind: "boolean",
    preferShort: true,
    availableOn: ["gnu"],
    summary: "Follow symlinks and archive what they point at.",
    detail:
      "Without this, tar stores the link itself. With it, an archive can balloon in size or loop through a symlink cycle.",
    order: 1200,
  },
  {
    id: "dereferenceBsd",
    short: "-L",
    long: "-L",
    group: "paths",
    kind: "boolean",
    preferShort: true,
    availableOn: ["bsd"],
    summary: "Follow all symlinks and archive what they point at.",
    detail:
      "bsdtar spells dereference -L. GNU tar's -L is --tape-length and takes a number, so these must stay separate entries.",
    order: 1205,
  },
  {
    id: "followCmdlineSymlinksBsd",
    short: "-H",
    long: "-H",
    group: "paths",
    kind: "boolean",
    preferShort: true,
    availableOn: ["bsd"],
    summary: "Follow only the symlinks named on the command line.",
    detail: "A middle ground between storing links and following every one of them.",
    order: 1210,
  },
  {
    id: "hardDereference",
    long: "--hard-dereference",
    group: "paths",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Store hard-linked files as separate copies.",
    detail: "Loses the link relationship and duplicates data, but produces an archive that is simpler to consume.",
    order: 1215,
  },
  {
    id: "absoluteNames",
    short: "-P",
    long: "-P",
    group: "paths",
    kind: "boolean",
    preferShort: true,
    danger: "caution",
    summary: "Do not strip leading '/' from member names.",
    detail:
      "tar normally removes leading slashes precisely so extraction can never write outside the current directory. This turns that protection off in both directions.",
    order: 1220,
  },
  {
    id: "transform",
    long: "--transform",
    group: "paths",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: "s,^,prefix/,", separator: "=" },
    summary: "Rewrite member names with a sed expression.",
    detail: "The general form of --strip-components: anything sed's s/// can express, e.g. adding a prefix on create.",
    order: 1230,
  },
  {
    id: "substituteBsd",
    short: "-s",
    long: "-s",
    group: "paths",
    kind: "text",
    preferShort: true,
    availableOn: ["bsd"],
    arg: { placeholder: "/old/new/", separator: " " },
    summary: "Rewrite member names with a substitution expression.",
    detail:
      "bsdtar's equivalent of --transform. GNU tar's -s means --same-order instead, which is why these are separate entries.",
    order: 1240,
  },
  {
    id: "stripComponents",
    long: "--strip-components",
    group: "paths",
    kind: "number",
    arg: { placeholder: "1", min: 0, separator: "=" },
    summary: "Drop this many leading path components from each member name.",
    detail:
      "The usual way to unwrap an archive that has everything under one versioned directory: --strip-components=1 extracts its contents directly.",
    order: 1250,
  },
  {
    id: "chrootBsd",
    long: "--chroot",
    group: "paths",
    kind: "boolean",
    availableOn: ["bsd"],
    summary: "chroot() into the target directory before extracting.",
    detail: "A hard containment guarantee that no member can escape the extraction directory. Requires privileges.",
    order: 1260,
  },

  // ══ informative output ════════════════════════════════════════════════════
  {
    id: "totals",
    long: "--totals",
    group: "output",
    kind: "boolean",
    conflictsWith: ["totalsSignal"],
    summary: "Print the total bytes written when finished.",
    detail: "A cheap sanity check that the archive is roughly the size you expected.",
    order: 1300,
  },
  {
    id: "totalsSignal",
    long: "--totals",
    group: "output",
    kind: "enum",
    conflictsWith: ["totals"],
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "Off", renders: "" },
      { value: "SIGHUP", label: "On SIGHUP", renders: "--totals=SIGHUP" },
      { value: "SIGQUIT", label: "On SIGQUIT", renders: "--totals=SIGQUIT" },
      { value: "SIGINT", label: "On SIGINT", renders: "--totals=SIGINT" },
      { value: "SIGUSR1", label: "On SIGUSR1", renders: "--totals=SIGUSR1" },
      { value: "SIGUSR2", label: "On SIGUSR2", renders: "--totals=SIGUSR2" },
    ],
    summary: "Print running totals when this signal arrives.",
    detail: "Turns a long-running tar into something you can poll: kill -USR1 the process and it reports progress.",
    order: 1305,
  },
  {
    id: "checkpoint",
    long: "--checkpoint",
    group: "output",
    kind: "number",
    availableOn: ["gnu"],
    arg: { placeholder: "1000", min: 1, separator: "=" },
    summary: "Print a progress message every N records.",
    detail: "The closest thing GNU tar has to a progress bar. Bare --checkpoint would default to 10.",
    order: 1310,
  },
  {
    id: "checkpointAction",
    long: "--checkpoint-action",
    group: "output",
    kind: "text",
    danger: "caution",
    requires: ["checkpoint"],
    availableOn: ["gnu"],
    arg: { placeholder: "echo=Reached %u", separator: "=" },
    summary: "Run an action at each checkpoint.",
    detail:
      "Actions include echo, dot, ttyout, sleep and exec. The exec form runs an arbitrary program, so treat this as executable input.",
    order: 1315,
  },
  {
    id: "blockNumber",
    short: "-R",
    long: "-R",
    group: "output",
    kind: "boolean",
    preferShort: true,
    availableOn: ["gnu"],
    summary: "Show the archive block number with each message.",
    detail: "Mainly a debugging aid for locating where a damaged archive goes wrong.",
    order: 1320,
  },
  {
    id: "checkLinks",
    short: "-l",
    long: "--check-links",
    group: "output",
    kind: "boolean",
    summary: "Warn if not all links to a file were archived.",
    detail: "Catches a hard-linked file that is only partly represented because its siblings were excluded.",
    order: 1330,
  },
  {
    id: "showTransformedNames",
    long: "--show-transformed-names",
    group: "output",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Report names after --transform / --strip-components.",
    detail: "Shows what will actually land on disk rather than what the archive says.",
    order: 1340,
  },
  {
    id: "showOmittedDirs",
    long: "--show-omitted-dirs",
    group: "output",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "List directories that did not match the selection.",
    detail: "Useful for debugging why an expected file never appeared.",
    order: 1345,
  },
  {
    id: "showDefaults",
    long: "--show-defaults",
    group: "output",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Print this tar's compiled-in defaults and exit.",
    detail: "Reports the default format, blocking factor and rmt/rsh commands for the build you are running.",
    order: 1350,
  },
  {
    id: "showSnapshotFieldRanges",
    long: "--show-snapshot-field-ranges",
    group: "output",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Print valid ranges for snapshot-file fields and exit.",
    detail: "A diagnostic for hand-inspecting incremental snapshot files.",
    order: 1355,
  },
  {
    id: "fullTime",
    long: "--full-time",
    group: "output",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Print timestamps at full resolution.",
    detail: "Listings normally round to the minute.",
    order: 1360,
  },
  {
    id: "utc",
    long: "--utc",
    group: "output",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Print times in UTC.",
    detail: "Makes listings comparable across machines in different time zones.",
    order: 1365,
  },
  {
    id: "indexFile",
    long: "--index-file",
    group: "output",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: "listing.txt", separator: "=" },
    summary: "Send verbose output to a file instead of stderr.",
    detail: "The way to keep -v's listing when stdout is already carrying the archive or member data.",
    order: 1370,
  },
  {
    id: "quotingStyle",
    long: "--quoting-style",
    group: "output",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default (escape)", renders: "" },
      { value: "literal", label: "literal — no quoting at all", renders: "--quoting-style=literal" },
      { value: "shell", label: "shell", renders: "--quoting-style=shell" },
      { value: "shell-always", label: "shell-always", renders: "--quoting-style=shell-always" },
      { value: "shell-escape", label: "shell-escape", renders: "--quoting-style=shell-escape" },
      { value: "shell-escape-always", label: "shell-escape-always", renders: "--quoting-style=shell-escape-always" },
      { value: "c", label: "c — C string literal", renders: "--quoting-style=c" },
      { value: "c-maybe", label: "c-maybe", renders: "--quoting-style=c-maybe" },
      { value: "escape", label: "escape", renders: "--quoting-style=escape" },
      { value: "locale", label: "locale", renders: "--quoting-style=locale" },
      { value: "clocale", label: "clocale", renders: "--quoting-style=clocale" },
    ],
    summary: "How names are quoted in tar's own output.",
    detail:
      "Affects only what tar prints, never what it stores. 'literal' is what you want when piping a listing into another tool.",
    order: 1380,
  },
  {
    id: "quoteChars",
    long: "--quote-chars",
    group: "output",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: " ", separator: "=" },
    summary: "Additionally quote these characters in output.",
    detail: "Refines the chosen --quoting-style.",
    order: 1385,
  },
  {
    id: "noQuoteChars",
    long: "--no-quote-chars",
    group: "output",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: " ", separator: "=" },
    summary: "Stop quoting these characters in output.",
    detail: "The inverse of --quote-chars.",
    order: 1390,
  },
  {
    id: "interactive",
    short: "-w",
    long: "-w",
    group: "output",
    kind: "boolean",
    preferShort: true,
    summary: "Ask for confirmation before every action.",
    detail: "Present in both implementations, and the cheapest brake available when a command looks risky.",
    order: 1400,
  },
  {
    id: "warningKeyword",
    long: "--warning",
    group: "output",
    kind: "text",
    availableOn: ["gnu"],
    arg: { placeholder: "no-file-changed", separator: "=" },
    summary: "Enable or suppress a named warning class.",
    detail: "Prefix a keyword with no- to silence it, e.g. --warning=no-file-changed in a live backup.",
    order: 1410,
  },
  {
    id: "versionInfo",
    long: "--version",
    group: "output",
    kind: "boolean",
    summary: "Print the tar version and exit.",
    detail: "The quickest way to find out which implementation and version you actually have in front of you.",
    order: 1420,
  },

  // ══ incremental backups (GNU) ═════════════════════════════════════════════
  {
    id: "listedIncremental",
    short: "-g",
    long: "-g",
    group: "incremental",
    kind: "path",
    preferShort: true,
    availableOn: ["gnu"],
    arg: { placeholder: "backup.snar", separator: " " },
    summary: "Use a snapshot file for a GNU incremental backup.",
    detail:
      "tar records directory state in the snapshot and archives only what changed since. The snapshot is as important as the archives — losing it means the chain cannot be extended.",
    order: 1500,
  },
  {
    id: "level",
    long: "--level",
    group: "incremental",
    kind: "number",
    requires: ["listedIncremental"],
    availableOn: ["gnu"],
    arg: { placeholder: "0", min: 0, separator: "=" },
    summary: "Dump level for the incremental archive.",
    detail: "--level=0 forces a full backup and resets the snapshot; omitting it continues the chain.",
    order: 1510,
  },
  {
    id: "incrementalOld",
    short: "-G",
    long: "-G",
    group: "incremental",
    kind: "boolean",
    preferShort: true,
    availableOn: ["gnu"],
    summary: "Old GNU-format incremental backup.",
    detail: "Superseded by -g. Present for reading archives produced by very old tools.",
    order: 1520,
  },
  {
    id: "checkDeviceMode",
    long: "--check-device",
    group: "incremental",
    kind: "enum",
    availableOn: ["gnu"],
    options: [
      { value: "none", label: "GNU tar default (check)", renders: "" },
      { value: "check", label: "Check device numbers", renders: "--check-device" },
      { value: "no-check", label: "Ignore device numbers", renders: "--no-check-device" },
    ],
    summary: "Whether device numbers are compared for incremental backups.",
    detail:
      "--no-check-device avoids a spurious full re-dump when a filesystem's device number changes across reboots, which is common with LVM and virtual disks.",
    order: 1530,
  },
  {
    id: "sparse",
    short: "-S",
    long: "-S",
    group: "incremental",
    kind: "boolean",
    preferShort: true,
    availableOn: ["gnu"],
    summary: "Store sparse files efficiently.",
    detail: "Detects holes rather than writing megabytes of zeros — important for VM images and database files.",
    order: 1540,
  },
  {
    id: "sparseVersion",
    long: "--sparse-version",
    group: "incremental",
    kind: "text",
    requires: ["sparse"],
    availableOn: ["gnu"],
    arg: { placeholder: "1.0", separator: "=" },
    summary: "Which sparse-format version to use.",
    detail: "Newer versions describe holes more precisely at the cost of needing a newer tar to read them.",
    order: 1550,
  },
  {
    id: "readSparseModeBsd",
    long: "--read-sparse",
    group: "incremental",
    kind: "enum",
    availableOn: ["bsd"],
    options: [
      { value: "none", label: "bsdtar default", renders: "" },
      { value: "read", label: "Detect holes in sparse files", renders: "--read-sparse" },
      { value: "no-read", label: "Read sparse files as solid data", renders: "--no-read-sparse" },
    ],
    summary: "Whether sparse files are detected while reading.",
    detail: "bsdtar's counterpart to GNU's -S.",
    order: 1560,
  },

  // ══ blocking & devices ════════════════════════════════════════════════════
  {
    id: "blockingFactor",
    short: "-b",
    long: "-b",
    group: "device",
    kind: "number",
    preferShort: true,
    arg: { placeholder: "20", min: 1, separator: " " },
    summary: "Records per I/O block (× 512 bytes).",
    detail: "20 (10 KiB) is the historical default. Larger blocks helped tape drives; for files it rarely matters.",
    order: 1600,
  },
  {
    id: "recordSize",
    long: "--record-size",
    group: "device",
    kind: "number",
    conflictsWith: ["blockingFactor"],
    availableOn: ["gnu"],
    arg: { placeholder: "10240", min: 512, separator: "=" },
    summary: "Bytes per record — must be a multiple of 512.",
    detail: "The same knob as -b expressed in bytes rather than 512-byte units.",
    order: 1610,
  },
  {
    id: "readFullRecords",
    short: "-B",
    long: "-B",
    group: "device",
    kind: "boolean",
    preferShort: true,
    availableOn: ["gnu"],
    summary: "Reblock while reading, for pipes.",
    detail: "Handles short reads from a pipe, which 4.2BSD-era pipes needed and some network streams still do.",
    order: 1620,
  },
  {
    id: "ignoreZeros",
    short: "-i",
    long: "-i",
    group: "device",
    kind: "boolean",
    preferShort: true,
    summary: "Do not treat a block of zeros as end-of-archive.",
    detail:
      "Required to read a file made by concatenating several archives, which would otherwise appear to end at the first one.",
    order: 1630,
  },
  {
    id: "multiVolume",
    short: "-M",
    long: "-M",
    group: "device",
    kind: "boolean",
    preferShort: true,
    availableOn: ["gnu"],
    summary: "Create or read a multi-volume archive.",
    detail: "Splits one logical archive across several media, pairing with -L to say how much fits on each.",
    order: 1640,
  },
  {
    id: "tapeLength",
    short: "-L",
    long: "-L",
    group: "device",
    kind: "number",
    preferShort: true,
    requires: ["multiVolume"],
    availableOn: ["gnu"],
    arg: { placeholder: "4096", min: 1, separator: " " },
    summary: "Change volume after this many KiB.",
    detail: "Only meaningful with -M. Note bsdtar's -L is --dereference, an unrelated boolean.",
    order: 1650,
  },
  {
    id: "infoScript",
    short: "-F",
    long: "--info-script",
    group: "device",
    kind: "path",
    danger: "caution",
    availableOn: ["gnu"],
    arg: { placeholder: "next-volume.sh", separator: "=" },
    summary: "Run this script at the end of each volume (implies -M).",
    detail: "Executes the named script to swap media. Treat as executable input.",
    order: 1660,
  },
  {
    id: "volnoFile",
    long: "--volno-file",
    group: "device",
    kind: "path",
    availableOn: ["gnu"],
    arg: { placeholder: "volume.no", separator: "=" },
    summary: "Track the current volume number in this file.",
    detail: "Lets a multi-volume run resume knowing which volume it was on.",
    order: 1670,
  },
  {
    id: "forceLocal",
    long: "--force-local",
    group: "device",
    kind: "boolean",
    availableOn: ["gnu"],
    summary: "Treat the archive name as local even if it contains a colon.",
    detail:
      "Without this, GNU tar reads host:/path as a remote tape drive — which is exactly what a Windows path like C:\\backup.tar looks like.",
    order: 1680,
  },
  {
    id: "rmtCommand",
    long: "--rmt-command",
    group: "device",
    kind: "path",
    danger: "caution",
    availableOn: ["gnu"],
    arg: { placeholder: "/usr/sbin/rmt", separator: "=" },
    summary: "Use this rmt program instead of the compiled-in default.",
    detail: "For driving a remote tape drive. Executes the named program.",
    order: 1690,
  },
  {
    id: "rshCommand",
    long: "--rsh-command",
    group: "device",
    kind: "path",
    danger: "caution",
    availableOn: ["gnu"],
    arg: { placeholder: "/usr/bin/ssh", separator: "=" },
    summary: "Use this remote-shell program instead of rsh.",
    detail:
      "Almost always set to ssh, since the compiled-in default is still the unencrypted rsh. Executes the named program.",
    order: 1700,
  },

  // ══ compatibility ═════════════════════════════════════════════════════════
  {
    id: "compatO",
    short: "-o",
    long: "-o",
    group: "compat",
    kind: "boolean",
    preferShort: true,
    availableOn: ["gnu"],
    summary: "Mode-dependent legacy switch.",
    detail:
      "When creating it means --old-archive (v7 format); when extracting it means --no-same-owner. Two unrelated behaviours behind one letter — prefer naming the one you actually want.",
    order: 1800,
  },
] as const;

export const CATALOGUE = createFlagCatalogue<FlagGroup>(FLAGS);

export const getFlag = CATALOGUE.getFlag;
export const requireFlag = CATALOGUE.requireFlag;
export const flagsInGroup = CATALOGUE.flagsInGroup;
export const flagsInArgvOrder = CATALOGUE.flagsInArgvOrder;

export function isAvailableOn(flag: FlagDef, variant: TarVariant): boolean {
  return isAvailableOnGeneric(flag, variant);
}

export function flagLabel(flag: FlagDef): string {
  return flagLabelGeneric(flag);
}
