import {
  createFlagCatalogue,
  flagLabel as flagLabelGeneric,
  isUnavailable as isUnavailableGeneric,
  type DangerLevel,
  type FlagArgSpec,
  type FlagDef as FlagDefGeneric,
  type FlagEnumOption,
  type FlagKind,
} from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type { DangerLevel, FlagArgSpec, FlagEnumOption, FlagKind };
export type FlagDef = FlagDefGeneric<FlagGroup>;

export const FLAGS: readonly FlagDef[] = [
  // ── connection ────────────────────────────────────────────────────────────
  {
    id: "protectArgs",
    short: "-s",
    long: "-s",
    group: "connection",
    kind: "boolean",
    summary: "Invoke a subsystem instead of a shell (e.g. sftp).",
    detail: "Used internally by tools like sftp; rarely typed by hand.",
    order: 100,
  },
  {
    id: "strictHostKeyChecking",
    long: "-o StrictHostKeyChecking",
    group: "connection",
    kind: "enum",
    danger: "caution",
    options: [
      // "none" (not "unset") is the engine's inactive-enum sentinel — see
      // `isFlagActive`. Naming it anything else makes an untouched dropdown
      // count as a set flag in lint, diagnostics and enabledFlagIds.
      { value: "none", label: "Use ssh's own default", renders: "" },
      { value: "accept-new", label: "Accept new, reject changed", renders: "-o StrictHostKeyChecking=accept-new" },
      { value: "yes", label: "Reject unknown and changed", renders: "-o StrictHostKeyChecking=yes" },
      {
        value: "no",
        label: "Accept anything (dangerous)",
        renders: "-o StrictHostKeyChecking=no",
        summary: "Disables host key verification entirely — vulnerable to man-in-the-middle attacks.",
      },
    ],
    summary: "How to handle the remote host's key.",
    detail:
      "Left unset by default so ssh's own configuration decides. Setting it to \"no\" silently trusts any host claiming to be the target, which defeats the point of host key verification.",
    order: 110,
  },
  {
    id: "batchMode",
    long: "-o BatchMode=yes",
    group: "connection",
    kind: "boolean",
    summary: "Never prompt for a password or passphrase.",
    detail:
      "Correct for scripts and scheduled jobs. Fails immediately instead of hanging if key auth doesn't work, rather than waiting for input that will never come.",
    order: 120,
  },
  {
    id: "connectTimeout",
    long: "-o ConnectTimeout",
    group: "connection",
    kind: "number",
    arg: { placeholder: "10", unit: "seconds", min: 1, separator: "=" },
    summary: "Give up connecting after N seconds.",
    detail: "Prevents a script hanging forever against a host that never responds.",
    order: 130,
  },
  {
    id: "configFile",
    long: "-F",
    group: "connection",
    kind: "path",
    arg: { placeholder: "~/.ssh/config-work", separator: " " },
    summary: "Use an alternate ssh config file.",
    detail: "Points ssh at a specific config instead of the default ~/.ssh/config.",
    order: 140,
  },
  {
    id: "compression",
    short: "-C",
    long: "-C",
    group: "connection",
    kind: "boolean",
    preferShort: true,
    summary: "Compress data in transit.",
    detail: "Helps over slow links; pure overhead on a fast local network.",
    order: 150,
  },
  {
    id: "ipVersion",
    long: "-4/-6",
    group: "connection",
    kind: "enum",
    options: [
      { value: "none", label: "Either (let ssh/DNS decide)", renders: "" },
      { value: "ipv4", label: "IPv4 only (-4)", renders: "-4" },
      { value: "ipv6", label: "IPv6 only (-6)", renders: "-6" },
    ],
    summary: "Restrict the connection to one IP version.",
    detail: "Useful when a host resolves to both and one path is broken or firewalled.",
    order: 155,
  },
  {
    id: "bindInterface",
    short: "-B",
    long: "-B",
    group: "connection",
    kind: "text",
    arg: { placeholder: "eth0", separator: " " },
    summary: "Bind to this network interface before connecting.",
    detail: "Chooses which local NIC originates the connection on a multi-homed machine.",
    order: 160,
  },
  {
    id: "bindAddress",
    short: "-b",
    long: "-b",
    group: "connection",
    kind: "text",
    arg: { placeholder: "192.168.1.5", separator: " " },
    summary: "Bind to this local address before connecting.",
    detail: "The address counterpart to -B — picks the source address rather than the interface.",
    order: 165,
  },
  {
    id: "jumpHost",
    short: "-J",
    long: "-J",
    group: "connection",
    kind: "text",
    arg: { placeholder: "user@bastion:22", separator: " " },
    summary: "Connect via one or more jump (bastion) hosts.",
    detail:
      "[user@]host[:port], comma-separated for multiple hops. The modern, built-in replacement for -o ProxyCommand='ssh -W %h:%p ...'.",
    order: 170,
  },

  // ── authentication ────────────────────────────────────────────────────────
  {
    id: "cipherSpec",
    short: "-c",
    long: "-c",
    group: "authentication",
    kind: "text",
    arg: { placeholder: "aes256-gcm@openssh.com", separator: " " },
    summary: "Cipher(s) to use, in order of preference.",
    detail: "A comma-separated list. Only worth touching to work around a host that lacks ssh's default choice.",
    order: 400,
  },
  {
    id: "macSpec",
    short: "-m",
    long: "-m",
    group: "authentication",
    kind: "text",
    arg: { placeholder: "hmac-sha2-256", separator: " " },
    summary: "MAC algorithm(s) to use, in order of preference.",
    detail: "A comma-separated list, for the same kind of host-compatibility reason as -c.",
    order: 410,
  },
  {
    id: "pkcs11",
    short: "-I",
    long: "-I",
    group: "authentication",
    kind: "path",
    arg: { placeholder: "/usr/lib/opensc-pkcs11.so", separator: " " },
    summary: "PKCS#11 shared library for a hardware key or smart card.",
    detail: "Points ssh at the middleware that exposes keys held on a YubiKey, smart card, or similar token.",
    order: 420,
  },
  {
    id: "gssapiForwarding",
    short: "-K",
    long: "-K",
    group: "authentication",
    kind: "boolean",
    conflictsWith: ["gssapiNoForwarding"],
    danger: "caution",
    summary: "Enable GSSAPI authentication and forward credentials to the server.",
    detail: "Delegates your Kerberos ticket to the remote host, which can then use it to authenticate onward as you.",
    order: 430,
  },
  {
    id: "gssapiNoForwarding",
    short: "-k",
    long: "-k",
    group: "authentication",
    kind: "boolean",
    conflictsWith: ["gssapiForwarding"],
    summary: "Disable forwarding of GSSAPI credentials.",
    detail: "Useful to override an ssh_config default that turns forwarding on.",
    order: 440,
  },

  // ── forwarding ────────────────────────────────────────────────────────────
  {
    id: "agentForwarding",
    short: "-A",
    long: "-A",
    group: "forwarding",
    kind: "boolean",
    danger: "caution",
    summary: "Forward the local SSH agent to the remote host.",
    detail:
      "Lets the remote host use your local keys without copying them — but anyone with root on that host can then use your agent to authenticate elsewhere as you, for as long as the connection is open.",
    order: 200,
  },
  {
    id: "x11Forwarding",
    short: "-X",
    long: "-X",
    group: "forwarding",
    kind: "boolean",
    conflictsWith: ["x11ForwardingTrusted"],
    danger: "caution",
    summary: "Forward X11 (untrusted mode).",
    detail: "Lets remote graphical apps display locally, under X11's SECURITY extension restrictions.",
    order: 210,
  },
  {
    id: "x11ForwardingTrusted",
    short: "-Y",
    long: "-Y",
    group: "forwarding",
    kind: "boolean",
    conflictsWith: ["x11Forwarding"],
    danger: "caution",
    summary: "Forward X11 (trusted mode).",
    detail:
      "Bypasses the X11 SECURITY extension entirely. A malicious or compromised remote host can then do anything to your local X session — log keystrokes, read other windows' contents.",
    order: 220,
  },
  {
    id: "localForward",
    short: "-L",
    long: "-L",
    group: "forwarding",
    kind: "text",
    arg: { placeholder: "8080:localhost:80", separator: " " },
    summary: "Forward a local port to a destination reachable from the remote host.",
    detail:
      "Full form: [bind_address:]local_port:remote_host:remote_port. bind_address is optional — omitted, the listening port only accepts connections from this machine; destination_host:destination_port is resolved from the REMOTE (server) side, not locally. Either local_port or destination_host:destination_port may instead be a filesystem path — local_socket or destination_socket — to forward a Unix domain socket instead of a TCP port, e.g. /tmp/local.sock:/var/run/docker.sock.",
    order: 230,
  },
  {
    id: "remoteForward",
    short: "-R",
    long: "-R",
    group: "forwarding",
    kind: "text",
    arg: { placeholder: "8080:localhost:80", separator: " " },
    danger: "caution",
    summary: "Forward a remote port to a destination reachable from here.",
    detail:
      "Full form: [bind_address:]remote_port:local_host:local_port — the mirror image of -L. remote_port is opened on the SERVER side (bind_address there controls whether hosts other than the server itself can reach it — see -g/GatewayPorts); local_host:local_port is resolved from THIS (client) side, not remotely. Either remote_port or local_host:local_port may instead be a filesystem path — remote_socket or local_socket — to forward a Unix domain socket. Giving just [bind_address:]remote_port with no destination allocates the port without binding it to anything yet, for use with -O forward.",
    order: 240,
  },
  {
    id: "dynamicForward",
    short: "-D",
    long: "-D",
    group: "forwarding",
    kind: "text",
    arg: { placeholder: "1080", separator: " " },
    danger: "caution",
    summary: "Open a local SOCKS proxy through this connection.",
    detail:
      "Full form: [bind_address:]port. Traffic pointed at the local SOCKS proxy port exits from the remote host. bind_address is optional — omitted, the proxy only accepts connections from this machine; giving one explicitly (e.g. 0.0.0.0) lets other machines on your network use it too.",
    order: 250,
  },
  {
    id: "disableAgentForwarding",
    short: "-a",
    long: "-a",
    group: "forwarding",
    kind: "boolean",
    conflictsWith: ["agentForwarding"],
    summary: "Disable agent forwarding.",
    detail: "Agent forwarding is off by default — this exists to override an ssh_config that turns it on.",
    order: 260,
  },
  {
    id: "disableX11Forwarding",
    short: "-x",
    long: "-x",
    group: "forwarding",
    kind: "boolean",
    conflictsWith: ["x11Forwarding", "x11ForwardingTrusted"],
    summary: "Disable X11 forwarding.",
    detail: "X11 forwarding is off by default — this exists to override an ssh_config that turns it on.",
    order: 270,
  },
  {
    id: "gatewayPorts",
    short: "-g",
    long: "-g",
    group: "forwarding",
    kind: "boolean",
    danger: "caution",
    summary: "Allow other hosts to connect to locally forwarded ports.",
    detail:
      "Without this, a -L/-D forwarded port only accepts connections from this machine. With it, anything that can reach this machine's network can use the forward too.",
    order: 280,
  },
  {
    id: "stdioForward",
    long: "-W",
    group: "forwarding",
    kind: "text",
    arg: { placeholder: "host:port", separator: " " },
    summary: "Forward stdin/stdout to a single destination instead of opening a shell.",
    detail:
      "The mechanism -J is built on: turns ssh into a raw pipe to host:port. Mainly useful directly when scripting a jump manually instead of using -J.",
    order: 290,
  },
  {
    id: "tunnelDevice",
    short: "-w",
    long: "-w",
    group: "forwarding",
    kind: "text",
    danger: "caution",
    arg: { placeholder: "0:0", separator: " " },
    summary: "Request a tun(4) device forward — a full virtual network interface.",
    detail:
      "local_tun[:remote_tun]. Creates a real network tunnel rather than forwarding individual ports. Requires the server to allow it (PermitTunnel) and usually root on both ends.",
    order: 295,
  },

  // ── multiplexing (connection sharing) ────────────────────────────────────
  {
    id: "masterMode",
    short: "-M",
    long: "-M",
    group: "multiplexing",
    kind: "enum",
    options: [
      { value: "none", label: "Off", renders: "" },
      { value: "master", label: "Master mode (-M)", renders: "-M" },
      { value: "master-confirm", label: "Master mode, confirm each reuse (-MM)", renders: "-M -M" },
    ],
    summary: "Act as the master for connection sharing.",
    detail:
      "Subsequent ssh/scp/sftp commands to the same destination can reuse this connection via -S's control socket instead of opening a new one.",
    order: 500,
  },
  {
    id: "controlCommand",
    short: "-O",
    long: "-O",
    group: "multiplexing",
    kind: "enum",
    options: [
      { value: "none", label: "(not a control command)", renders: "" },
      { value: "check", label: "check — is the master still alive?", renders: "-O check" },
      { value: "forward", label: "forward — request forwardings only", renders: "-O forward" },
      { value: "cancel", label: "cancel — cancel forwardings", renders: "-O cancel" },
      { value: "exit", label: "exit — ask the master to exit", renders: "-O exit" },
      { value: "stop", label: "stop — stop accepting new multiplexed sessions", renders: "-O stop" },
    ],
    summary: "Send a control command to an existing master connection instead of starting a session.",
    detail: "Talks to the master through the control socket named by -S (or resolved from config) — no new connection is made.",
    order: 510,
  },
  {
    id: "controlPath",
    short: "-S",
    long: "-S",
    group: "multiplexing",
    kind: "path",
    arg: { placeholder: "~/.ssh/cm-%r@%h:%p", separator: " " },
    summary: "Location of the control socket for connection sharing.",
    detail: "Shared by the master (-M) and every client that reuses it (-O). \"none\" disables connection sharing outright.",
    order: 520,
  },

  // ── output / behavior ─────────────────────────────────────────────────────
  {
    id: "verbose",
    long: "-v",
    group: "output",
    kind: "enum",
    options: [
      { value: "none", label: "Quiet", renders: "" },
      { value: "1", label: "-v", renders: "-v" },
      { value: "2", label: "-vv", renders: "-vv" },
      { value: "3", label: "-vvv (debug)", renders: "-vvv" },
    ],
    summary: "Verbosity level.",
    detail: "-vvv is the level actually useful for debugging a failed connection or auth attempt.",
    order: 300,
  },
  {
    id: "quiet",
    short: "-q",
    long: "-q",
    group: "output",
    kind: "boolean",
    summary: "Suppress most warnings and diagnostics.",
    detail: "Quiet mode — errors are still shown, informational messages are not.",
    order: 310,
  },
  {
    id: "forcePty",
    short: "-t",
    long: "-t",
    group: "output",
    kind: "boolean",
    conflictsWith: ["disablePty"],
    summary: "Force pseudo-terminal allocation.",
    detail: "Needed to run interactive, full-screen remote programs when a remote command is also given.",
    order: 320,
  },
  {
    id: "disablePty",
    short: "-T",
    long: "-T",
    group: "output",
    kind: "boolean",
    conflictsWith: ["forcePty"],
    summary: "Disable pseudo-terminal allocation.",
    detail: "Correct for non-interactive remote commands that only produce output, not a shell.",
    order: 330,
  },
  {
    id: "noRemoteCommand",
    long: "-N",
    group: "output",
    kind: "boolean",
    summary: "Do not execute a remote command.",
    detail:
      "Useful when the whole point of the connection is port forwarding (-L/-R/-D) and no shell or remote command is needed.",
    order: 340,
  },
  {
    id: "background",
    long: "-f",
    group: "output",
    kind: "boolean",
    requires: ["noRemoteCommand"],
    summary: "Go to background before executing.",
    detail:
      "Requires -N (or a remote command) — there has to be something to stay backgrounded for, or ssh has nothing left to do once it forks.",
    order: 350,
  },
  {
    id: "stdinNull",
    short: "-n",
    long: "-n",
    group: "output",
    kind: "boolean",
    summary: "Redirect stdin from /dev/null.",
    detail: "Prevents ssh from reading local stdin — needed when backgrounding without -f in a script that has no input to give it.",
    order: 355,
  },
  {
    id: "version",
    short: "-V",
    long: "-V",
    group: "output",
    kind: "boolean",
    summary: "Print the ssh version and exit.",
    detail: "Nothing else in the command has any effect — ssh exits before connecting.",
    order: 360,
  },
  {
    id: "printConfig",
    short: "-G",
    long: "-G",
    group: "output",
    kind: "boolean",
    summary: "Print the evaluated configuration and exit, without connecting.",
    detail: "Shows what ssh_config resolves to for this destination — a dry-run for configuration, not for the connection itself.",
    order: 365,
  },
  {
    id: "syslog",
    short: "-y",
    long: "-y",
    group: "output",
    kind: "boolean",
    summary: "Send log information via syslog instead of stderr.",
    detail: "Matches how a backgrounded (-f) session's diagnostics are usually captured.",
    order: 370,
  },
  {
    id: "logFile",
    short: "-E",
    long: "-E",
    group: "output",
    kind: "path",
    arg: { placeholder: "ssh-debug.log", separator: " " },
    summary: "Append debug logs to this file instead of stderr.",
    detail: "Pairs with -v/-vv/-vvv when the terminal itself isn't a convenient place to capture the output.",
    order: 375,
  },
  {
    id: "escapeChar",
    short: "-e",
    long: "-e",
    group: "output",
    kind: "text",
    arg: { placeholder: "~", separator: " " },
    summary: "Set the escape character for interactive sessions (default ~).",
    detail: "Use \"none\" to disable the escape character entirely — needed when the session itself must transport literal ~-prefixed lines.",
    order: 380,
  },
  {
    id: "queryOption",
    short: "-Q",
    long: "-Q",
    group: "output",
    kind: "enum",
    options: [
      { value: "none", label: "(not a query)", renders: "" },
      { value: "cipher", label: "cipher — supported ciphers", renders: "-Q cipher" },
      { value: "cipher-auth", label: "cipher-auth — ciphers with integrated auth", renders: "-Q cipher-auth" },
      { value: "mac", label: "mac — supported MAC algorithms", renders: "-Q mac" },
      { value: "kex", label: "kex — supported key-exchange algorithms", renders: "-Q kex" },
      { value: "key", label: "key — supported key types", renders: "-Q key" },
      { value: "key-cert", label: "key-cert — supported certificate key types", renders: "-Q key-cert" },
      { value: "key-plain", label: "key-plain — supported plain key types", renders: "-Q key-plain" },
      { value: "key-sig", label: "key-sig — supported signature algorithms", renders: "-Q key-sig" },
      { value: "protocol-version", label: "protocol-version — supported SSH protocol version(s)", renders: "-Q protocol-version" },
      { value: "compression", label: "compression — supported compression schemes", renders: "-Q compression" },
    ],
    summary: "Query supported algorithms and exit, without connecting.",
    detail: "A reference lookup against this local ssh build — nothing else in the command has any effect when this is set.",
    order: 385,
  },
] as const;

export const CATALOGUE = createFlagCatalogue<FlagGroup>(FLAGS);

export const getFlag = CATALOGUE.getFlag;
export const requireFlag = CATALOGUE.requireFlag;
export const flagsInGroup = CATALOGUE.flagsInGroup;
export const flagsInArgvOrder = CATALOGUE.flagsInArgvOrder;

export function isUnavailable(flag: FlagDef, targetVersion: number): boolean {
  return isUnavailableGeneric(flag, targetVersion);
}

export function flagLabel(flag: FlagDef): string {
  return flagLabelGeneric(flag);
}
