import {
  createFlagCatalogue,
  flagLabel as flagLabelGeneric,
  type DangerLevel,
  type FlagArgSpec,
  type FlagDef as FlagDefGeneric,
  type FlagEnumOption,
  type FlagKind,
} from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type { DangerLevel, FlagArgSpec, FlagEnumOption, FlagKind };
export type FlagDef = FlagDefGeneric<FlagGroup>;

export const FLAGS: readonly FlagDef[] = [
  // ── display (POSIX) ──────────────────────────────────────────────────────
  {
    id: "long",
    short: "-l",
    long: "-l",
    group: "display",
    kind: "boolean",
    preferShort: true,
    availableOn: ["posix"],
    summary: "Long format — permissions, owner, size, modification time.",
    detail: "The format most other flags here (sizes, sorting by time) are meant to be read alongside.",
    order: 100,
  },
  {
    id: "all",
    short: "-a",
    long: "-a",
    group: "display",
    kind: "boolean",
    preferShort: true,
    availableOn: ["posix"],
    summary: "Show hidden entries, including . and ..",
    detail: "Lists dotfiles and the current/parent directory entries too.",
    order: 110,
  },
  {
    id: "almostAll",
    short: "-A",
    long: "-A",
    group: "display",
    kind: "boolean",
    preferShort: true,
    availableOn: ["posix"],
    summary: "Show hidden entries, but not . or ..",
    detail: "Usually what you actually want instead of -a — dotfiles without the noise of . and ..",
    order: 120,
  },
  {
    id: "humanReadable",
    short: "-h",
    long: "-h",
    group: "display",
    kind: "boolean",
    preferShort: true,
    requires: ["long"],
    availableOn: ["posix"],
    summary: "Print sizes in human units (K/M/G).",
    detail: "Only affects anything visible with -l, which is the only format that prints sizes.",
    order: 130,
  },
  {
    id: "classify",
    short: "-F",
    long: "-F",
    group: "display",
    kind: "boolean",
    preferShort: true,
    availableOn: ["posix"],
    summary: "Append an indicator to entries (/, *, @, ...).",
    detail: "/ for directories, * for executables, @ for symlinks, and a few more — quick visual triage.",
    order: 140,
  },
  {
    id: "showInode",
    short: "-i",
    long: "-i",
    group: "display",
    kind: "boolean",
    preferShort: true,
    availableOn: ["posix"],
    summary: "Print the inode number of each entry.",
    detail: "Useful for telling apart hard links to the same file, or for scripting against find -inum.",
    order: 150,
  },
  {
    id: "color",
    long: "--color",
    group: "display",
    kind: "enum",
    availableOn: ["posix"],
    options: [
      { value: "auto", label: "Auto (default)", renders: "" },
      { value: "always", label: "Always", renders: "--color=always" },
      { value: "never", label: "Never", renders: "--color=never" },
    ],
    summary: "Whether to colorize output.",
    detail: "\"Auto\" only colorizes when the output is a terminal — never garbles a pipe or redirect.",
    order: 160,
  },
  {
    id: "oneLine",
    short: "-1",
    long: "-1",
    group: "display",
    kind: "boolean",
    preferShort: true,
    availableOn: ["posix"],
    summary: "One entry per line.",
    detail: "Forces single-column output, e.g. for piping into another command.",
    order: 170,
  },

  // ── display (PowerShell / Get-ChildItem) ─────────────────────────────────
  {
    id: "forceHiddenPs",
    long: "-Force",
    group: "display",
    kind: "boolean",
    availableOn: ["powershell"],
    summary: "Show hidden and system entries.",
    detail:
      "Get-ChildItem excludes hidden/system items by default; -Force includes them — the closest equivalent to -a/-A.",
    order: 180,
  },
  {
    id: "nameOnlyPs",
    long: "-Name",
    group: "display",
    kind: "boolean",
    availableOn: ["powershell"],
    summary: "Output just the names, one per line.",
    detail: "Suppresses the Mode/LastWriteTime/Length columns entirely — the closest equivalent to -1.",
    order: 185,
  },
  {
    id: "directoryOnlyPs",
    long: "-Directory",
    group: "display",
    kind: "boolean",
    conflictsWith: ["fileOnlyPs"],
    availableOn: ["powershell"],
    summary: "List only directories, not files.",
    detail: "Filters the listing down to subdirectories. No direct POSIX ls flag does this (a shell glob like */ is the usual equivalent).",
    order: 190,
  },
  {
    id: "fileOnlyPs",
    long: "-File",
    group: "display",
    kind: "boolean",
    conflictsWith: ["directoryOnlyPs"],
    availableOn: ["powershell"],
    summary: "List only files, not directories.",
    detail: "The inverse of -Directory.",
    order: 195,
  },

  // ── sorting (POSIX only — PowerShell sorts via a separate Sort-Object ──
  // pipeline stage, not a Get-ChildItem flag, so there is no equivalent to
  // offer here without modeling a whole pipeline stage) ────────────────────
  {
    id: "sortBy",
    long: "--sort",
    group: "sorting",
    kind: "enum",
    availableOn: ["posix"],
    options: [
      { value: "name", label: "Name (default)", renders: "" },
      { value: "time", label: "Modification time (-t)", renders: "-t" },
      { value: "size", label: "Size, largest first (-S)", renders: "-S" },
      { value: "extension", label: "Extension (-X)", renders: "-X" },
      { value: "none", label: "None — directory order (-U)", renders: "-U" },
    ],
    summary: "What order to list entries in.",
    detail: "-U (no sorting) is the fastest option on very large directories, since it skips the sort entirely.",
    order: 200,
  },
  {
    id: "reverse",
    short: "-r",
    long: "-r",
    group: "sorting",
    kind: "boolean",
    preferShort: true,
    availableOn: ["posix"],
    summary: "Reverse the sort order.",
    detail: "Combine with --sort=time for oldest-first, or the default name sort for Z-to-A.",
    order: 210,
  },
  {
    id: "groupDirectoriesFirst",
    long: "--group-directories-first",
    group: "sorting",
    kind: "boolean",
    availableOn: ["posix"],
    summary: "List all directories before files.",
    detail: "Applied before the chosen sort order within each group. GNU ls only.",
    order: 220,
  },

  // ── recursion (POSIX) ────────────────────────────────────────────────────
  {
    id: "recursive",
    short: "-R",
    long: "-R",
    group: "recursion",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["directory"],
    availableOn: ["posix"],
    summary: "List subdirectories recursively.",
    detail: "Can produce a lot of output fast on a deep tree — pair with -1 if piping elsewhere.",
    order: 300,
  },
  {
    id: "directory",
    short: "-d",
    long: "-d",
    group: "recursion",
    kind: "boolean",
    preferShort: true,
    conflictsWith: ["recursive"],
    availableOn: ["posix"],
    summary: "List directories themselves, not their contents.",
    detail: "The opposite of the default — shows the directory entry itself rather than descending into it.",
    order: 310,
  },
  {
    id: "followSymlinks",
    short: "-L",
    long: "-L",
    group: "recursion",
    kind: "boolean",
    preferShort: true,
    availableOn: ["posix"],
    summary: "Follow symlinks as if they were the real thing.",
    detail: "When a listed path is a symlink to a directory, list its contents rather than the link itself.",
    order: 320,
  },

  // ── recursion (PowerShell / Get-ChildItem) ───────────────────────────────
  {
    id: "recursePs",
    long: "-Recurse",
    group: "recursion",
    kind: "boolean",
    availableOn: ["powershell"],
    summary: "List subdirectories recursively.",
    detail: "Same idea as -R — PowerShell's own recursion. Combine with -Depth to bound it.",
    order: 330,
  },
  {
    id: "followSymlinkPs",
    long: "-FollowSymlink",
    group: "recursion",
    kind: "boolean",
    availableOn: ["powershell"],
    summary: "Follow symlinks as if they were the real thing.",
    detail: "Only meaningful together with -Recurse.",
    order: 340,
  },
  {
    id: "depthPs",
    long: "-Depth",
    group: "recursion",
    kind: "number",
    requires: ["recursePs"],
    availableOn: ["powershell"],
    arg: { placeholder: "2", separator: " " },
    summary: "Limit recursion to this many levels deep.",
    detail: "Without this, -Recurse descends the entire tree.",
    order: 350,
  },
] as const;

export const CATALOGUE = createFlagCatalogue<FlagGroup>(FLAGS);

export const getFlag = CATALOGUE.getFlag;
export const requireFlag = CATALOGUE.requireFlag;
export const flagsInGroup = CATALOGUE.flagsInGroup;
export const flagsInArgvOrder = CATALOGUE.flagsInArgvOrder;

export function flagLabel(flag: FlagDef): string {
  return flagLabelGeneric(flag);
}
