import { createFlagCatalogue, type FlagDef as FlagDefGeneric } from "@cmdgen/engine";
import type { FlagGroup } from "./groups";

export type EncFlagDef = FlagDefGeneric<FlagGroup>;

/** Modeled from the real `openssl enc -help` output. */
export const ENC_FLAGS: readonly EncFlagDef[] = [
  {
    id: "decrypt",
    short: "-d",
    preferShort: true,
    long: "--decrypt",
    group: "options",
    kind: "boolean",
    conflictsWith: ["encrypt"],
    summary: "Decrypt the input instead of encrypting it.",
    detail: "Real enc defaults to encrypt (-e) when neither is given; this app renders -e explicitly when this is off, for clarity.",
    order: 10,
  },
  {
    id: "encrypt",
    short: "-e",
    preferShort: true,
    long: "--encrypt",
    group: "options",
    kind: "boolean",
    conflictsWith: ["decrypt"],
    summary: "Encrypt the input (the default action).",
    detail: "Included explicitly here for clarity, even though real enc already defaults to this when neither -e nor -d is given.",
    order: 20,
  },
  {
    id: "base64",
    short: "-a",
    preferShort: true,
    long: "--base64",
    group: "options",
    kind: "boolean",
    summary: "Base64 encode the output (when encrypting) or decode the input (when decrypting).",
    detail: "Needed whenever the ciphertext has to survive as printable text, e.g. pasted into an email or a text field.",
    order: 30,
  },
  {
    id: "pass",
    long: "-pass",
    group: "options",
    kind: "text",
    arg: { placeholder: "pass:hunter2", separator: " " },
    summary: "Passphrase source, e.g. pass:<value>, env:<var>, or file:<path>.",
    detail: "The modern replacement for the deprecated -k/-kfile flags — avoids the passphrase ever appearing in shell history via -k.",
    order: 40,
  },
  {
    id: "pbkdf2",
    long: "-pbkdf2",
    group: "options",
    kind: "boolean",
    summary: "Derive the key from the passphrase using PBKDF2.",
    detail: "The modern, recommended key-derivation choice — real openssl now warns if you don't pass this alongside a passphrase.",
    order: 50,
  },
  {
    id: "iter",
    long: "-iter",
    group: "options",
    kind: "number",
    arg: { placeholder: "10000", separator: " " },
    requires: ["pbkdf2"],
    summary: "PBKDF2 iteration count.",
    detail: "Higher is more resistant to brute-force but slower; real openssl defaults to 10000 and forces PBKDF2 when this is set.",
    order: 60,
  },
  {
    id: "salt",
    long: "-salt",
    group: "options",
    kind: "boolean",
    conflictsWith: ["nosalt"],
    summary: "Use a salt in key derivation (the default).",
    detail: "Randomizes the derived key even when the same passphrase is reused across encryptions.",
    order: 70,
  },
  {
    id: "nosalt",
    long: "-nosalt",
    group: "options",
    kind: "boolean",
    conflictsWith: ["salt"],
    danger: "caution",
    summary: "Disable the salt in key derivation.",
    detail: "Makes the derived key deterministic across encryptions of the same passphrase — a real, meaningful weakening.",
    order: 80,
  },
  {
    id: "nopad",
    long: "-nopad",
    group: "options",
    kind: "boolean",
    summary: "Disable standard block padding.",
    detail: "The input length must already be a multiple of the cipher's block size, or decryption/encryption will fail.",
    order: 90,
  },
] as const;
export const ENC_CATALOGUE = createFlagCatalogue<FlagGroup>(ENC_FLAGS);

/** `rsautl` is deprecated in favor of `pkeyutl` but still common in the wild — kept intentionally minimal. */
export const RSAUTL_FLAGS: readonly EncFlagDef[] = [
  {
    id: "encrypt",
    long: "-encrypt",
    group: "options",
    kind: "boolean",
    conflictsWith: ["decrypt", "sign", "verify"],
    summary: "Encrypt the input with the given public/private key.",
    detail: "Exactly one of Encrypt/Decrypt/Sign/Verify must be chosen — real rsautl errors otherwise.",
    order: 10,
  },
  {
    id: "decrypt",
    long: "-decrypt",
    group: "options",
    kind: "boolean",
    conflictsWith: ["encrypt", "sign", "verify"],
    summary: "Decrypt the input with the given private key.",
    detail: "Exactly one of Encrypt/Decrypt/Sign/Verify must be chosen — real rsautl errors otherwise.",
    order: 20,
  },
  {
    id: "sign",
    long: "-sign",
    group: "options",
    kind: "boolean",
    conflictsWith: ["encrypt", "decrypt", "verify"],
    summary: "Sign the input with the given private key.",
    detail: "Exactly one of Encrypt/Decrypt/Sign/Verify must be chosen — real rsautl errors otherwise.",
    order: 30,
  },
  {
    id: "verify",
    long: "-verify",
    group: "options",
    kind: "boolean",
    conflictsWith: ["encrypt", "decrypt", "sign"],
    summary: "Verify a signature against the input using the given public key.",
    detail: "Exactly one of Encrypt/Decrypt/Sign/Verify must be chosen — real rsautl errors otherwise.",
    order: 40,
  },
  {
    id: "pubin",
    long: "-pubin",
    group: "options",
    kind: "boolean",
    summary: "Treat the key file as a public key rather than a private key.",
    detail: "Needed when the key file given is a public key, e.g. verifying a signature or encrypting to someone else's key.",
    order: 50,
  },
] as const;
export const RSAUTL_CATALOGUE = createFlagCatalogue<FlagGroup>(RSAUTL_FLAGS);

export const PKEYUTL_FLAGS: readonly EncFlagDef[] = [
  {
    id: "encrypt",
    long: "-encrypt",
    group: "options",
    kind: "boolean",
    conflictsWith: ["decrypt", "sign", "verify", "derive"],
    summary: "Encrypt the input with the given public key.",
    detail: "Exactly one of Encrypt/Decrypt/Sign/Verify/Derive must be chosen — real pkeyutl errors otherwise.",
    order: 10,
  },
  {
    id: "decrypt",
    long: "-decrypt",
    group: "options",
    kind: "boolean",
    conflictsWith: ["encrypt", "sign", "verify", "derive"],
    summary: "Decrypt the input with the given private key.",
    detail: "Exactly one of Encrypt/Decrypt/Sign/Verify/Derive must be chosen — real pkeyutl errors otherwise.",
    order: 20,
  },
  {
    id: "sign",
    long: "-sign",
    group: "options",
    kind: "boolean",
    conflictsWith: ["encrypt", "decrypt", "verify", "derive"],
    summary: "Sign the input with the given private key.",
    detail: "Exactly one of Encrypt/Decrypt/Sign/Verify/Derive must be chosen — real pkeyutl errors otherwise.",
    order: 30,
  },
  {
    id: "verify",
    long: "-verify",
    group: "options",
    kind: "boolean",
    conflictsWith: ["encrypt", "decrypt", "sign", "derive"],
    summary: "Verify a signature against the input using the given public key.",
    detail: "Exactly one of Encrypt/Decrypt/Sign/Verify/Derive must be chosen — real pkeyutl errors otherwise.",
    order: 40,
  },
  {
    id: "derive",
    long: "-derive",
    group: "options",
    kind: "boolean",
    conflictsWith: ["encrypt", "decrypt", "sign", "verify"],
    summary: "Derive a shared secret (e.g. via ECDH/X25519) using the given private key and a peer's public key.",
    detail: "Exactly one of Encrypt/Decrypt/Sign/Verify/Derive must be chosen — real pkeyutl errors otherwise.",
    order: 50,
  },
  {
    id: "pubin",
    long: "-pubin",
    group: "options",
    kind: "boolean",
    summary: "Treat the key file as a public key rather than a private key.",
    detail: "Needed when the key file given is a public key, e.g. verifying a signature or encrypting to someone else's key.",
    order: 60,
  },
] as const;
export const PKEYUTL_CATALOGUE = createFlagCatalogue<FlagGroup>(PKEYUTL_FLAGS);
